Repository reframe-hpc/reframe, pull requests merged in 2018-02, with the labels that each got.

#38 Enable CI
  Jenkinsfile
  ci-scripts/ci-runner.bash
  config/cscs.py
  config/generic.py
  reframe/settings.py
Labels: ci, enhancement, prio: important

#82 Parse Github comments to trigger the CI on specific machines
  Jenkinsfile
Labels: ci, enhancement, prio: important

#87 Enable Travis CI
  .travis.yml
  Jenkinsfile
  README.md
  requirements.txt
Labels: ci, enhancement, prio: normal

#89 Fix logging config in generic settings
  ci-scripts/ci-runner.bash
  config/generic.py
Labels: bugfix, frontend, prio: important

#131 CI: use machinesToRun in the "cleanup stale" phase
  Jenkinsfile
Labels: bugfix, ci, prio: important

#123 Add prefix 'rfm_' to the given job name
  reframe/core/schedulers/__init__.py
  unittests/test_launchers.py
  unittests/test_schedulers.py
Labels: backend, enhancement, prio: normal

#129 Fix emission of Slurm's --exclusive flag
  reframe/core/schedulers/slurm.py
  unittests/test_schedulers.py
Labels: backend, bugfix, prio: normal

#135 Fix occasional unit test failure in async policy.
  unittests/resources/frontend_checks.py
Labels: bugfix, frontend, prio: important

#132 Remove 'pre_run' and 'post_run' access from 'job'
  cscs-checks/apps/openfoam-extend/check_openfoam_extend.py
  cscs-checks/apps/openfoam/check_openfoam.py
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
  cscs-checks/tools/profiling_and_debugging/notool.py
  cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
Labels: bugfix, enhancement, prio: normal, regression test

#141 Add ICON RRTMGP regression test.
  cscs-checks/apps/icon/rrtmgp_check.py
Labels: prio: normal, regression test

#142 Fix git cloning for Leone
  Jenkinsfile
Labels: bugfix, ci, prio: important

#144 Fix environment import in site config loader
  reframe/frontend/loader.py
Labels: code quality, enhancement

#145 Fix confusing error messages in serial execution policy.
  reframe/frontend/executors/policies.py
Labels: bugfix, frontend, prio: normal

#121 Add G2G meteoswiss check
  config/cscs.py
  cscs-checks/microbenchmarks/mch/g2g_meteoswiss_check.py
Labels: prio: important, regression test

#149 Reenable 'switches' resource in 'cscs' settings
  config/cscs.py
Labels: enhancement, prio: important
