Repository reframe-hpc/reframe, pull requests merged in 2018-07, with the labels that each got.

#352 [bugfix] Comment out Graylog handler from CSCS config
  config/cscs.py
Labels: bugfix, enhancement, prio: urgent

#350 [bugfix] Fix expected OpenMP versions for Dom
  cscs-checks/tools/profiling_and_debugging/notool.py
Labels: bugfix, prio: important, regression test

#348 [test] Update PrgEnv-pgi definitions on Kesch
  config/cscs.py
  cscs-checks/prgenv/gpu_direct_acc.py
Labels: enhancement, prio: important

#353 [ci] Check added/modified regression tests w.r.t master
  ci-scripts/ci-runner.bash
Labels: ci, prio: normal

#358 [bugfix] Change the resources dir path
  config/cscs-pbs.py
  config/cscs.py
Labels: bugfix, prio: important

#361 [bugfix] Enable sphinx versioning only for releases
  docs/conf.py
  docs/tutorial.rst
Labels: bugfix, documentation, enhancement, prio: normal

#399 [feat] Allow purging modules before running regression tests
  reframe/frontend/cli.py
Labels: enhancement, frontend, prio: low

#359 [feat] Evaluate and log all performance values before asserting them
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: backend, enhancement, prio: normal

#406 [ci] Temporarily disable running of checks on Daint
  ci-scripts/ci-runner.bash
Labels: ci, enhancement, prio: important

#340 [feat] Add a new infrastructure for build systems
  reframe/core/buildsystems.py
  reframe/core/environments.py
  reframe/core/exceptions.py
  reframe/core/fields.py
  reframe/core/launchers/__init__.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  reframe/core/shell.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  reframe/settings.py
  unittests/resources/checks/hellocheck_make.py
  unittests/resources/settings.py
  unittests/test_buildsystems.py
  unittests/test_cli.py
  unittests/test_environments.py
  unittests/test_fields.py
  unittests/test_launchers.py
  unittests/test_pipeline.py
  unittests/test_policies.py
  unittests/test_schedulers.py
  unittests/test_script_builders.py
  unittests/test_shell.py
Labels: backend, enhancement, prio: normal

#404 [test] Adapt the petsc test for PE 18.07
  cscs-checks/libraries/petsc/petsc_helloworld.py
  cscs-checks/libraries/petsc/src/petsc_poisson2d.ref
  cscs-checks/libraries/petsc/src/poisson2d.c
Labels: enhancement, prio: normal, regression test

#405 [bugfix] Fix bug in unloading of conflicting modules
  reframe/core/environments.py
Labels: backend, bugfix, prio: normal

#401 [test] Adapt Paraview check for PE 18.07
  cscs-checks/apps/paraview/paraview_check.py
  cscs-checks/apps/paraview/src/coloredSphere.py
Labels: enhancement, prio: normal, regression test

#408 [test] Adapt the Boost Python test for PE 18.07
  cscs-checks/libraries/boost/boost_python_check.py
Labels: enhancement, prio: normal, regression test

#409 [test] Adapt Tensorflow tests for PE 18.07
  cscs-checks/apps/tensorflow/tensorflow_check.py
Labels: enhancement, prio: normal, regression test

#412 [test] Adapt the nco test for PE 18.07
  cscs-checks/tools/io/nco.py
Labels: enhancement, prio: important, regression test

#414 [test] Adapt nvprof test to PE 18.07
  cscs-checks/tools/profiling_and_debugging/nvprof.py
Labels: enhancement, prio: normal, regression test
