Repository reframe-hpc/reframe, pull requests merged in 2018-09, with the labels that each got.

#434 [test] Adapt netcdf tests to build systems
  cscs-checks/libraries/io/netcdf_compile_run.py
Labels: enhancement, prio: normal, regression test

#436 [ci] Remove monch from the machinesList
  Jenkinsfile
Labels: ci, prio: normal

#437 [bugfix] Add a persistent version of rmtree()
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/utility/os_ext.py
  unittests/test_cli.py
  unittests/test_pipeline.py
  unittests/test_policies.py
  unittests/test_schedulers.py
  unittests/test_utility.py
Labels: backend, bugfix, prio: important

#433 [doc] Update documentation for the build systems feature
  docs/advanced.rst
  docs/reference.rst
  docs/tutorial.rst
  reframe/core/buildsystems.py
  reframe/core/pipeline.py
  tutorial/advanced/advanced_example1.py
  tutorial/advanced/advanced_example4.py
  tutorial/advanced/advanced_example8.py
  tutorial/example2.py
  tutorial/example3.py
  tutorial/example4.py
  tutorial/example7.py
  tutorial/example8.py
Labels: documentation, enhancement, prio: normal

#416 [test] Adapt helloworld tests to build systems
  cscs-checks/prgenv/helloworld.py
Labels: enhancement, prio: normal, regression test

#439 [test] Adapt perftools to use build systems
  cscs-checks/tools/profiling_and_debugging/perftools.py
  cscs-checks/tools/profiling_and_debugging/src/C++/Makefile_perftools
  cscs-checks/tools/profiling_and_debugging/src/C/Makefile_perftools
  cscs-checks/tools/profiling_and_debugging/src/Cuda/Makefile_perftools
  cscs-checks/tools/profiling_and_debugging/src/F90/Makefile_perftools
Labels: enhancement, prio: important, regression test

#441 [bugfix] Do not load environments twice
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: backend, bugfix, prio: urgent

#440 [bugfix] Convert message for inexistent test files to warning
  reframe/frontend/cli.py
Labels: bugfix, frontend, prio: normal

#445 [bugfix] Fix reading of 'logdir' setting from system config
  docs/configure.rst
  docs/running.rst
  reframe/core/config.py
  reframe/core/runtime.py
  reframe/core/systems.py
  reframe/frontend/cli.py
  unittests/resources/settings.py
  unittests/test_config.py
  unittests/test_runtime.py
Labels: bugfix, frontend, prio: important

#447 [feat] Add support for CMake
  docs/advanced.rst
  docs/tutorial.rst
  reframe/core/buildsystems.py
  reframe/core/pipeline.py
  unittests/test_buildsystems.py
Labels: backend, enhancement, prio: normal

#442 [test] Update OSU microbenchmark test to new syntax and build system
  cscs-checks/microbenchmarks/osu/osu_tests.py
  cscs-checks/microbenchmarks/osu/src/Makefile_alltoall
  cscs-checks/microbenchmarks/osu/src/Makefile_g2g
  cscs-checks/microbenchmarks/osu/src/Makefile_p2p
Labels: enhancement, prio: normal, regression test

#356 [ci] Add testing for python3.7 in travis
  .travis.yml
Labels: ci, enhancement, prio: normal

#452 [feat] Add support for Autotools-based projects
  docs/advanced.rst
  reframe/core/buildsystems.py
  reframe/core/pipeline.py
  unittests/test_buildsystems.py
Labels: backend, enhancement, prio: normal

#420 [test] Adapt stream microbenchmark test to build systems
  cscs-checks/microbenchmarks/stream/stream.py
Labels: enhancement, prio: normal, regression test

#457 [test] Replace FFLAGS with FCFLAGS in Makefiles
  cscs-checks/compile/src/haswell_fma/Makefile
  cscs-checks/tools/profiling_and_debugging/src/F90/Makefile
  cscs-checks/tools/profiling_and_debugging/src/F90/Makefile_perftools
  cscs-checks/tools/profiling_and_debugging/src/F90/Makefile_scorep_mpi_omp
Labels: bugfix, prio: important, regression test

#460 [ci] Automate deployment and generation of release notes
  ci-scripts/deploy.sh
  ci-scripts/genrelnotes.py
Labels: ci, enhancement, prio: normal

#459 [test] Increase GROMACS sanity check tolerance to 0.1%
  cscs-checks/apps/gromacs/gromacs_check.py
Labels: enhancement, prio: normal, regression test

#461 [test] Adapt cuda nvml check to build systems
  cscs-checks/cuda/nvml_check.py
Labels: enhancement, prio: normal, regression test

#462 [test] Adapt gpu direct test to build systems
  cscs-checks/prgenv/gpu_direct_acc.py
  cscs-checks/prgenv/gpu_direct_cuda.py
Labels: enhancement, prio: normal, regression test

#466 [test] Adapt trilinos regression test to PE18.08 and build systems
  cscs-checks/libraries/math/trilinos_compile_run.py
Labels: prio: normal, regression test

#464 [feat] Use different stage and output directories for different retries of the same test
  reframe/core/runtime.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/statistics.py
  unittests/test_policies.py
Labels: enhancement, frontend, prio: normal

#477 [ci] Adapt Kesch settings
  config/cscs.py
Labels: backend, enhancement, prio: important

#474 [bugfix] Remove time limit from build jobs
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  unittests/test_launchers.py
Labels: backend, bugfix, prio: normal

#481 [test] Add matrix file add20.rua in the src dir
  cscs-checks/libraries/math/src/add20.rua
  cscs-checks/libraries/math/trilinos_compile_run.py
Labels: enhancement, prio: normal, regression test

#476 [test] Set required version for tests using build systems
  cscs-checks/compile/haswell_fma_check.py
  cscs-checks/compile/libsci_resolve.py
  cscs-checks/cuda/cuda_checks.py
  cscs-checks/cuda/multi_gpu.py
  cscs-checks/cuda/nvml_check.py
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/dgemm.py
  cscs-checks/libraries/math/scalapack_compile_run.py
  cscs-checks/libraries/math/trilinos_compile_run.py
  cscs-checks/libraries/petsc/petsc_helloworld.py
  cscs-checks/microbenchmarks/osu/osu_tests.py
  cscs-checks/microbenchmarks/stream/stream.py
  cscs-checks/prgenv/gpu_direct_acc.py
  cscs-checks/prgenv/gpu_direct_cuda.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
  cscs-checks/tools/profiling_and_debugging/ddt.py
  cscs-checks/tools/profiling_and_debugging/notool.py
  cscs-checks/tools/profiling_and_debugging/nvprof.py
  cscs-checks/tools/profiling_and_debugging/perftools.py
  cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
Labels: regression test

#484 [test] Remove the matrix file from version control
  cscs-checks/libraries/math/src/add20.rua
  cscs-checks/libraries/math/trilinos_compile_run.py
Labels: enhancement, prio: normal, regression test
