Repository reframe-hpc/reframe, pull requests merged in 2018-10, with the labels that each got.

#463 [test] Publish MAGMA tests and adapt to PE 18.08
  cscs-checks/libraries/magma/magma-2.2/Makefile_cblas_z
  cscs-checks/libraries/magma/magma-2.2/Makefile_zgemm
  cscs-checks/libraries/magma/magma-2.2/Makefile_zsymmetrize
  cscs-checks/libraries/magma/magma-2.2/Makefile_ztranspose
  cscs-checks/libraries/magma/magma-2.2/Makefile_zunmbr
  cscs-checks/libraries/magma/magma-2.2/flops.h
  cscs-checks/libraries/magma/magma-2.2/license.txt
  cscs-checks/libraries/magma/magma-2.2/magma_util.cpp
  cscs-checks/libraries/magma/magma-2.2/patch.txt
  cscs-checks/libraries/magma/magma-2.2/testing_c.h
  cscs-checks/libraries/magma/magma-2.2/testing_cblas_z.cpp
  cscs-checks/libraries/magma/magma-2.2/testing_d.h
  cscs-checks/libraries/magma/magma-2.2/testing_s.h
  cscs-checks/libraries/magma/magma-2.2/testing_z.h
  cscs-checks/libraries/magma/magma-2.2/testing_zgemm.cpp
  cscs-checks/libraries/magma/magma-2.2/testing_zsymmetrize.cpp
  cscs-checks/libraries/magma/magma-2.2/testing_ztranspose.cpp
  cscs-checks/libraries/magma/magma-2.2/testing_zunmbr.cpp
  cscs-checks/libraries/magma/magma-2.2/testings.h
  cscs-checks/libraries/magma/magma-2.4/Makefile_cblas_z
  cscs-checks/libraries/magma/magma-2.4/Makefile_zgemm
  cscs-checks/libraries/magma/magma-2.4/Makefile_zsymmetrize
  cscs-checks/libraries/magma/magma-2.4/Makefile_ztranspose
  cscs-checks/libraries/magma/magma-2.4/Makefile_zunmbr
  cscs-checks/libraries/magma/magma-2.4/flops.h
  cscs-checks/libraries/magma/magma-2.4/license.txt
  cscs-checks/libraries/magma/magma-2.4/magma_lapack.hpp
  cscs-checks/libraries/magma/magma-2.4/magma_matrix.hpp
  cscs-checks/libraries/magma/magma-2.4/magma_util.cpp
  cscs-checks/libraries/magma/magma-2.4/patch.txt
  cscs-checks/libraries/magma/magma-2.4/testing_c.h
  cscs-checks/libraries/magma/magma-2.4/testing_cblas_z.cpp
  cscs-checks/libraries/magma/magma-2.4/testing_d.h
  cscs-checks/libraries/magma/magma-2.4/testing_s.h
  cscs-checks/libraries/magma/magma-2.4/testing_z.h
  cscs-checks/libraries/magma/magma-2.4/testing_zgemm.cpp
  cscs-checks/libraries/magma/magma-2.4/testing_zsymmetrize.cpp
  cscs-checks/libraries/magma/magma-2.4/testing_ztranspose.cpp
  cscs-checks/libraries/magma/magma-2.4/testing_zunmbr.cpp
  cscs-checks/libraries/magma/magma-2.4/testings.h
  cscs-checks/libraries/magma/magma_checks.py
Labels: prio: normal, regression test

#480 [bugfix] Remove the validation of the name of the test's base classes
  reframe/frontend/loader.py
  unittests/resources/checks/bad/relative_imports.py
Labels: bugfix, prio: normal

#487 [feat] List only the checks that are supported on the current system
  reframe/frontend/cli.py
Labels: enhancement, prio: normal

#492 [doc] Update documentation on the topic of filtering tests by system
  docs/running.rst
Labels: documentation, prio: important

#342 [test] New OpenACC/CUDA/C++ test from MCH
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/mch/src/Makefile
  cscs-checks/mch/src/compute_cuda.cu
  cscs-checks/mch/src/openacc_cuda_mpi_cppstd.F90
  cscs-checks/mch/src/std_cpp_call.cpp
Labels: prio: normal, regression test

#482 [test] Adapt NetCDF test to Kesch
  cscs-checks/libraries/io/netcdf_compile_run.py
Labels: prio: normal, regression test

#500 [test] Remove `PrgEnv-gnu` support from the Scalapack test on Kesch
  cscs-checks/libraries/math/scalapack_compile_run.py
Labels: prio: normal, regression test

#494 [refactor] Better support for dynamic type checking and field validation
  reframe/core/buildsystems.py
  reframe/core/config.py
  reframe/core/environments.py
  reframe/core/fields.py
  reframe/core/launchers/__init__.py
  reframe/core/modules.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/core/schedulers/__init__.py
  reframe/core/systems.py
  reframe/utility/typecheck.py
  unittests/test_fields.py
  unittests/test_typecheck.py
Labels: code quality, prio: normal

#501 [test] Adapt QE test to PE18.08
  cscs-checks/apps/espresso/espresso_check.py
Labels: prio: important, regression test

#502 [test] Adapt the LAMMPS test to PE18.08
  cscs-checks/apps/lammps/lammps_check.py
Labels: prio: important, regression test

#504 [test] Adjust LAMMPS performance values
  cscs-checks/apps/lammps/lammps_check.py
Labels: enhancement, prio: normal, regression test

#347 [test] Add MCH `alltoallv` check
  config/cscs.py
  cscs-checks/mch/alltoallv.py
Labels: prio: normal, regression test

#505 [test] Adapt IOR checks to build systems
  cscs-checks/system/io/ior_check.py
Labels: enhancement, prio: normal

#485 [refactor] Pass `sched_*` options to `options` list in slurm
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  unittests/test_launchers.py
  unittests/test_schedulers.py
Labels: code quality, enhancement, prio: normal

#509 [test] Add MCH halo exchange benchmark
  cscs-checks/mch/collectives_halo.py
Labels: prio: normal, regression test

#517 [ci] Re-enable running modified tests on Daint
  ci-scripts/ci-runner.bash
Labels: ci, prio: important

#515 [test] Adapt Score-P modules to PE 18.08
  cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
Labels: prio: important, regression test

#516 [test] Adapt the TensorFlow module name for PE 18.08
  cscs-checks/apps/tensorflow/tensorflow_check.py
Labels: prio: important, regression test

#518 [test] Adapt boost tests to latest pe18.08
  cscs-checks/libraries/boost/boost_python_check.py
Labels: prio: important, regression test

#514 [test] Add MCH CUDA stress test
  cscs-checks/mch/cuda_stress_test.py
  cscs-checks/mch/src/cuda_stencil_test.cu
Labels: prio: normal, regression test

#519 [test] Sync OpenMP versions for Dom/Daint in notool test
  cscs-checks/tools/profiling_and_debugging/notool.py
Labels: prio: important, regression test

#506 [feat] Add new command-line option for more verbose test listing
  docs/advanced.rst
  docs/running.rst
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: enhancement, prio: normal

#523 [test] Fix NetCDF test on Kesch
  cscs-checks/libraries/io/netcdf_compile_run.py
Labels: prio: important, regression test

#512 [ci] Add C2SM environments on Kesch
  config/cscs.py
Labels: ci, prio: important

#520 [doc] Add User Lab Day slides to documentation
  docs/index.rst
Labels: documentation, prio: normal

#529 [test] Remove read-only files attribute from the CP2K check
  cscs-checks/apps/cp2k/cp2k_check.py
Labels: enhancement, prio: normal, regression test

#533 [bugfix] Do not silently abort tasks in hold when all currently running tasks fail
  reframe/frontend/executors/policies.py
  unittests/resources/checks/frontend_checks.py
  unittests/test_policies.py
Labels: bugfix, prio: normal

#535 [bugfix] Fix retry report when test fails before the setup phase
  reframe/frontend/statistics.py
  unittests/test_policies.py
Labels: bugfix, prio: normal

#537 [test] Remove Monch from supported systems
  cscs-checks/apps/gromacs/gromacs_check.py
  cscs-checks/cuda/hpcg_check.py
  cscs-checks/libraries/math/dgemm.py
  cscs-checks/libraries/math/scalapack_compile_run.py
  cscs-checks/microbenchmarks/osu/flexible_a2a.py
  cscs-checks/microbenchmarks/osu/osu_tests.py
  cscs-checks/microbenchmarks/stream/stream.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/system/io/ior_check.py
Labels: prio: normal, regression test

#448 [bugfix] Fix redundant export statements
  reframe/core/environments.py
Labels: bugfix, prio: normal

#522 [feat] Full support for flexible task allocation
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  unittests/test_launchers.py
  unittests/test_schedulers.py
Labels: enhancement, prio: normal
