Repository reframe-hpc/reframe, pull requests merged in 2018-03, with the labels that each got.

#154 Fix failure of the asynchronous execution policy's unit tests
  unittests/test_policies.py
Labels: bugfix, prio: important

#143 Make '--exclude' work with flexible allocation
  reframe/core/schedulers/slurm.py
  unittests/test_schedulers.py
Labels: backend, enhancement, prio: important

#155 Add 'switches' for g2g and alltoall tests
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: enhancement, prio: important, regression test

#152 Fix math domain error in decaying poll rate
  reframe/frontend/executors/policies.py
Labels: bugfix, frontend, prio: important

#133 Module mapping file and corresponding command line option
  docs/running.rst
  reframe/core/modules.py
  reframe/frontend/cli.py
  unittests/test_modules.py
Labels: backend, enhancement, frontend, prio: normal

#168 Update documentation on the 'check_info' logging attribute
  docs/running.rst
  reframe/core/pipeline.py
Labels: bugfix, documentation, enhancement, prio: important

#172 Fix crash when init_modules_system throws
  reframe/core/modules.py
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: bugfix, frontend, prio: normal

#175 Version bump
  reframe/__init__.py
Labels: frontend, prio: normal

#173 Revert to normal leone checkout
  Jenkinsfile
Labels: ci, prio: important

#174 Numerical sanity check in quantum espresso test
  cscs-checks/apps/espresso/espresso_check.py
Labels: enhancement, prio: normal, regression test

#169 Allow upper thresholds >= 1.0 in 'assert_reference'
  docs/tutorial.rst
  reframe/utility/sanity.py
  unittests/test_sanity_functions.py
Labels: backend, enhancement, prio: important

#177 Adapt the G2G and AlltoAll tests
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: prio: important, regression test

#187 Make settings.py a regular file
  Jenkinsfile
  ci-scripts/ci-runner.bash
  config/generic.py
  reframe/settings.py
Labels: bugfix, documentation, prio: important

#188 Requirements and copyright dates update of documentation
  docs/conf.py
  docs/requirements.txt
Labels: documentation, enhancement, prio: normal

#192 Fix 'git_repo_exists' bug causing a deadlock
  reframe/utility/os.py
Labels: backend, bugfix, prio: normal

#195 ReFrame upcoming version
  reframe/__init__.py
Labels: enhancement, frontend, prio: normal

#198 Adapt cp2k production
  cscs-checks/apps/cp2k/cp2k_check.py
Labels: enhancement, prio: important

#199 Adapt Gromacs production
  cscs-checks/apps/gromacs/gromacs_check.py
Labels: enhancement, prio: important, regression test

#196 Add check for TensorFlow
  cscs-checks/apps/tensorflow/tensorflow_check.py
Labels: prio: normal, regression test

#207 Terminate pending task upon abort in serial policy
  reframe/frontend/executors/policies.py
  reframe/frontend/statistics.py
  unittests/test_policies.py
Labels: bugfix, frontend, prio: normal

#205 Adapt production tests
  cscs-checks/apps/amber/amber_check.py
  cscs-checks/apps/cp2k/cp2k_check.py
  cscs-checks/apps/espresso/espresso_check.py
  cscs-checks/apps/gromacs/gromacs_check.py
  cscs-checks/apps/lammps/lammps_check.py
  cscs-checks/apps/namd/namd_check.py
  cscs-checks/libraries/magma/magma_checks.py
  cscs-checks/microbenchmarks/stream/stream.py
Labels: enhancement, prio: important, regression test

#200 Add numerical sanity check to cp2k test
  cscs-checks/apps/cp2k/cp2k_check.py
Labels: enhancement, prio: normal, regression test

#202 Add numerical sanity check to lammps test
  cscs-checks/apps/lammps/lammps_check.py
Labels: enhancement, prio: normal, regression test

#214 Expand environment variables in the -c option
  reframe/frontend/cli.py
Labels: enhancement, frontend, prio: important

#209 Correct use of scoped dict key updates in the multi-GPU CUDA test
  cscs-checks/cuda/multi_gpu.py
Labels: enhancement, prio: normal, regression test

#210 Enforce unique test names
  docs/running.rst
  reframe/core/exceptions.py
  reframe/frontend/cli.py
  reframe/frontend/loader.py
  unittests/resources/badchecks/invalid_check.py
  unittests/resources/hellocheck_copy.py
  unittests/test_cli.py
  unittests/test_loader.py
  unittests/test_policies.py
Labels: enhancement, frontend, prio: normal

#217 Adapt the async poll rate
  reframe/frontend/executors/policies.py
Labels: backend, enhancement, prio: important

#225 Fine tuning of the config file option impl
  reframe/frontend/cli.py
  reframe/frontend/config.py
  reframe/frontend/loader.py
  reframe/settings.py
  reframe/utility/__init__.py
  unittests/fixtures.py
  unittests/resources/settings_unittests.tmpl
  unittests/test_cli.py
  unittests/test_loader.py
  unittests/test_schedulers.py
  unittests/test_utility.py
Labels: enhancement, frontend, prio: normal

#227 Better implementation of the sample program
  cscs-checks/microbenchmarks/mpi/src/mpi_helloworld.c
Labels: enhancement, regression test

#220 MPI flexible Hello World test
  cscs-checks/microbenchmarks/mpi/mpi_helloworld.py
  cscs-checks/microbenchmarks/mpi/src/mpi_helloworld.c
Labels: prio: normal, regression test

#230 Fix cuda example inconsistencies in tutorial
  docs/advanced.rst
  docs/tutorial.rst
Labels: bugfix, documentation, enhancement, prio: important
