Repository reframe-hpc/reframe, pull requests merged in 2018-11, with the labels that each got.

#548 [test] Update GROMACS performance numbers
  cscs-checks/apps/gromacs/gromacs_check.py
Labels: prio: important, regression test

#552 [test] Adapt usertool tests to new syntax
  cscs-checks/system/slurm/cscs_usertools.py
Labels: prio: important, regression test

#551 [test] Disable Trilinos tests which fail due to the corresponding module
  cscs-checks/libraries/math/trilinos_compile_run.py
Labels: prio: important, regression test

#558 [bugfix] Directly assign to `num_tasks` if `--flex-alloc-tasks` has an integer value
  reframe/core/schedulers/__init__.py
Labels: bugfix, prio: important

#564 [test] Adapt the GPU burn test for multi-gpu nodes
  cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
  cscs-checks/microbenchmarks/gpu_burn/src/gpu_burn.cu
Labels: prio: important, regression test

#559 [test] Update CP2K test
  cscs-checks/apps/cp2k/cp2k_check.py
Labels: enhancement, prio: important

#571 [test] Update MAGMA tests
  cscs-checks/libraries/magma/magma_checks.py
Labels: prio: important, regression test

#572 [test] Add test checking if CRAY_CPU_TARGET is set
  cscs-checks/prgenv/cpu_target_check.py
Labels: prio: normal, regression test

#579 [test] Update GROMACS test for Dom
  cscs-checks/apps/gromacs/gromacs_check.py
Labels: prio: important, regression test

#581 [test] Run libsci_acc and libsci_resolve tests on compute nodes as well
  cscs-checks/compile/libsci_acc_symlink.py
  cscs-checks/compile/libsci_resolve.py
Labels: prio: normal, regression test

#574 [test] Update NAMD test
  cscs-checks/apps/namd/namd_check.py
Labels: prio: important, regression test

#582 [doc] Document the `--flex-alloc-tasks` feature
  docs/advanced.rst
  docs/running.rst
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  tutorial/advanced/advanced_example9.py
Labels: documentation, prio: important

#580 [feat] Update retries stage/output directory naming convention
  reframe/core/pipeline.py
  reframe/core/runtime.py
Labels: enhancement, prio: important

#584 [feat] Add a new `count_uniq()` sanity function
  reframe/utility/sanity.py
  unittests/test_sanity_functions.py
Labels: enhancement, prio: normal

#596 [test] Adapt CP2K test
  cscs-checks/apps/cp2k/cp2k_check.py
Labels: prio: important, regression test

#576 [feat] Add support for units in performance references
  config/cscs.py
  docs/running.rst
  docs/tutorial.rst
  reframe/core/logging.py
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  reframe/settings.py
  tutorial/example7.py
  unittests/resources/checks/frontend_checks.py
  unittests/resources/settings.py
Labels: enhancement, prio: normal

#588 [ci] Replace python 3.7-dev with 3.7 in `.travis.yml`
  .travis.yml
Labels: ci, prio: normal

#513 [test] Adapt MCH regression tests to C2SM-RCM environments
  config/cscs.py
  cscs-checks/mch/automatic_arrays.py
  cscs-checks/mch/g2g_meteoswiss_check.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/mch/gpu_direct_cuda.py
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/mch/src/openacc_cuda_mpi_cppstd.F90
Labels: prio: normal, regression test

#591 [test] Set `exclusive_access` for Kesch tests
  cscs-checks/cuda/cuda_checks.py
  cscs-checks/cuda/multi_gpu.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/scalapack_compile_run.py
  cscs-checks/mch/automatic_arrays.py
  cscs-checks/mch/check_ruby.py
  cscs-checks/mch/collectives_halo.py
  cscs-checks/mch/cuda_stress_test.py
  cscs-checks/mch/g2g_meteoswiss_check.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/mch/gpu_direct_cuda.py
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
  cscs-checks/microbenchmarks/mpi/mpi_helloworld.py
  cscs-checks/microbenchmarks/osu/flexible_a2a.py
  cscs-checks/microbenchmarks/osu/osu_tests.py
  cscs-checks/microbenchmarks/stream/stream.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/system/slurm/slurm.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
  cscs-checks/tools/profiling_and_debugging/ddt.py
  cscs-checks/tools/profiling_and_debugging/nvprof.py
Labels: prio: important, regression test

#585 [test] Remove `ifdef USE_MPI` from the MCH OpenACC/CUDA/MPI/C++ test
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/mch/src/openacc_cuda_mpi_cppstd.F90
Labels: enhancement, prio: normal, regression test

#600 [ci] Use integer comparison for ReFrame versions in deployment script
  ci-scripts/deploy.sh
Labels: bugfix, ci, prio: normal

#606 [doc] Move SC18 presentation & demo to docs
  README.md
  docs/index.rst
Labels: documentation, prio: normal
