Repository reframe-hpc/reframe, pull requests merged in 2018-08, with the labels that each got.

#415 [test] Adapt haswell_fma to buildsystems style
  cscs-checks/compile/haswell_fma_check.py
Labels: enhancement, prio: normal, regression test

#417 [test] Adapt the scalapack tests to use build systems
  cscs-checks/libraries/math/scalapack_compile_run.py
Labels: enhancement, prio: normal, regression test

#418 [test] Adapt dgemm test to use build systems
  cscs-checks/libraries/math/dgemm.py
Labels: enhancement, prio: normal, regression test

#410 [bugfix] Filter out empty strings before writing preamble
  reframe/core/schedulers/slurm.py
  reframe/core/shell.py
  unittests/test_schedulers.py
Labels: backend, bugfix, prio: normal

#421 [test] Adapt cuda checks to build systems
  cscs-checks/cuda/cuda_checks.py
Labels: enhancement, prio: normal, regression test

#426 [test] Adapt scorep test to PE 18.07
  cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
Labels: enhancement, prio: important, regression test

#424 [test] Adapt libsci_resolve test to PE 18.07
  cscs-checks/compile/libsci_resolve.py
Labels: enhancement, prio: important, regression test

#422 [test] Adapt hdf5 tests to build systems
  cscs-checks/libraries/io/hdf5_compile_run.py
Labels: enhancement, prio: normal, regression test

#427 [test] Adapt notools check to build systems
  cscs-checks/tools/profiling_and_debugging/notool.py
Labels: enhancement, prio: normal, regression test

#428 [test] Adapt cuda_gdb to build systems
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
Labels: enhancement, prio: normal, regression test

#425 [test] Adapt ddt regression test to PE 18.07
  cscs-checks/tools/profiling_and_debugging/ddt.py
  cscs-checks/tools/profiling_and_debugging/src/C++/Makefile_ddt
  cscs-checks/tools/profiling_and_debugging/src/C/Makefile_ddt
  cscs-checks/tools/profiling_and_debugging/src/Cuda/Makefile
  cscs-checks/tools/profiling_and_debugging/src/Cuda/Makefile_ddt
  cscs-checks/tools/profiling_and_debugging/src/F90/Makefile_ddt
Labels: enhancement, prio: important, regression test

#432 [ci] New programming environments for Kesch
  config/cscs.py
Labels: ci, enhancement, prio: normal

#431 [test] Adapt cdo test to PE 18.07
  cscs-checks/tools/io/cdo.py
Labels: prio: normal, regression test
