Repository reframe-hpc/reframe, pull requests merged in 2019-08, with the labels that each got.

#887 [feat] Enable modifications to ReFrame's environment per system basis
  docs/configure.rst
  reframe/core/config.py
  reframe/core/systems.py
  reframe/frontend/cli.py
  unittests/resources/settings.py
  unittests/test_config.py
Labels: enhancement, prio: normal

#891 [test] Update Intel VTune test
  cscs-checks/tools/profiling_and_debugging/intel_vtune.py
Labels: prio: normal, regression test

#894 [test] Update IPM tests for PE19.06
  cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
Labels: prio: normal, regression test

#896 [test] Update Tensorflow checks for PE19.06
  cscs-checks/apps/tensorflow/tensorflow_check.py
Labels: prio: normal, regression test

#897 Fix openacc_cuda_mpi_cppstd.F90
  cscs-checks/mch/src/compute_cuda.cu
  cscs-checks/mch/src/openacc_cuda_mpi_cppstd.F90
Labels: bug

#904 [test] Update tensorflow/horovod tests for latest modules
  cscs-checks/apps/tensorflow/tensorflow_check.py
  cscs-checks/apps/tensorflow/tf_horovod_check.py
Labels: prio: normal, regression test

#906 [feat] Print debug info when preload environment fails to load
  reframe/frontend/cli.py
Labels: enhancement, prio: normal

#907 [deploy] Fix project description in setup of PyPI package
  setup.py
Labels: enhancement, prio: normal

#900 [test] Add nsimd simd test
  cscs-checks/microbenchmarks/simd/nsimd.py
Labels: prio: normal, regression test

#899 [test] Add libVC simd test
  cscs-checks/microbenchmarks/simd/vc.py
Labels: prio: normal, regression test

#911 [bugfix] Use login shell when building executables
  reframe/core/pipeline.py
Labels: bugfix, prio: normal

#912 [ci] Run benchmark tests in CI with predefined number of tasks
  ci-scripts/ci-runner.bash
Labels: ci, prio: normal

#914 [ci] Fix tags of modified regression tests to run in ci
  ci-scripts/ci-runner.bash
Labels: ci, prio: normal

#910 [test] Increase iterations for async kernel latency test
  cscs-checks/microbenchmarks/kernel_latency/kernel_latency.py
  cscs-checks/microbenchmarks/kernel_latency/src/kernel_latency.cu
Labels: prio: normal, regression test
