Repository reframe-hpc/reframe, pull requests merged in 2019-10, with the labels that each got.

#954 [refactor] Use three single quotes for docstrings
  cscs-checks/cuda/multi_gpu.py
  cscs-checks/microbenchmarks/simd/nsimd.py
  cscs-checks/microbenchmarks/simd/vc.py
  cscs-checks/microbenchmarks/stream/stream.py
  cscs-checks/prgenv/mpi.py
  cscs-checks/tools/profiling_and_debugging/berkeley-ert-nvprof.py
  cscs-checks/tools/profiling_and_debugging/berkeley-ert.py
  reframe/core/buildsystems.py
  reframe/core/config.py
  reframe/core/containers.py
  reframe/core/debug.py
  reframe/core/decorators.py
  reframe/core/deferrable.py
  reframe/core/environments.py
  reframe/core/exceptions.py
  reframe/core/fields.py
  reframe/core/launchers/__init__.py
  reframe/core/launchers/registry.py
  reframe/core/logging.py
  reframe/core/modules.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/registry.py
  reframe/core/schedulers/slurm.py
  reframe/core/systems.py
  reframe/frontend/argparse.py
  reframe/frontend/dependency.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  reframe/frontend/loader.py
  reframe/frontend/printer.py
  reframe/frontend/statistics.py
  reframe/utility/__init__.py
  reframe/utility/color.py
  reframe/utility/os_ext.py
  reframe/utility/sanity.py
  reframe/utility/typecheck.py
  reframe/utility/versioning.py
  unittests/fixtures.py
  unittests/resources/checks/frontend_checks.py
  unittests/resources/checks_unlisted/good.py
  unittests/test_deferrable.py
  unittests/test_fields.py
  unittests/test_launchers.py
  unittests/test_modules.py
  unittests/test_policies.py
  unittests/test_schedulers.py
  unittests/test_utility.py
Labels: code quality, enhancement, prio: normal

#951 [feat] Add syntax for running functions after dependency resolution
  reframe/core/decorators.py
  reframe/core/meta.py
  reframe/core/pipeline.py
  unittests/test_pipeline.py
  unittests/test_policies.py
Labels: enhancement, prio: normal

#956 [test] Remove tags from nsimd checks
  cscs-checks/microbenchmarks/simd/nsimd.py
  cscs-checks/microbenchmarks/simd/vc.py
Labels: prio: normal, regression test

#952 [feat] Add SSH job launcher
  docs/configure.rst
  reframe/core/launchers/registry.py
  reframe/core/launchers/ssh.py
  unittests/test_launchers.py
Labels: enhancement, prio: normal

#957 [test] Update IPM check with new Cray path to PAPI (`PAT_BUILD_PAPI_LIBDIR`)
  cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
Labels: bugfix, prio: normal

#961 [feat] Lazy evaluation of job-related attributes and environments
  reframe/core/environments.py
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  reframe/utility/__init__.py
  unittests/test_cli.py
  unittests/test_environments.py
  unittests/test_modules.py
  unittests/test_pipeline.py
  unittests/test_schedulers.py
  unittests/test_utility.py
Labels: enhancement, prio: normal

#962 [test] Update Paraview test
  cscs-checks/apps/paraview/paraview_check.py
  cscs-checks/apps/paraview/src/coloredSphere.py
Labels: prio: important, regression test

#974 [test] Backport Paraview check to 2.17
  ci-scripts/ci-runner.bash
  cscs-checks/apps/paraview/paraview_check.py
  cscs-checks/apps/paraview/src/coloredSphere.py
Labels: prio: important, regression test

#853 [feat] Enable running containers inside the test pipeline
  config/cscs.py
  reframe/core/config.py
  reframe/core/containers.py
  reframe/core/pipeline.py
  reframe/core/systems.py
  unittests/test_containers.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#966 [test] Port GPUDirect check to Tiger
  cscs-checks/mch/gpu_direct_cuda.py
Labels: prio: normal, regression test

#965 [test] Update NVML with src from cudatoolkit
  cscs-checks/cuda/nvml_check.py
  cscs-checks/cuda/src/nvml_example.patch
Labels: code quality, prio: normal, regression test

#969 [test] Add specific tag to checks that test Cray PE
  cscs-checks/analytics/spark/spark_check.py
  cscs-checks/compile/haswell_fma_check.py
  cscs-checks/compile/libsci_acc_symlink.py
  cscs-checks/compile/libsci_resolve.py
  cscs-checks/cuda/cuda_checks.py
  cscs-checks/cuda/cuda_memtest_check.py
  cscs-checks/cuda/multi_gpu.py
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/trilinos_compile_run.py
  cscs-checks/libraries/petsc/petsc_helloworld.py
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/collectives_halo.py
  cscs-checks/mch/cuda_stress_test.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/mch/gpu_direct_cuda.py
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
  cscs-checks/microbenchmarks/dgemm/dgemm.py
  cscs-checks/microbenchmarks/fft/fftw_benchmark.py
  cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
  cscs-checks/microbenchmarks/kernel_latency/kernel_latency.py
  cscs-checks/microbenchmarks/latency/latency.py
  cscs-checks/microbenchmarks/osu/osu_tests.py
  cscs-checks/microbenchmarks/shmem/shmem.py
  cscs-checks/microbenchmarks/stream/stream.py
  cscs-checks/prgenv/affinity_check.py
  cscs-checks/prgenv/cpu_target_check.py
  cscs-checks/prgenv/environ_check.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/prgenv/mpi.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/prgenv/opencl_check.py
  cscs-checks/prgenv/ssh_environ_check.py
  cscs-checks/prgenv/ulimit_check.py
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
  cscs-checks/tools/profiling_and_debugging/ddt.py
  cscs-checks/tools/profiling_and_debugging/gdb4hpc.py
  cscs-checks/tools/profiling_and_debugging/nvprof.py
  cscs-checks/tools/profiling_and_debugging/perftools.py
Labels: prio: normal, regression test

#964 [test] Tag checks that use external resources
  cscs-checks/apps/amber/amber_check.py
  cscs-checks/apps/espresso/espresso_check.py
  cscs-checks/apps/gromacs/gromacs_check.py
  cscs-checks/apps/icon/rrtmgp_check.py
  cscs-checks/apps/lammps/lammps_check.py
  cscs-checks/apps/namd/namd_check.py
  cscs-checks/apps/openfoam/check_openfoam.py
  cscs-checks/apps/openfoam/check_openfoam_extend.py
  cscs-checks/cuda/cuda_checks.py
  cscs-checks/cuda/multi_gpu.py
  cscs-checks/cuda/nvml_check.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/scalapack_compile_run.py
  cscs-checks/mch/fieldextra_check.py
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
  cscs-checks/microbenchmarks/spec-accel/spec.py
  cscs-checks/system/io/ior_check.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
  cscs-checks/tools/profiling_and_debugging/berkeley-ert-nvprof.py
  cscs-checks/tools/profiling_and_debugging/berkeley-ert.py
  cscs-checks/tools/profiling_and_debugging/intel_advisor_roofline.py
  cscs-checks/tools/profiling_and_debugging/intel_sde_berkeley_stream.py
  cscs-checks/tools/profiling_and_debugging/intel_sde_roofline.py
  cscs-checks/tools/profiling_and_debugging/intel_vtune_roofline.py
Labels: prio: normal, regression test

#987 [test] Remove workaround for NetCDF C++ test with PGI
  cscs-checks/libraries/io/netcdf_compile_run.py
Labels: bugfix, prio: important, regression test

#967 [test] Port NETCDF check to Tiger
  cscs-checks/libraries/io/netcdf_compile_run.py
Labels: prio: normal, regression test

#968 [test] Port automatic arrays check to Tiger
  cscs-checks/mch/automatic_arrays_acc.py
Labels: prio: normal, regression test

#970 [test] Port collectives halo exchange check to Tiger
  cscs-checks/mch/collectives_halo.py
Labels: prio: normal, regression test

#979 [test] Port GPUBURN check to Tiger
  cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
Labels: prio: normal, regression test

#980 [test] Port KERNEL_LATENCY check to Tiger
  cscs-checks/microbenchmarks/kernel_latency/kernel_latency.py
Labels: prio: normal, regression test

#982 [test] Port FFTW check to Tiger
  cscs-checks/microbenchmarks/fft/fftw_benchmark.py
Labels: prio: normal, regression test

#983 [test] Port SHMEM to Tiger
  cscs-checks/microbenchmarks/shmem/shmem.py
Labels: prio: normal, regression test

#984 [test] Port CPUTARGET check to Tiger
  cscs-checks/prgenv/cpu_target_check.py
  cscs-checks/prgenv/ssh_environ_check.py
Labels: prio: normal, regression test

#973 [test] Port OPENACCCUDACPP to Tiger
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
Labels: prio: normal, regression test

#978 [test] Port DGEMM check to Tiger
  cscs-checks/microbenchmarks/dgemm/dgemm.py
Labels: prio: normal, regression test

#958 [test] Remove cce compiler from SCORE-P check
  cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
Labels: bugfix, prio: normal

#989 [doc] Update documentation links in README
  README.md
Labels: documentation, prio: normal

#977 [test] Add mem-per-cpu resources to ALLOC_SPEED check for Tiger
  cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
Labels: prio: normal, regression test

#960 [ci] Add config file for additional system
  config/tiger.py
Labels: ci, prio: normal

#981 [test] Port OSU check to Tiger
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: code quality, prio: normal, regression test

#971 [test] Port GPUDIRECTACC check to Tiger
  cscs-checks/mch/gpu_direct_acc.py
Labels: prio: normal, regression test

#990 [test] Remove unnecessary scheduler options from the DGEMM benchmark
  cscs-checks/microbenchmarks/dgemm/dgemm.py
Labels: bugfix, prio: important, regression test

#998 [bugfix] Do not use login shell when submitting jobs
  reframe/core/pipeline.py
Labels: bugfix, prio: normal

#994 [bugfix] Support inheritance in pipeline hooks
  docs/tutorial.rst
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: bugfix, prio: important

#985 [doc] Document the container platforms feature
  docs/advanced.rst
  docs/configure.rst
  docs/reference.rst
  reframe/core/buildsystems.py
  reframe/core/containers.py
  reframe/core/pipeline.py
  tutorial/advanced/advanced_example10.py
  tutorial/config/settings.py
Labels: documentation, prio: important

#1000 [test] Port GpuBandwidthCheck to Tiger
  cscs-checks/cuda/multi_gpu.py
Labels: prio: normal, regression test

#1002 [refactor] Make `Sarus` container platform backend a base class
  reframe/core/containers.py
Labels: code quality, prio: important

#976 [feat] Write the number of tasks in performance report
  config/cscs-ci.py
  config/cscs-pbs.py
  config/cscs.py
  docs/running.rst
  reframe/core/logging.py
  reframe/frontend/statistics.py
Labels: enhancement, prio: normal

#999 [test] Add PrgEnv-pgi to SPEC-ACCEL test
  cscs-checks/microbenchmarks/spec-accel/spec.py
  cscs-checks/microbenchmarks/spec-accel/src/cscs-pgi
Labels: prio: normal, regression test

#1004 [test] Update Intel_VTuneAmplifier
  cscs-checks/tools/profiling_and_debugging/intel_vtune.py
Labels: prio: normal, regression test

#1003 [test] Minor fixes for CLE7
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
  cscs-checks/tools/profiling_and_debugging/gdb4hpc.py
  cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
  cscs-checks/tools/profiling_and_debugging/mpip_mpi_omp.py
  cscs-checks/tools/profiling_and_debugging/src/Cuda/.in.cudagdb
Labels: prio: normal, regression test

#1006 [test] Fix Scorep_mpi_omp check
  cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
  cscs-checks/tools/profiling_and_debugging/src/F90/_main.F90
Labels: prio: normal, regression test

#1007 [test] Bump PE version in module names
  cscs-checks/apps/tensorflow/tensorflow_check.py
  cscs-checks/apps/tensorflow/tf_horovod_check.py
  cscs-checks/libraries/boost/boost_python_check.py
Labels: prio: important, regression test

#1010 [daint-gpu] Port Gromacs check to Tiger
  cscs-checks/apps/gromacs/gromacs_check.py
Labels: prio: normal, regression test

#1008 [doc] Fix syntax of container tutorial example
  docs/advanced.rst
  tutorial/advanced/advanced_example10.py
Labels: documentation, enhancement, prio: normal

#1009 [doc] Fix literal include lines in performance logging documentation
  docs/running.rst
Labels: bugfix, documentation, prio: normal

#1011 [test] Fix nvidia and libsci/mkl resolve tests
  cscs-checks/compile/libsci_resolve.py
Labels: prio: important, regression test

#1013 [test] Fix buffer decode error in MpiP check
  cscs-checks/tools/profiling_and_debugging/mpip_mpi_omp.py
Labels: prio: normal, regression test

#1016 [config] Update module for PrgEnv-cray_classic in config
  config/cscs.py
Labels: prio: important

#1020 [test] Update HPX "hello world" program name to v1.3.0
  cscs-checks/libraries/hpx/hpx_hello_world.py
Labels: bugfix, prio: important, regression test

#1015 [feat] Add support for test dependencies in serial execution policy
  reframe/core/exceptions.py
  reframe/frontend/cli.py
  reframe/frontend/dependency.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  unittests/resources/checks_unlisted/deps_complex.py
  unittests/resources/checks_unlisted/deps_simple.py
  unittests/test_policies.py
Labels: enhancement, prio: normal
