Repository reframe-hpc/reframe, pull requests merged in 2019-03, with the labels that each got.

#697 [feat] Remove support for passing options to the `RegressionTest.compile()` method
  reframe/core/pipeline.py
Labels: enhancement, prio: normal

#693 [bugfix] Fix bug ignoring a partition defined in 'access'
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  unittests/test_launchers.py
  unittests/test_schedulers.py
Labels: bugfix, prio: important

#675 [feat] Add logging handler for sending records to syslog
  docs/running.rst
  reframe/core/logging.py
  unittests/test_logging.py
Labels: enhancement, prio: normal

#685 [test] Add test for Fieldextra COSMO postprocessing
  cscs-checks/mch/fieldextra_check.py
Labels: prio: normal, regression test

#691 [test] Extend DGEMM test to build with OpenBLAS
  cscs-checks/microbenchmarks/dgemm/dgemm.py
Labels: prio: normal, regression test

#703 [bugfix] Correct the units of the kernel latency test
  cscs-checks/microbenchmarks/kernel_latency/kernel_latency.py
Labels: bugfix, prio: normal

#689 [test] Enlarge buffer sizes for H2D and D2D multi GPU tests
  cscs-checks/cuda/multi_gpu.py
Labels: enhancement, prio: normal, regression test

#705 [doc] Move documentation to readthedocs.org
  README.md
  ci-scripts/deploy.sh
  docs/Makefile
  docs/_templates/breadcrumbs.html
  docs/conf.py
  docs/requirements.txt
Labels: documentation, prio: normal

#666 [test] Add MPI halo cell exchange benchmark
  cscs-checks/microbenchmarks/mpi/halo_cell_exchange.py
  cscs-checks/microbenchmarks/mpi/src/halo_cell_exchange.c
  cscs-checks/microbenchmarks/mpi/src/input.txt
Labels: regression test

#684 [test] Add Fulen as a supported system in CSCS config
  config/cscs.py
Labels: prio: normal, regression test

#711 [bugfix] Fix deprecation warnings with Python 3.7
  reframe/core/decorators.py
  unittests/resources/checks/frontend_checks.py
Labels: bugfix, prio: normal

#709 [ci] Reenable Dom in the Jenkinsfile
  Jenkinsfile
Labels: ci, prio: important

#710 [test] Add Intel Inspector test
  cscs-checks/tools/profiling_and_debugging/intel_inspector.py
Labels: prio: normal, regression test

#690 [test] Add description to the collective halo tests
  cscs-checks/mch/collectives_halo.py
Labels: prio: normal, regression test

#704 [bugfix] Fix error message in case of performance errors
  reframe/core/exceptions.py
  reframe/core/pipeline.py
  reframe/utility/__init__.py
  unittests/resources/checks/frontend_checks.py
  unittests/test_exceptions.py
  unittests/test_pipeline.py
Labels: bugfix, prio: normal

#715 [bugfix] Fix unit test failure with EBUSY when running on NFS filesystem
  reframe/utility/os_ext.py
Labels: bugfix, prio: important

#713 [bugfix] Fix Slurm backend failures when trying node lists with inexistent nodes
  reframe/core/schedulers/slurm.py
Labels: bugfix, prio: normal

#664 [feat] Add support for selecting tests using regular expressions
  reframe/core/pipeline.py
  reframe/frontend/check_filters.py
  reframe/frontend/cli.py
  unittests/test_check_filters.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#716 [bugfix] Define the set of run environments correctly when `-p` option is used with regular expressions
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: bugfix, prio: important

#717 [doc] Add documentation for regular expression support in test selection options
  docs/running.rst
Labels: documentation, prio: important

#686 [test] Add OSU Allreduce test
  cscs-checks/microbenchmarks/osu/osu_tests.py
  cscs-checks/microbenchmarks/osu/src/Makefile_allreduce
  cscs-checks/microbenchmarks/osu/src/osu_allreduce.c
Labels: prio: normal, regression test

#723 [bugfix] Fix deprecation warning in check filter functions unit tests
  unittests/test_check_filters.py
Labels: bugfix, prio: normal

#719 [test] Add gperftools parallel test
  cscs-checks/tools/profiling_and_debugging/gperftools_mpi_omp.py
Labels: prio: normal, regression test

#718 [bugfix] Fix string error in header file of Cuda memtest
  cscs-checks/cuda/src/cuda_memtest-1.2.3.patch
Labels: bugfix, prio: normal

#720 [test] Add mpiP parallel test
  cscs-checks/tools/profiling_and_debugging/mpip_mpi_omp.py
  cscs-checks/tools/profiling_and_debugging/src/C++/Makefile
Labels: prio: normal, regression test

#721 [test] Add Intel Advisor Roofline test
  cscs-checks/tools/profiling_and_debugging/intel_advisor_roofline.py
Labels: prio: normal, regression test
