Repository reframe-hpc/reframe, pull requests merged in 2019-04, with the labels that each got.

#724 [refactor] Refactor frontend to execute directly test cases
  reframe/core/systems.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  reframe/frontend/statistics.py
  unittests/test_cli.py
  unittests/test_policies.py
Labels: enhancement, prio: normal

#726 [bugfix] Remove unnecessary module from the "Hello, World" tests
  cscs-checks/prgenv/helloworld.py
Labels: bugfix, prio: normal, regression test

#729 [bugfix] Fix crash in flexible task allocation due to refactoring of `SystemPartition`
  reframe/utility/__init__.py
  unittests/test_utility.py
Labels: bugfix, prio: important

#735 [bugfix] Fix typo in Likwid bandwidth benchmark
  cscs-checks/microbenchmarks/likwid/likwid.py
Labels: bugfix, regression test

#739 [test] Sort cores list in affinity test before comparing
  cscs-checks/prgenv/affinity_check.py
Labels: enhancement, regression test

#738 [test] Enable small scale application tests also on Daint
  cscs-checks/apps/amber/amber_check.py
  cscs-checks/apps/cp2k/cp2k_check.py
  cscs-checks/apps/cpmd/cpmd_check.py
  cscs-checks/apps/espresso/espresso_check.py
  cscs-checks/apps/gromacs/gromacs_check.py
  cscs-checks/apps/lammps/lammps_check.py
  cscs-checks/apps/namd/namd_check.py
  cscs-checks/apps/tensorflow/tf_horovod_check.py
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: prio: important, regression test

#742 [doc] Fix reference to `exclusive_access` in tutorial
  docs/tutorial.rst
Labels: bugfix, documentation, prio: normal

#740 [bugfix] Fix duplicate module commands emitted while executing test cases
  reframe/frontend/executors/__init__.py
  reframe/utility/sandbox.py
  unittests/test_fields.py
Labels: bugfix, prio: important

#603 [test] Add test for gdb4hpc
  cscs-checks/tools/profiling_and_debugging/gdb4hpc.py
  cscs-checks/tools/profiling_and_debugging/src/F90/gdb4hpc.in
  cscs-checks/tools/profiling_and_debugging/src/F90/gdb4hpc.slm
Labels: prio: normal, regression test

#743 [ci] Prepare ReFrame for deployment to PyPI
  README.md
  ci-scripts/deploy.sh
  setup.py
Labels: ci, prio: normal

#745 [bugfix] Fix failure in Intel Advisor Roofline check
  cscs-checks/tools/profiling_and_debugging/intel_advisor_roofline.py
Labels: prio: normal, regression test

#749 [ci] Disable running modified tests on Daint
  ci-scripts/ci-runner.bash
  config/cscs.py
Labels: ci, prio: important

#750 [test] Rename for loop variable to fix warnings in kernel latency test
  cscs-checks/microbenchmarks/kernel_latency/src/kernel_latency.cu
Labels: prio: normal, regression test

#733 [feat] Add option to print performance report
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  reframe/frontend/statistics.py
Labels: enhancement, prio: normal

#731 [test] Update perftools check for CLE7
  cscs-checks/tools/profiling_and_debugging/perftools.py
Labels: prio: normal, regression test

#752 [ci] Add PyPI badge to README
  README.md
  setup.py
Labels: ci, prio: normal

#748 [test] Update boost python test to use the latest module
  cscs-checks/libraries/boost/boost_python_check.py
Labels: prio: normal, regression test

#751 [test] Fix ldflags for `nvprof`, `cuda_gdb` tests
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
  cscs-checks/tools/profiling_and_debugging/nvprof.py
  cscs-checks/tools/profiling_and_debugging/src/Cuda/Makefile_nvprof
Labels: prio: normal, regression test

#727 [test] Update Jacobi test for CLE7
  cscs-checks/tools/profiling_and_debugging/notool.py
Labels: prio: normal, regression test

#754 [test] Update magma tests
  cscs-checks/libraries/magma/magma-2.2/Makefile_cblas_z
  cscs-checks/libraries/magma/magma-2.2/Makefile_zgemm
  cscs-checks/libraries/magma/magma-2.2/Makefile_zsymmetrize
  cscs-checks/libraries/magma/magma-2.2/Makefile_ztranspose
  cscs-checks/libraries/magma/magma-2.2/Makefile_zunmbr
  cscs-checks/libraries/magma/magma-2.2/flops.h
  cscs-checks/libraries/magma/magma-2.2/license.txt
  cscs-checks/libraries/magma/magma-2.2/magma_util.cpp
  cscs-checks/libraries/magma/magma-2.2/patch.txt
  cscs-checks/libraries/magma/magma-2.2/testing_c.h
  cscs-checks/libraries/magma/magma-2.2/testing_cblas_z.cpp
  cscs-checks/libraries/magma/magma-2.2/testing_d.h
  cscs-checks/libraries/magma/magma-2.2/testing_s.h
  cscs-checks/libraries/magma/magma-2.2/testing_z.h
  cscs-checks/libraries/magma/magma-2.2/testing_zgemm.cpp
  cscs-checks/libraries/magma/magma-2.2/testing_zsymmetrize.cpp
  cscs-checks/libraries/magma/magma-2.2/testing_ztranspose.cpp
  cscs-checks/libraries/magma/magma-2.2/testing_zunmbr.cpp
  cscs-checks/libraries/magma/magma-2.2/testings.h
  cscs-checks/libraries/magma/magma_checks.py
  cscs-checks/libraries/magma/src/Makefile_cblas_z
  cscs-checks/libraries/magma/src/Makefile_zgemm
  cscs-checks/libraries/magma/src/Makefile_zsymmetrize
  cscs-checks/libraries/magma/src/Makefile_ztranspose
  cscs-checks/libraries/magma/src/Makefile_zunmbr
  cscs-checks/libraries/magma/src/flops.h
  cscs-checks/libraries/magma/src/license.txt
  cscs-checks/libraries/magma/src/magma_lapack.hpp
  cscs-checks/libraries/magma/src/magma_matrix.hpp
  cscs-checks/libraries/magma/src/magma_util.cpp
  cscs-checks/libraries/magma/src/patch.txt
  cscs-checks/libraries/magma/src/testing_c.h
  cscs-checks/libraries/magma/src/testing_cblas_z.cpp
  cscs-checks/libraries/magma/src/testing_d.h
  cscs-checks/libraries/magma/src/testing_s.h
  cscs-checks/libraries/magma/src/testing_z.h
  cscs-checks/libraries/magma/src/testing_zgemm.cpp
  cscs-checks/libraries/magma/src/testing_zsymmetrize.cpp
  cscs-checks/libraries/magma/src/testing_ztranspose.cpp
  cscs-checks/libraries/magma/src/testing_zunmbr.cpp
  cscs-checks/libraries/magma/src/testings.h
Labels: bugfix, prio: normal, regression test

#755 [ci] Update deployment script
  ci-scripts/deploy.sh
Labels: ci, enhancement

#758 [test] Adapt Paraview GPU check to CLE7
  cscs-checks/apps/paraview/paraview_check.py
Labels: enhancement, regression test

#757 [bugfix] Do not crash when invalid regular expressions are passed to the test selection options
  reframe/frontend/check_filters.py
  unittests/test_check_filters.py
Labels: bugfix, prio: important

#766 [test] Update IPM check for PE/19.03
  cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
Labels: prio: normal, regression test

#767 [test] Update Score-P check for PE/19.03
  cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
Labels: prio: normal, regression test

#762 [test] Add flexible HPCG GPU benchmark test
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
  cscs-checks/microbenchmarks/hpcg/hpcg_check.py
Labels: enhancement, regression test

#761 [doc] Document the `--performance-report` command line option
  docs/running.rst
Labels: documentation, prio: important
