Repository reframe-hpc/reframe, pull requests merged in 2019-01, with the labels that each got.

#635 [refactor] Sanitize the `Environment` class
  .pep8speaks.yml
  reframe/core/config.py
  reframe/core/environments.py
  reframe/core/pipeline.py
  reframe/utility/__init__.py
  unittests/test_environments.py
  unittests/test_utility.py
Labels: code quality, prio: normal

#639 [bugfix] Fix bug in variable names in Slurm backend
  reframe/core/schedulers/slurm.py
Labels: bugfix, prio: important

#638 [docs] Add Google Analytics track to documentation
  docs/conf.py
Labels: documentation, enhancement, prio: normal

#633 [feat] Add command line options for showing the system and environments configuration
  docs/configure.rst
  reframe/core/environments.py
  reframe/core/runtime.py
  reframe/core/systems.py
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: enhancement, prio: normal

#616 [test] Add HPX hello world test
  cscs-checks/libraries/hpx/hpx_hello_world.py
Labels: prio: low, regression test

#642 [doc] Update README with contact info
  README.md
Labels: documentation, prio: important

#604 [test] Add flexible HPCG test
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
  cscs-checks/microbenchmarks/hpcg/src/Make.CrayXC
Labels: prio: normal, regression test

#637 [test] Add test for distributed training with TensorFlow and Horovod
  cscs-checks/apps/tensorflow/tf_horovod_check.py
Labels: prio: normal, regression test

#629 [refactor] Refactor test selection phase
  reframe/frontend/check_filters.py
  reframe/frontend/cli.py
  unittests/test_check_filters.py
Labels: code quality, prio: normal

#648 [ci] Add option to disable CSCS CI tests
  Jenkinsfile
Labels: ci, prio: normal

#649 [ci] Make `.pep8speaks.yml` consistent with coding style
  .pep8speaks.yml
Labels: ci, prio: normal

#618 [test] Add tests for SPEC-ACCEL benchmarks
  cscs-checks/microbenchmarks/spec-accel/spec.py
  cscs-checks/microbenchmarks/spec-accel/src/cscs-cray
  cscs-checks/microbenchmarks/spec-accel/src/cscs-gnu
Labels: prio: normal, regression test

#646 [test] Add benchmark measuring CUDA kernel launch latency
  cscs-checks/microbenchmarks/kernel_latency/kernel_latency.py
  cscs-checks/microbenchmarks/kernel_latency/src/kernel_latency.cu
Labels: prio: normal, regression test

#620 [test] Add new `MPI_Init_thread()` check
  cscs-checks/prgenv/mpi.py
  cscs-checks/prgenv/src/mpi_init_thread.cpp
Labels: prio: normal, regression test

#654 [refactor] Refactor `PrettyPrinter` and enable colors in the general logger
  reframe/core/logging.py
  reframe/frontend/argparse.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/printer.py
  reframe/utility/__init__.py
  reframe/utility/color.py
  unittests/test_color.py
  unittests/test_logging.py
Labels: code quality, prio: normal

#623 [bugfix] Improve handling of bad tests to avoid frontend crashing
  reframe/core/decorators.py
  unittests/resources/checks_unlisted/bad_init_check.py
  unittests/test_loader.py
Labels: bugfix, prio: normal

#661 [doc] Add link for the automatic invites to Slack
  README.md
Labels: documentation, prio: normal

#652 [feat] Add support for setting a minimum number of required tasks in tests with flexible task allocation
  docs/advanced.rst
  docs/running.rst
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  unittests/test_schedulers.py
Labels: enhancement, prio: normal

#647 [test] Add Likwid benchmarks for cache, memory and cross-socket bandwidths
  cscs-checks/microbenchmarks/likwid/likwid.py
Labels: prio: normal, regression test

#665 [doc] Document verbosity option
  docs/running.rst
  reframe/frontend/cli.py
Labels: documentation, prio: important
