Repository reframe-hpc/reframe, pull requests merged in 2019-09, with the labels that each got.

#917 [test] Add performance report to Empirical Roofline Tool test
  cscs-checks/tools/profiling_and_debugging/berkeley-ert.py
Labels: prio: normal, regression test

#913 [test] Adapt MCH checks to CrayPE 17.06 on Kesch (RH7.5)
  config/cscs.py
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/collectives_halo.py
  cscs-checks/mch/cuda_stress_test.py
  cscs-checks/mch/g2g_meteoswiss_check.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/mch/gpu_direct_cuda.py
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/mch/src/openacc_cuda_mpi_cppstd.F90
Labels: enhancement, regression test

#925 [test] Fixing I/O checks on Kesch
  config/cscs.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
Labels: bugfix, regression test

#918 [feat] Print compiler commands and flags when showing the environment configuration
  reframe/core/environments.py
Labels: enhancement, prio: normal

#929 [test] Update GitHub repository in collectives MCH check
  cscs-checks/mch/collectives_halo.py
Labels: enhancement, prio: normal, regression test

#928 [test] Fixing OpenACCFortran checks on Kesch
  config/cscs.py
  cscs-checks/prgenv/openacc_checks.py
Labels: bugfix, regression test

#931 [bugfix] Back port Slurm fixes to ReFrame 2.17
  cscs-checks/system/slurm/slurm.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/slurm.py
  unittests/test_schedulers.py
Labels: bugfix, prio: important, regression test

#933 [bugfix] Back port Intel Inspector test
  cscs-checks/tools/profiling_and_debugging/intel_inspector.py
Labels: bugfix, prio: important, regression test

#920 [feat] Add new syntax for attaching arbitrary regression test methods to pipeline stages
  docs/reference.rst
  docs/tutorial.rst
  reframe/core/decorators.py
  reframe/core/meta.py
  reframe/core/pipeline.py
  tutorial/advanced/advanced_example8.py
  tutorial/example2.py
  tutorial/example3.py
  tutorial/example4.py
  tutorial/example8.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#874 [test] Add CPU memory latency test
  cscs-checks/microbenchmarks/latency/latency.py
  cscs-checks/microbenchmarks/latency/src/latency.cpp
Labels: prio: normal, regression test

#908 [test] Enable performance reporting in the flexible alltoall OSU benchmark
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: enhancement, prio: normal, regression test

#916 [test] Add performance report to the Intel Advisor test
  cscs-checks/tools/profiling_and_debugging/intel_advisor_roofline.py
Labels: prio: normal, regression test

#938 [test] Make the MpiP check generic
  cscs-checks/tools/profiling_and_debugging/mpip_mpi_omp.py
Labels: prio: normal, regression test

#939 [test] Update reference values of G2G [1] check
  cscs-checks/mch/g2g_meteoswiss_check.py
Labels: enhancement, regression test

#937 [test] Enable IOR test on Daint
  cscs-checks/system/io/ior_check.py
Labels: prio: normal, regression test

#940 [test] Back port Intel VTune and IOR tests to 2.17
  config/cscs.py
  cscs-checks/system/io/ior_check.py
  cscs-checks/tools/profiling_and_debugging/intel_vtune.py
Labels: bugfix, regression test

#934 [feat] Improve and simplify the topological sorting of the test cases
  reframe/frontend/dependency.py
Labels: enhancement, prio: normal

#945 [test] Adapt module versions to PE19.09
  cscs-checks/apps/tensorflow/tensorflow_check.py
  cscs-checks/apps/tensorflow/tf_horovod_check.py
  cscs-checks/libraries/boost/boost_python_check.py
  cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
Labels: prio: important, regression test

#943 [test] Fix cuda checks on Kesch
  cscs-checks/cuda/cuda_checks.py
  cscs-checks/microbenchmarks/osu/osu_tests.py
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
  cscs-checks/tools/profiling_and_debugging/ddt.py
  cscs-checks/tools/profiling_and_debugging/nvprof.py
Labels: bugfix, regression test

#948 [bugfix] Fix unit tests leaving stale files behind
  unittests/test_pipeline.py
Labels: bugfix, prio: normal

#946 [feat] Replace `reframe_module` configuration option with command line option
  config/cscs-ci.py
  config/cscs-pbs.py
  config/cscs.py
  reframe/frontend/cli.py
  reframe/settings.py
  tutorial/config/settings.py
  unittests/modules/testmod_bar
  unittests/modules/testmod_boo
  unittests/modules/testmod_foo
  unittests/resources/settings.py
  unittests/test_cli.py
Labels: enhancement, prio: normal

#921 [test] Add OpenStack SWIFT S3 tests
  cscs-checks/system/openstack/s3_check.py
  cscs-checks/system/openstack/src/s3_create_bucket.py
  cscs-checks/system/openstack/src/s3_create_small_object.py
  cscs-checks/system/openstack/src/s3_delete.py
  cscs-checks/system/openstack/src/s3_download_large_object.py
  cscs-checks/system/openstack/src/s3_test.sh
  cscs-checks/system/openstack/src/s3_upload_large_object.py
  cscs-checks/system/openstack/src/tools.py
Labels: prio: normal, regression test

#949 [feat] Enable easy testing of non-default Cray programming environments
  docs/running.rst
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/frontend/cli.py
Labels: enhancement, prio: normal

#950 [test] Update Gromacs reference value
  cscs-checks/apps/gromacs/gromacs_check.py
Labels: prio: important, regression test
