Repository reframe-hpc/reframe, pull requests merged in 2019-05, with the labels that each got.

#768 [test] Update Tensorflow check to r1.12.0
  cscs-checks/apps/tensorflow/tensorflow_check.py
Labels: prio: normal, regression test

#771 [test] Adapt TensorFlow+Horovod test to CrayGNU-19.03
  cscs-checks/apps/tensorflow/tf_horovod_check.py
Labels: prio: normal, regression test

#770 [test] Add CUDA shared memory bandwidth benchmark
  cscs-checks/microbenchmarks/shmem/shmem.py
  cscs-checks/microbenchmarks/shmem/src/shmem.cu
Labels: prio: normal, regression test

#772 [test] Fix ddt+cuda/10.0 check
  cscs-checks/tools/profiling_and_debugging/ddt.py
Labels: prio: normal, regression test

#774 [test] Add sde roofline check
  cscs-checks/tools/profiling_and_debugging/intel_sde_berkeley_stream.py
  cscs-checks/tools/profiling_and_debugging/intel_sde_roofline.py
Labels: prio: important, regression test

#773 [test] Add ert roofline check
  cscs-checks/tools/profiling_and_debugging/berkeley-ert.py
Labels: prio: important, regression test

#775 [test] Add ert roofline check (gpu)
  cscs-checks/tools/profiling_and_debugging/berkeley-ert-nvprof.py
Labels: prio: important, regression test

#778 [test] Add Roofline check of the GPP code using NVIDIA nvprof
  cscs-checks/tools/profiling_and_debugging/gpp_nvprof_roofline.py
Labels: prio: normal, regression test

#777 [ci] Add Ault TDS to the config file
  config/cscs.py
Labels: prio: normal, regression test

#782 [ci] Expand Ault configuration
  config/cscs.py
Labels: ci, prio: normal

#779 [feat] Do not use absolute paths in generated batch scripts
  docs/advanced.rst
  docs/tutorial.rst
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/pbs.py
  unittests/test_launchers.py
  unittests/test_policies.py
Labels: feature request, prio: normal

#785 [test] Hardcode version in Intel Vtune test to prevent failure when default changes
  cscs-checks/tools/profiling_and_debugging/intel_vtune.py
Labels: prio: normal, regression test

#790 [bugfix] Fix filename order in build error message
  reframe/core/exceptions.py
Labels: bugfix, prio: normal

#786 [feat] Print task allocation type (standard or flexible) for tests in detailed listing
  docs/running.rst
  reframe/frontend/cli.py
Labels: prio: normal

#793 [bugfix] Fix exception message formatting in reservation node extraction
  reframe/core/schedulers/slurm.py
Labels: bugfix, prio: normal

#769 [feat] Implement test dependency API
  reframe/core/exceptions.py
  reframe/core/pipeline.py
  reframe/frontend/dependency.py
  reframe/frontend/executors/__init__.py
  unittests/resources/checks_unlisted/dependencies/normal.py
  unittests/resources/settings.py
  unittests/test_config.py
  unittests/test_policies.py
Labels: enhancement, prio: normal

#796 [test] Make CUDA kernel latency tests generic
  cscs-checks/microbenchmarks/kernel_latency/kernel_latency.py
Labels: enhancement, regression test

#794 [bugfix] Add version checks for TMod and TMod4
  docs/configure.rst
  reframe/core/modules.py
Labels: bugfix, prio: normal

#798 [config] Fix configuration for Ault
  config/cscs.py
Labels: prio: normal

#800 [test] Make alloc_speed check generic
  cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
Labels: enhancement, regression test

#799 [test] Make the STREAM test generic
  cscs-checks/microbenchmarks/stream/stream.py
Labels: enhancement, regression test

#801 [test] Make OSU tests check generic
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: enhancement, regression test

#791 [feat] Print performance variable name in case of performance errors
  reframe/core/pipeline.py
  reframe/utility/sanity.py
Labels: prio: normal

#807 [ci] Require full tag names in genrelnotes.py script
  ci-scripts/genrelnotes.py
Labels: ci, prio: normal

#797 [feat] Validate test case graph
  reframe/frontend/dependency.py
  unittests/test_policies.py
Labels: enhancement, prio: normal

#776 [test] Add simple FFTW benchmark
  cscs-checks/microbenchmarks/fft/fftw_benchmark.py
  cscs-checks/microbenchmarks/fft/src/fftw_benchmark.c
Labels: prio: normal, regression test

#787 [feat] Add high-level API for container platforms
  reframe/core/containers.py
  reframe/core/exceptions.py
  unittests/test_containers.py
Labels: enhancement, prio: normal

#805 [refactor] Fix abstract class definitions
  reframe/core/buildsystems.py
  reframe/frontend/executors/__init__.py
  reframe/utility/versioning.py
  unittests/test_buildsystems.py
  unittests/test_modules.py
  unittests/test_schedulers.py
Labels: code quality, prio: normal

#783 [test] Revise MAGMA library benchmark
  cscs-checks/libraries/magma/magma_checks.py
  cscs-checks/libraries/magma/src/patch.txt
Labels: prio: normal, regression test

#808 [bugfix] Fix crash when using syslog logging handler with the `-v` option
  reframe/core/logging.py
Labels: bugfix, prio: normal
