Repository reframe-hpc/reframe, pull requests merged in 2019-06, with the labels that each got.

#814 [test] Add `dom:mc` as valid system to `IntelRooflineAdvisorTest`
  cscs-checks/tools/profiling_and_debugging/intel_advisor_roofline.py
Labels: prio: normal, regression test

#813 [test] Add Intel Vtune roofline check
  cscs-checks/tools/profiling_and_debugging/intel_vtune_roofline.py
Labels: prio: normal, regression test

#810 [feat] Limit concurrent build jobs to `1` by default in build systems
  docs/advanced.rst
  reframe/core/buildsystems.py
  unittests/test_buildsystems.py
Labels: prio: normal

#817 [test] Make `HaloCellExchangeTest` generic
  cscs-checks/microbenchmarks/mpi/halo_cell_exchange.py
Labels: prio: normal, regression test

#819 [test] Make the Jacobi check generic
  cscs-checks/tools/profiling_and_debugging/notool.py
Labels: enhancement, regression test

#812 [test] Add API calls in Intel Advisor Roofline check
  cscs-checks/tools/profiling_and_debugging/intel_advisor_roofline.py
Labels: prio: normal, regression test

#823 [misc] Add Licence and Slack badges to README.md
  README.md
Labels: enhancement, prio: normal

#822 [config] Add configuration for Tave
  config/cscs.py
Labels: enhancement, prio: normal

#818 [bugfix] Fix bug in performance report output
  reframe/core/pipeline.py
  unittests/test_cli.py
Labels: bugfix, prio: urgent

#828 [test] Make GPU burn test generic
  cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
Labels: prio: normal, regression test

#829 [test] Make GPU shared memory bandwidth test generic
  cscs-checks/microbenchmarks/shmem/shmem.py
Labels: prio: normal, regression test

#827 [test] Make DGEMM test generic
  cscs-checks/microbenchmarks/dgemm/dgemm.py
Labels: prio: normal, regression test

#830 [test] Make HPCG basic test generic
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
Labels: prio: normal, regression test

#824 [bugfix] Fix timing in the allocation speed test
  cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
  cscs-checks/microbenchmarks/alloc_speed/src/alloc_speed.cpp
Labels: bugfix, prio: normal, regression test

#826 [test] Make MCH halo cell exchange generic
  cscs-checks/mch/collectives_halo.py
Labels: bugfix, prio: normal, regression test

#815 [feat] Implement topological sort of the test cases
  reframe/frontend/dependency.py
  reframe/utility/__init__.py
  unittests/test_policies.py
  unittests/test_typecheck.py
  unittests/test_utility.py
Labels: prio: normal

#831 [test] Set `num_cpus_per_task` to the TensorFlow Horovod test
  cscs-checks/apps/tensorflow/tf_horovod_check.py
Labels: bugfix, regression test

#835 [bugfix] Fix ReFrame hanging when Slurm job gets OOM killed
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/slurm.py
  unittests/test_schedulers.py
Labels: bugfix, prio: important

#836 [test] Fix MemoryOverconsumptionCheck message check
  cscs-checks/system/slurm/slurm.py
Labels: prio: normal, regression test

#837 [test] Fix DefaultRequestGPUSetsGRES for updated slurm output
  cscs-checks/system/slurm/slurm.py
Labels: prio: normal, regression test

#760 [test] Add GridTools mini app benchmark
  cscs-checks/libraries/gridtools/gridtools_tests.py
Labels: prio: normal, regression test

#841 [ci] Reenable PGI on Dom
  config/cscs.py
Labels: ci, prio: important

#842 [test] Enable dynamic linking tests for Trilinos
  cscs-checks/libraries/math/trilinos_compile_run.py
Labels: prio: normal, regression test

#845 [bugfix] Fix how Slurm states are mapped internally by the Slurm backend
  reframe/core/schedulers/slurm.py
Labels: bugfix, prio: normal
