Repository reframe-hpc/reframe, pull requests merged in 2019-02, with the labels that each got.

#672 [bugfix] Fix bug in 'keep_files' unit tests
  unittests/test_pipeline.py
Labels: bugfix, prio: normal

#673 [feat] Add support for directories in `keep_files` attribute
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#662 [test] Extend DGEMM test for using MKL
  cscs-checks/microbenchmarks/dgemm/dgemm.py
  cscs-checks/microbenchmarks/dgemm/src/dgemm.c
Labels: enhancement, prio: normal

#660 [feat] Extend `Job` API for retrieving the list of nodes assigned to the regression test
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/slurm.py
  unittests/test_schedulers.py
Labels: enhancement, prio: normal

#678 [feat] Drop support for setting flags in environment
  docs/configure.rst
  reframe/core/buildsystems.py
  reframe/core/environments.py
  reframe/core/fields.py
  reframe/frontend/cli.py
  unittests/test_buildsystems.py
  unittests/test_environments.py
Labels: enhancement, prio: normal

#679 [test] Update maintenance tests
  cscs-checks/apps/cp2k/cp2k_check.py
  cscs-checks/apps/lammps/lammps_check.py
Labels: prio: normal, regression test

#631 [test] Add test for NERSC IPM
  cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
Labels: prio: low, regression test

#657 [test] Add CPU affinity test
  cscs-checks/prgenv/affinity_check.py
  cscs-checks/prgenv/src/alternate_socket_filling.txt
  cscs-checks/prgenv/src/consecutive_socket_filling.txt
  cscs-checks/prgenv/src/gpu_omp_bind_cores.txt
  cscs-checks/prgenv/src/gpu_omp_bind_threads.txt
  cscs-checks/prgenv/src/gpu_omp_bind_threads_nomultithread.txt
  cscs-checks/prgenv/src/mc_omp_bind_cores.txt
  cscs-checks/prgenv/src/mc_omp_bind_threads.txt
  cscs-checks/prgenv/src/mc_omp_bind_threads_nomultithread.txt
  cscs-checks/prgenv/src/single_task_per_socket_omp.txt
  cscs-checks/prgenv/src/single_task_per_socket_omp_multithread.txt
Labels: prio: normal, regression test

#670 [test] Add test for gperftools
  cscs-checks/tools/profiling_and_debugging/gperftools.py
Labels: prio: low, regression test

#683 [feat] Support command substitution in variable expansion
  reframe/core/config.py
  reframe/core/environments.py
  reframe/frontend/cli.py
  reframe/utility/os_ext.py
  unittests/test_utility.py
Labels: enhancement, prio: urgent

#681 [test] Fix tags of flexible tests + other improvements
  cscs-checks/cuda/cuda_memtest_check.py
  cscs-checks/cuda/src/cuda_memtest-1.2.3.patch
  cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
  cscs-checks/microbenchmarks/mpi/mpi_helloworld.py
  cscs-checks/microbenchmarks/osu/flexible_a2a.py
  cscs-checks/microbenchmarks/osu/osu_tests.py
  cscs-checks/prgenv/mpi.py
  cscs-checks/prgenv/src/mpi_helloworld.c
Labels: enhancement, prio: normal, regression test

#680 [bugfix] Fix crash in failure report when test is killed due to timeout
  reframe/utility/os_ext.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#676 [bugfix] Use the default Slurm partition with `--flex-alloc-tasks` if none is specified
  reframe/core/schedulers/slurm.py
  unittests/test_schedulers.py
Labels: bugfix, prio: normal

#695 [test] Change resources dir for GROMACS test
  cscs-checks/apps/gromacs/gromacs_check.py
Labels: enhancement, prio: normal, regression test

#696 [ci] Disable Dom from running in the ci
  Jenkinsfile
Labels: ci, prio: important
