Repository reframe-hpc/reframe, pull requests merged in 2020-07, with the labels that each got.

#1396 [ci] Use eb 3.1-dev0 recipe as template for deployment
  JenkinsfileDeploy
Labels: ci, prio: normal

#1399 [bugfix] Process execution modes before configuring logging
  reframe/frontend/cli.py
Labels: bugfix, prio: normal

#1400 [bugfix] Normalize ReFrame path prefixes
  bin/reframe
  reframe/__init__.py
Labels: bugfix, prio: normal

#1401 [doc] Expand documentation of `@require_deps` decorator
  reframe/core/decorators.py
Labels: documentation, enhancement

#1405 [ci] Use account option in CSCS CI
  config/cscs-ci.py
Labels: ci, prio: important

#1404 [feat] Add option to disable test stage directory cleanup
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
  reframe/utility/os_ext.py
  unittests/test_cli.py
  unittests/test_utility.py
Labels: enhancement, prio: normal

#1407 [test] Add account in executable options of RequiredConstraintCheck
  cscs-checks/system/slurm/slurm.py
Labels: prio: normal, regression test

#1409 [ci] Set the account dynamically in the configuration file for unit tests
  config/cscs-ci.py
Labels: ci, enhancement, prio: normal

#1413 [bugfix] Copy scheduler options when initializing job instances
  reframe/core/schedulers/__init__.py
Labels: bugfix, prio: urgent

#1410 [refactor] Add a powerful `repr()` function for debugging
  reframe/core/config.py
  reframe/core/debug.py
  reframe/core/logging.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/loader.py
  reframe/frontend/statistics.py
  reframe/utility/__init__.py
  unittests/test_policies.py
  unittests/test_utility.py
Labels: code quality, prio: important

#1411 [bugfix] Fix unit test failure of asynchronous execution policy
  unittests/fixtures.py
  unittests/test_argparser.py
Labels: bugfix, ci, prio: important

#1416 [feat] Add utility function for retrieving the current Cray CDT version
  reframe/utility/os_ext.py
  unittests/test_utility.py
Labels: feature request, prio: normal

#1419 [feat] Add utility function for retrieving Cray Linux Environment (CLE) information
  reframe/utility/os_ext.py
  unittests/test_utility.py
Labels: enhancement, prio: normal

#1418 [ci] Dynamically set the account in CSCS config
  config/cscs.py
Labels: ci, enhancement, prio: important

#1421 [test] Enhance workaround for PGI in CDT 20.06
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/prgenv/opencl_check.py
Labels: bug, enhancement, prio: normal

#1423 [bugfix] Use '&' to combine Slurm constraints
  cscs-checks/system/slurm/slurm.py
  docs/manpage.rst
  reframe/core/schedulers/slurm.py
  unittests/test_schedulers.py
Labels: bugfix, prio: important

#1425 [doc] Document that sanity functions use 're.MULTILINE'
  reframe/utility/sanity.py
Labels: bugfix, documentation

#1426 [test] Workaround for NetCDF tests for CDT20.06
  cscs-checks/libraries/io/netcdf_compile_run.py
Labels: prio: normal, regression test

#1403 [test] TrilinosTest_static build workaround for cdt/20.06
  cscs-checks/libraries/math/trilinos_compile_run.py
Labels: enhancement, prio: normal, regression test

#1424 [bugfix] Convert Syslog handler port parameter into integer
  reframe/core/logging.py
  unittests/test_logging.py
Labels: bugfix, prio: normal

#1427 [feat] Allow Syslog's address to be set from an environment variable
  docs/manpage.rst
  reframe/frontend/cli.py
Labels: enhancement, prio: normal

#1428 [feat] Increase default concurrency of asynchronous execution policy to 8 jobs
  docs/config_reference.rst
  docs/tutorial_basics.rst
  reframe/schemas/config.json
  tutorials/config/settings.py
  unittests/test_config.py
Labels: enhancement, prio: normal

#1431 [ci] Change modules system for Dom to TMod4
  config/cscs-ci.py
  config/cscs.py
Labels: bugfix, ci, prio: urgent

#1434 [bugfix] Capture all pending test tasks in the exit loop of the asynchronous execution policy
  reframe/frontend/executors/policies.py
Labels: bugfix, prio: normal

#1377 [feat] Produce detailed JSON report for a regression testing session
  docs/config_reference.rst
  docs/manpage.rst
  docs/tutorial_basics.rst
  reframe/core/pipeline.py
  reframe/core/systems.py
  reframe/frontend/cli.py
  reframe/frontend/statistics.py
  reframe/schemas/config.json
  reframe/schemas/runreport.json
  unittests/test_cli.py
  unittests/test_policies.py
Labels: feature request, prio: normal

#1435 [ci] Revert dom config to TMod modules system
  config/cscs-ci.py
  config/cscs.py
Labels: ci, prio: urgent

#1433 [feat] Support multiple tags in `extract*` sanity functions
  reframe/utility/sanity.py
  unittests/test_sanity_functions.py
Labels: enhancement, prio: normal

#1438 [bugfix] Fix JSON schema $id parameter
  reframe/schemas/config.json
  reframe/schemas/runreport.json
Labels: bugfix, prio: normal

#1439 [bugfix] Fix glob pattern to search for both txt and yaml
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
Labels: bugfix, prio: normal
