Repository reframe-hpc/reframe, pull requests merged in 2020-10, with the labels that each got.

#1490 [feat] Add configuration parameter for automatically capturing command errors and exit code in job scripts
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/pipeline.py
  reframe/schemas/config.json
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1402 [feat] Redesign job polling mechanism in the framework
  reframe/core/exceptions.py
  reframe/core/fields.py
  reframe/core/launchers/mpi.py
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  reframe/core/schedulers/torque.py
  reframe/core/systems.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  unittests/resources/checks/frontend_checks.py
  unittests/resources/checks/hellocheck.py
  unittests/test_cli.py
  unittests/test_config.py
  unittests/test_fields.py
  unittests/test_launchers.py
  unittests/test_loader.py
  unittests/test_pipeline.py
  unittests/test_policies.py
  unittests/test_schedulers.py
  unittests/test_utility.py
Labels: code quality, enhancement, prio: normal

#1506 [bugfix] Print current environment and partition correctly even if a test fails before the setup
  reframe/frontend/statistics.py
Labels: bugfix, prio: normal

#1508 [bugfix] Do not require a configuration to be resolved always at system level
  reframe/core/config.py
  reframe/core/systems.py
  reframe/frontend/cli.py
  unittests/test_config.py
Labels: bugfix, prio: normal

#1513 [bugfix] Treat correctly forced local jobs and other small fixes
  reframe/core/systems.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  unittests/test_cli.py
  unittests/test_policies.py
  unittests/test_schedulers.py
Labels: bugfix, prio: important

#1514 [test] Remove Openfoam check
  cscs-checks/apps/openfoam/check_openfoam.py
  cscs-checks/apps/openfoam/check_openfoam_extend.py
Labels: prio: normal, regression test

#1509 [feat] Delay the setup of performance logging, so that `perf_patterns` can be defined after the test construction
  reframe/core/pipeline.py
Labels: enhancement, prio: normal

#1510 [bugfix] Fix error message when a sane Tmod installation cannot be found
  reframe/core/modules.py
Labels: bugfix, prio: normal

#1517 [bugfix] Fix typo in modules system unit tests
  unittests/test_modules.py
Labels: bugfix, code quality, prio: normal

#1518 [ci] Remove the unit tests from the coverage report
  .travis.yml
Labels: ci, prio: normal

#1512 [test] Add test for parallel HDF5 via h5py
  cscs-checks/libraries/io/h5py_parallel_run.py
  cscs-checks/libraries/io/src/h5py_mpi_test.py
Labels: prio: normal, regression test

#1528 [test] Remove C++ language bindings from MPI checks
  cscs-checks/prgenv/src/mpi/hello_world_mpi.cpp
  cscs-checks/prgenv/src/mpi_thread/mpi_init_thread.cpp
Labels: prio: normal, regression test

#1530 [doc] Remove session-id from basic tutorial report
  docs/tutorial_basics.rst
Labels: bugfix, documentation, prio: normal

#1507 [test] Remove PrgEnv-pgi from FFTW test
  cscs-checks/microbenchmarks/fft/fftw_benchmark.py
Labels: bugfix, prio: normal

#1531 [feat] Set the default location for log files to be the system's temporary directory
  config/cscs-ci.py
  docs/config_reference.rst
  docs/tutorial_basics.rst
  docs/tutorial_deps.rst
  docs/tutorial_misc_topics.rst
  reframe/core/logging.py
  reframe/core/schedulers/__init__.py
  reframe/core/settings.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
  tutorials/config/settings.py
  unittests/resources/settings.py
  unittests/test_cli.py
Labels: enhancement, prio: normal

#1505 [test] Reorganise directory structure for benchmarks
  config/cscs.py
  cscs-checks/cuda/cuda_checks.py
  cscs-checks/microbenchmarks/cpu/alloc_speed/alloc_speed.py
  cscs-checks/microbenchmarks/cpu/alloc_speed/src/alloc_speed.cpp
  cscs-checks/microbenchmarks/cpu/dgemm/dgemm.py
  cscs-checks/microbenchmarks/cpu/dgemm/src/dgemm.c
  cscs-checks/microbenchmarks/cpu/fft/fftw_benchmark.py
  cscs-checks/microbenchmarks/cpu/fft/src/fftw_benchmark.c
  cscs-checks/microbenchmarks/cpu/latency/latency.py
  cscs-checks/microbenchmarks/cpu/latency/src/latency.cpp
  cscs-checks/microbenchmarks/cpu/likwid/likwid.py
  cscs-checks/microbenchmarks/cpu/simd/nsimd.py
  cscs-checks/microbenchmarks/cpu/simd/vc.py
  cscs-checks/microbenchmarks/cpu/stream/src/stream.c
  cscs-checks/microbenchmarks/cpu/stream/stream.py
  cscs-checks/microbenchmarks/cpu/strided_bandwidth/src/strides.cpp
  cscs-checks/microbenchmarks/cpu/strided_bandwidth/strides.py
  cscs-checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py
  cscs-checks/microbenchmarks/gpu/gpu_burn/src/gpu_burn.cu
  cscs-checks/microbenchmarks/gpu/kernel_latency/kernel_latency.py
  cscs-checks/microbenchmarks/gpu/kernel_latency/src/kernel_latency.cu
  cscs-checks/microbenchmarks/gpu/memory_bandwidth.py
  cscs-checks/microbenchmarks/gpu/shmem/shmem.py
  cscs-checks/microbenchmarks/gpu/shmem/src/shmem.cu
  cscs-checks/microbenchmarks/gpu/spec-accel/spec.py
  cscs-checks/microbenchmarks/gpu/spec-accel/src/cscs-cray
  cscs-checks/microbenchmarks/gpu/spec-accel/src/cscs-gnu
  cscs-checks/microbenchmarks/gpu/spec-accel/src/cscs-pgi
  cscs-checks/microbenchmarks/mpi/halo_exchange/halo_cell_exchange.py
  cscs-checks/microbenchmarks/mpi/halo_exchange/src/halo_cell_exchange.c
  cscs-checks/microbenchmarks/mpi/halo_exchange/src/input.txt
  cscs-checks/microbenchmarks/mpi/osu/osu_tests.py
  cscs-checks/microbenchmarks/mpi/osu/src/Makefile_allreduce
  cscs-checks/microbenchmarks/mpi/osu/src/Makefile_alltoall
  cscs-checks/microbenchmarks/mpi/osu/src/Makefile_p2p
  cscs-checks/microbenchmarks/mpi/osu/src/osu_allreduce.c
  cscs-checks/microbenchmarks/mpi/osu/src/osu_alltoall.c
  cscs-checks/microbenchmarks/mpi/osu/src/osu_bw.c
  cscs-checks/microbenchmarks/mpi/osu/src/osu_latency.c
  cscs-checks/microbenchmarks/mpi/osu/src/osu_util.c
  cscs-checks/microbenchmarks/mpi/osu/src/osu_util.h
  cscs-checks/prgenv/cuda/cuda_aware_mpi.py
  cscs-checks/prgenv/cuda/cuda_memtest_check.py
  cscs-checks/prgenv/cuda/cuda_samples.py
  cscs-checks/prgenv/cuda/nvml_check.py
  cscs-checks/prgenv/cuda/src/cuda_memtest-1.2.3.patch
  cscs-checks/prgenv/cuda/src/nvml_example.patch
Labels: prio: normal, regression test

#1533 [ci] Enable parallel execution of unit tests and pin versions of requirements
  ci-scripts/ci-runner.bash
  docs/requirements.txt
  requirements.txt
Labels: ci, enhancement, prio: normal

#1529 [feat] Add option to install pygelf in boostrap script
  bootstrap.sh
  requirements.txt
Labels: enhancement, prio: normal

#1540 [bugfix] Fix bug when patchlevel in environment modules version is not an integer
  reframe/core/modules.py
Labels: bugfix, prio: normal

#1541 [doc] Publish the utility modules and submodules
  ci-scripts/ci-runner.bash
  config/cscs-ci.py
  config/cscs.py
  cscs-checks/apps/jupyter/check_ipcmagic.py
  cscs-checks/apps/tensorflow/tf2_horovod_check.py
  cscs-checks/libraries/boost/boost_python_check.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/trilinos_compile_run.py
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/prgenv/opencl_check.py
  cscs-checks/system/slurm/slurm.py
  docs/conf.py
  docs/configure.rst
  docs/exceptions.rst
  docs/manuals.rst
  docs/programming_apis.rst
  docs/regression_test_api.rst
  docs/utility_functions_reference.rst
  reframe/core/config.py
  reframe/core/environments.py
  reframe/core/exceptions.py
  reframe/core/logging.py
  reframe/core/modules.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  reframe/core/schedulers/torque.py
  reframe/frontend/cli.py
  reframe/frontend/loader.py
  reframe/utility/__init__.py
  reframe/utility/jsonext.py
  reframe/utility/osext.py
  reframe/utility/typecheck.py
  unittests/fixtures.py
  unittests/test_cli.py
  unittests/test_config.py
  unittests/test_environments.py
  unittests/test_pipeline.py
  unittests/test_policies.py
  unittests/test_schedulers.py
  unittests/test_shell.py
  unittests/test_utility.py
Labels: documentation, prio: normal

#1544 [test] Fix osext import in CUDA tests
  cscs-checks/prgenv/cuda/cuda_aware_mpi.py
  cscs-checks/prgenv/cuda/cuda_samples.py
Labels: bugfix, prio: urgent, regression test

#1548 [bugfix] Fix `IndexError` crash of `osext.copytree()` when the source directory does not exist
  reframe/utility/osext.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#1549 [feat] Color deprecation warnings
  ci-scripts/ci-runner.bash
  reframe/core/config.py
  reframe/core/deferrable.py
  reframe/core/exceptions.py
  reframe/core/fields.py
  reframe/core/meta.py
  reframe/core/pipeline.py
  reframe/core/systems.py
  reframe/core/warnings.py
  reframe/frontend/cli.py
  unittests/resources/checks_unlisted/deprecated_test.py
  unittests/test_config.py
  unittests/test_fields.py
  unittests/test_loader.py
  unittests/test_warnings.py
Labels: enhancement, prio: normal

#1553 [ci] Update maintenance mode for CSCS config
  config/cscs.py
Labels: bugfix, prio: important

#1552 [feat] Control verbosity of check failure info
  reframe/core/decorators.py
  reframe/core/exceptions.py
  reframe/frontend/cli.py
  reframe/frontend/statistics.py
  reframe/schemas/runreport.json
  reframe/utility/jsonext.py
  unittests/test_policies.py
Labels: enhancement, prio: normal

#1561 [bugfix] Add newline at the end of run report
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: bugfix, prio: normal
