Repository reframe-hpc/reframe, pull requests merged in 2020-06, with the labels that each got.

#1342 [feat] Add configuration option to disable the ReqNodeNotAvail check
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/schedulers/slurm.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
Labels: bugfix, enhancement, prio: normal

#1355 [bugfix] Unset all ReFrame environment variables before running the unit tests
  test_reframe.py
Labels: bugfix, prio: important

#1344 [test] Convert JacobiNoToolHybrid to pipeline hook format
  cscs-checks/tools/profiling_and_debugging/README.md
  cscs-checks/tools/profiling_and_debugging/ddt.py
  cscs-checks/tools/profiling_and_debugging/gdb4hpc.py
  cscs-checks/tools/profiling_and_debugging/gperftools_mpi_omp.py
  cscs-checks/tools/profiling_and_debugging/intel_sde_berkeley_stream.py
  cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
  cscs-checks/tools/profiling_and_debugging/notool.py
Labels: prio: normal, regression test

#1358 [doc] Add documentation about the cleanup stage for tests with dependencies
  docs/dependencies.rst
  docs/pipeline.rst
Labels: documentation, prio: normal

#1347 [feat] Add node list information for jobs submitted with the Torque backend
  reframe/core/schedulers/torque.py
  unittests/test_schedulers.py
Labels: feature request, prio: normal

#1357 [feat] Drop option `--flex-alloc-tasks` and internal unused sanity function utilities
  docs/manpage.rst
  reframe/core/deferrable.py
  reframe/frontend/cli.py
Labels: enhancement, prio: important

#1359 [bugfix] Fix parsing of completion time of Slurm jobs
  reframe/core/schedulers/slurm.py
Labels: bugfix, prio: normal

#1325 [feat] Add execution time profiling for the framework's pipeline
  docs/pipeline.rst
  docs/tutorial_basic.rst
  docs/tutorial_deps.rst
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
Labels: feature request, prio: normal

#1356 [feat] Add configuration option for always emitting `--nodes` in Slurm job scripts
  docs/config_reference.rst
  reframe/core/schedulers/slurm.py
  reframe/schemas/config.json
  unittests/test_schedulers.py
Labels: feature request, prio: normal

#1304 [test] New Slurm setup for Cp2kGpuCheck
  cscs-checks/apps/cp2k/cp2k_check.py
Labels: prio: normal, regression test

#1364 [test] Exclude Slurm memory overconsumption test from Tsa
  cscs-checks/system/slurm/slurm.py
Labels: prio: normal, regression test

#1373 [bugfix] Fix AttributeError when pipeline hooks are defined in a mixin class
  reframe/core/meta.py
Labels: bugfix, prio: normal

#1360 [test] Add check for IPCMagic
  cscs-checks/apps/jupyter/check_ipcmagic.py
  cscs-checks/apps/jupyter/src/tf-hvd-sgd-ipc-tf-1.14.py
Labels: regression test

#1371 [feat] Add bootstrap script to install dependencies of ReFrame
  README.md
  bin/reframe
  bootstrap.sh
  ci-scripts/ci-runner.bash
  ci-scripts/deploy.sh
  docs/conf.py
  docs/started.rst
  reframe.py
  test_reframe.py
Labels: enhancement, prio: normal

#1363 [bugfix] Combine access and job options for slurm '--constraint'
  docs/manpage.rst
  reframe/core/schedulers/slurm.py
  unittests/test_schedulers.py
Labels: bugfix, prio: normal

#1374 [feat] Allow flexible node allocation to select nodes in any state
  docs/manpage.rst
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/slurm.py
  reframe/frontend/cli.py
  unittests/test_schedulers.py
Labels: enhancement, prio: normal

#1386 [doc] Create man pages in proper man subdirectories
  docs/Makefile
Labels: documentation, enhancement

#1385 [test] Update P2P test on Dom
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: prio: normal, regression test

#1388 [test] Remove PrgEnv-cray_classic from Dom and add it to Daint
  config/cscs.py
Labels: enhancement, regression test

#1387 [test] Fix deprecation warning in IPCMagicCheck
  cscs-checks/apps/jupyter/check_ipcmagic.py
Labels: enhancement, regression test

#1389 [test] PrgEnv-pgi workaround for CDT 20.06
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/prgenv/opencl_check.py
Labels: prio: normal, regression test

#1393 [bugfix] Add missing launchers `upcrun` and `upcxx-run` in configuration schema
  reframe/schemas/config.json
Labels: bugfix, prio: normal

#1384 [test] Update configuration and tests for MCH system
  config/cscs-ci.py
  config/cscs.py
  cscs-checks/cuda/cuda_checks.py
  cscs-checks/mch/cuda_stress_test.py
  cscs-checks/mch/gpu_direct_cuda.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/system/slurm/slurm.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
Labels: enhancement, regression test
