Repository reframe-hpc/reframe, pull requests merged in 2020-08, with the labels that each got.

#1443 [test] Update libsci resolve test
  cscs-checks/compile/libsci_resolve.py
Labels: prio: important, regression test

#1440 [bugfix] Remove PrgEnv-pgi for dom and adjust references
  cscs-checks/microbenchmarks/fft/fftw_benchmark.py
Labels: bugfix, prio: normal

#1441 [test] Update Boost test
  cscs-checks/libraries/boost/boost_python_check.py
Labels: prio: important, regression test

#1444 [test] Use default module for Numpy checks
  cscs-checks/apps/python/numpy_check.py
Labels: prio: important, regression test

#1442 [test] Update libsci acc symlink test
  cscs-checks/compile/libsci_acc_symlink.py
Labels: prio: important, regression test

#1448 [test] Use default Quantum Espresso module
  cscs-checks/apps/quantumespresso/quantumespresso_check.py
Labels: prio: important, regression test

#1449 [test] Fix 'coloredSphere.py' script for Paraview 5.8
  cscs-checks/apps/paraview/src/coloredSphere.py
Labels: prio: important, regression test

#1450 [test] Update OpenACCFortranChecks
  cscs-checks/prgenv/openacc_checks.py
Labels: enhancement, prio: important

#1451 [test] Remove LINKER workaround from tests
  cscs-checks/compile/libsci_resolve.py
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/scalapack_compile_run.py
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/microbenchmarks/stream/stream.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/prgenv/mpi_t.py
  cscs-checks/tools/profiling_and_debugging/notool.py
Labels: enhancement, prio: important, regression test

#1455 [test] Update OpenCL test
  cscs-checks/prgenv/opencl_check.py
Labels: prio: important, regression test

#1454 [test] Update Boost test
  cscs-checks/libraries/boost/boost_python_check.py
Labels: prio: normal, regression test

#1445 [test] Update tf2 Horovod check
  cscs-checks/apps/tensorflow/tf2_horovod_check.py
Labels: prio: important, regression test

#1456 [test] Use CUDA_HOME workaround for pgi in cdt-20.08
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
Labels: bugfix, prio: important, regression test

#1452 [test] Update the ipcmagic check to TF2
  cscs-checks/apps/jupyter/check_ipcmagic.py
  cscs-checks/apps/jupyter/src/tf-hvd-sgd-ipc-tf-1.14.py
  cscs-checks/apps/jupyter/src/tf-hvd-sgd-ipc-tf2.py
Labels: regression test

#1429 [refactor] Convert unit tests to pytest syntax using fixtures
  reframe/core/buildsystems.py
  reframe/utility/sanity.py
  unittests/fixtures.py
  unittests/test_buildsystems.py
  unittests/test_check_filters.py
  unittests/test_color.py
  unittests/test_containers.py
  unittests/test_deferrable.py
  unittests/test_environments.py
  unittests/test_exceptions.py
  unittests/test_fields.py
  unittests/test_launchers.py
  unittests/test_loader.py
  unittests/test_logging.py
  unittests/test_modules.py
  unittests/test_sanity_functions.py
  unittests/test_schedulers.py
  unittests/test_shell.py
  unittests/test_typecheck.py
  unittests/test_utility.py
  unittests/test_versioning.py
Labels: code quality, prio: normal

#1460 [bugfix] Add always units in the default reference tuple
  reframe/core/pipeline.py
Labels: bugfix, prio: normal

#1463 [bugfix] Remove snx1600tds from test
  cscs-checks/system/io/ior_check.py
Labels: prio: normal, regression test
