Repository reframe-hpc/reframe, pull requests merged in 2020-05, with the labels that each got.

#1287 [bugfix] Fix deprecation warnings in unit tests
  ci-scripts/ci-runner.bash
  unittests/resources/checks/frontend_checks.py
  unittests/resources/checks_unlisted/selfkill.py
Labels: bugfix, enhancement, prio: normal

#1289 [test] Fix DGEMM test for PrgEnv-intel
  cscs-checks/microbenchmarks/dgemm/dgemm.py
Labels: prio: normal, regression test

#1291 [test] Update GridTools tests
  cscs-checks/libraries/gridtools/gridtools_tests.py
Labels: prio: normal, regression test

#1293 [bugfix] Fix the import of `getlauncher()` function in Greasy test
  cscs-checks/apps/greasy/greasy_check.py
Labels: bugfix, prio: urgent

#1303 [bugfix] Use absolute path as stage and output directory prefixes
  reframe/core/runtime.py
  reframe/frontend/cli.py
Labels: bugfix, prio: important

#1300 [test] Add specific failure message in HPCG test when number of processes cannot be factorized
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
Labels: prio: normal, regression test

#1296 [test] Fix Slurm constraint check for cabinets
  cscs-checks/system/slurm/slurm.py
Labels: prio: normal, regression test

#1301 [bugfix] Fix possible deadlock in PBS-based scheduler backends when a job is cancelled immediately after submission
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/torque.py
Labels: bugfix, prio: important

#1302 [feat] Allow users to set the output file in the configuration conversion tool
  docs/migration_2_to_3.rst
  reframe/core/config.py
  tools/convert-config
  tools/convert_config.py
Labels: feature request, prio: normal

#1306 [doc] Fix tutorial configuration
  ci-scripts/ci-runner.bash
  tutorial/config/settings.py
Labels: bugfix, documentation

#1310 [misc] Fix bottom line of performance report
  reframe/frontend/statistics.py
Labels: enhancement, prio: normal

#1311 [bugfix] Fix formatting of search path info line in output
  reframe/frontend/cli.py
Labels: bugfix, prio: normal

#1320 [feat] Add JSON support to the configuration conversion tool
  docs/migration_2_to_3.rst
  reframe/core/config.py
  tools/convert_config.py
Labels: enhancement, prio: normal

#1324 [feat] Insert 'noqa' annotations in long lines generated by the configuration conversion tool
  reframe/core/config.py
Labels: feature request, prio: normal

#1307 [bugfix] Fix behaviour of verbosity option
  reframe/frontend/cli.py
Labels: bugfix, prio: normal

#1309 [bugfix] Disable recursive search of checks by default
  docs/config_reference.rst
  schemas/config.json
  tutorial/config/settings.py
  unittests/test_argparser.py
Labels: bugfix, prio: normal

#1321 [bugfix] Fix handling of `perflogdir` in the configuration conversion tool
  reframe/core/config.py
  unittests/test_config.py
Labels: bugfix, prio: normal

#1323 [doc] Refine and enhance documentation
  docs/Makefile
  docs/_static/img/async-exec-policy.svg
  docs/_static/img/pipeline.svg
  docs/_static/img/serial-exec-policy.svg
  docs/about.rst
  docs/advanced.rst
  docs/conf.py
  docs/config_reference.rst
  docs/configure.rst
  docs/deferrables.rst
  docs/dependencies.rst
  docs/index.rst
  docs/manpage.rst
  docs/manuals.rst
  docs/pipeline.rst
  docs/regression_test_api.rst
  docs/requirements.txt
  docs/running.rst
  docs/sanity_functions_reference.rst
  docs/started.rst
  docs/topics.rst
  docs/tutorial_advanced.rst
  docs/tutorial_basic.rst
  docs/tutorial_deps.rst
  docs/tutorials.rst
  reframe/core/buildsystems.py
  reframe/core/containers.py
  reframe/core/decorators.py
  reframe/core/environments.py
  reframe/core/launchers/__init__.py
  reframe/core/modules.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/core/schedulers/__init__.py
  reframe/core/systems.py
  reframe/frontend/cli.py
  reframe/utility/sanity.py
  tutorial/advanced/advanced_example10.py
  tutorial/advanced/advanced_example5.py
  tutorial/advanced/advanced_example9.py
  unittests/resources/checks/hellocheck_make.py
  unittests/resources/checks/src/Makefile
  unittests/resources/checks/src/Makefile.nofort
  unittests/resources/checks/src/hello.cpp
  unittests/resources/checks/src/hello.f90
Labels: documentation, enhancement, prio: normal

#1327 [doc] Update the required Sphinx version in conf.py
  docs/conf.py
Labels: documentation, prio: urgent

#1328 [doc] Add 'jsonschema' to documentation requirements
  docs/requirements.txt
Labels: documentation, prio: urgent

#1315 [ci] Create deployment Jenkinsfile
  JenkinsfileDeploy
Labels: ci, prio: normal

#1326 [feat] Print ReFrame environment variables in debug output
  reframe/frontend/argparse.py
  reframe/frontend/cli.py
Labels: enhancement, prio: important

#1314 [test] Add new MultiDeviceOpenaccTest on Kesch and Tsa
  cscs-checks/mch/multi_device_openacc.py
  cscs-checks/mch/src/Makefile.multi_device_openacc
  cscs-checks/mch/src/multi_device_openacc.F90
Labels: prio: normal, regression test

#1334 [feat] Print the config file loaded by ReFrame
  reframe/frontend/cli.py
Labels: enhancement, prio: important

#1335 [doc] Update help message
  docs/tutorial_basic.rst
  reframe/frontend/cli.py
Labels: documentation, enhancement, prio: important

#1337 [ci] Change the eb template version to 3.0-dev6 when deploying
  JenkinsfileDeploy
Labels: ci, prio: normal

#1340 [bugfix] Fix configuration option value for non-existent name-addressable configuration objects
  reframe/core/config.py
  unittests/test_config.py
Labels: bugfix, prio: important

#1331 [bugfix] Fix early abort when compile step fails with async policy
  reframe/frontend/executors/policies.py
  unittests/resources/checks/frontend_checks.py
  unittests/test_policies.py
Labels: bugfix, prio: normal

#1345 [test] Update QuantumESPRESSO GPU test
  cscs-checks/apps/quantumespresso/quantumespresso_check.py
Labels: prio: normal, regression test

#1333 [feat] Add support for UPC language and launchers
  docs/config_reference.rst
  reframe/core/buildsystems.py
  reframe/core/launchers/mpi.py
  unittests/test_launchers.py
Labels: enhancement, prio: normal

#1341 [bugfix] Fix the setup.py package installation script
  docs/config_reference.rst
  docs/manpage.rst
  docs/migration_2_to_3.rst
  docs/started.rst
  reframe/core/config.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
  setup.py
  tools/convert-config
  tools/convert_config.py
Labels: bugfix, prio: important

#1332 [feat] Add test description to failure report
  reframe/frontend/statistics.py
Labels: enhancement, prio: normal

#1346 [doc] Fine tune documentation
  docs/migration_2_to_3.rst
  docs/regression_test_api.rst
  reframe/core/decorators.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/core/schedulers/__init__.py
  reframe/core/systems.py
Labels: documentation, prio: normal

#1343 [feat] Add configuration option for using a login shell for jobs
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
Labels: enhancement, prio: normal

#1336 [feat] Unify the names of pre/postrun and pre/postbuild cmds
  cscs-checks/apps/icon/rrtmgp_check.py
  cscs-checks/apps/openfoam/check_openfoam.py
  cscs-checks/apps/openfoam/check_openfoam_extend.py
  cscs-checks/apps/spark/spark_check.py
  cscs-checks/apps/tensorflow/tensorflow_check.py
  cscs-checks/apps/tensorflow/tf2_horovod_check.py
  cscs-checks/apps/tensorflow/tf_horovod_check.py
  cscs-checks/compile/libsci_resolve.py
  cscs-checks/cuda/cuda_memtest_check.py
  cscs-checks/cuda/nvml_check.py
  cscs-checks/libraries/hpx/hpx_stencil.py
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/libraries/magma/magma_checks.py
  cscs-checks/libraries/math/trilinos_compile_run.py
  cscs-checks/mch/collectives_halo.py
  cscs-checks/mch/fieldextra_check.py
  cscs-checks/mch/g2g_meteoswiss_check.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
  cscs-checks/microbenchmarks/simd/nsimd.py
  cscs-checks/microbenchmarks/simd/vc.py
  cscs-checks/microbenchmarks/spec-accel/spec.py
  cscs-checks/prgenv/affinity_check.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/system/io/ior_check.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
  cscs-checks/tools/profiling_and_debugging/ddt.py
  cscs-checks/tools/profiling_and_debugging/gdb4hpc.py
  cscs-checks/tools/profiling_and_debugging/gperftools_mpi_omp.py
  cscs-checks/tools/profiling_and_debugging/intel_sde_berkeley_stream.py
  cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
  cscs-checks/tools/profiling_and_debugging/notool.py
  cscs-checks/tools/profiling_and_debugging/nvprof.py
  docs/migration_2_to_3.rst
  docs/tutorial_advanced.rst
  docs/tutorial_deps.rst
  reframe/core/pipeline.py
  reframe/utility/color.py
  tutorial/advanced/advanced_example7.py
  tutorial/advanced/osu/osu_benchmarks.py
  unittests/resources/checks/bad/relative_imports.py
  unittests/resources/checks/frontend_checks.py
  unittests/resources/checks_unlisted/good.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1338 [feat] Replace scheduler-specific command-line options
  docs/manpage.rst
  reframe/frontend/cli.py
Labels: feature request, prio: normal
