Repository reframe-hpc/reframe, pull requests merged in 2020-09, with the labels that each got.

#1461 [bugfix] Use new the 2020 pip dependency resolver in the bootstrap script
  bootstrap.sh
  requirements.txt
Labels: bugfix, prio: normal

#1469 [test] Remove obsolete TensorFlow tests
  cscs-checks/apps/tensorflow/tensorflow_check.py
  cscs-checks/apps/tensorflow/tf_horovod_check.py
Labels: prio: normal, regression test

#1462 [feat] Allow disabling pipeline hooks from the command line
  docs/manpage.rst
  reframe/core/meta.py
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1471 [ci] Set save location for JSON report files for CSCS
  config/cscs.py
Labels: ci, enhancement, prio: important

#1470 [feat] Drop tuple syntax for timer fields
  reframe/core/fields.py
  reframe/core/pipeline.py
  unittests/test_fields.py
Labels: enhancement, prio: normal

#1468 [bugfix] Fix `OrderedSet` implementation
  reframe/utility/__init__.py
  reframe/utility/os_ext.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#1472 [bugfix] Fix crash when git is not available
  reframe/utility/os_ext.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#1475 [bugfix] Fix formatting of summary listing of checks
  reframe/frontend/cli.py
Labels: bugfix, prio: normal

#1482 [test] Align tests for Daint and Dom
  config/cscs.py
  cscs-checks/apps/quantumespresso/quantumespresso_check.py
  cscs-checks/compile/haswell_fma_check.py
  cscs-checks/compile/libsci_acc_symlink.py
  cscs-checks/compile/libsci_resolve.py
  cscs-checks/libraries/boost/boost_python_check.py
  cscs-checks/libraries/boost/src/Makefile
Labels: prio: important, regression test

#1484 [test] Adjust CSCS user tools test
  cscs-checks/system/slurm/cscs_usertools.py
Labels: prio: important, regression test

#1370 [test] Reorganize resources of prog. environment tests
  cscs-checks/prgenv/affinity_check.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/prgenv/mpi.py
  cscs-checks/prgenv/mpi_t.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/prgenv/opencl_check.py
  cscs-checks/prgenv/src/affinity_ref/alternate_socket_filling.txt
  cscs-checks/prgenv/src/affinity_ref/consecutive_socket_filling.txt
  cscs-checks/prgenv/src/affinity_ref/gpu_omp_bind_cores.txt
  cscs-checks/prgenv/src/affinity_ref/gpu_omp_bind_threads.txt
  cscs-checks/prgenv/src/affinity_ref/gpu_omp_bind_threads_nomultithread.txt
  cscs-checks/prgenv/src/affinity_ref/mc_omp_bind_cores.txt
  cscs-checks/prgenv/src/affinity_ref/mc_omp_bind_threads.txt
  cscs-checks/prgenv/src/affinity_ref/mc_omp_bind_threads_nomultithread.txt
  cscs-checks/prgenv/src/affinity_ref/single_task_per_socket_omp.txt
  cscs-checks/prgenv/src/affinity_ref/single_task_per_socket_omp_multithread.txt
  cscs-checks/prgenv/src/mpi/hello_world_mpi.c
  cscs-checks/prgenv/src/mpi/hello_world_mpi.cpp
  cscs-checks/prgenv/src/mpi/hello_world_mpi.f90
  cscs-checks/prgenv/src/mpi/mpi_helloworld.c
  cscs-checks/prgenv/src/mpi_openmp/hello_world_mpi_openmp.c
  cscs-checks/prgenv/src/mpi_openmp/hello_world_mpi_openmp.cpp
  cscs-checks/prgenv/src/mpi_openmp/hello_world_mpi_openmp.f90
  cscs-checks/prgenv/src/mpi_t/mpit_categories.ref
  cscs-checks/prgenv/src/mpi_t/mpit_control_vars.ref
  cscs-checks/prgenv/src/mpi_t/mpit_perf_vars.ref
  cscs-checks/prgenv/src/mpi_t/mpit_vars.c
  cscs-checks/prgenv/src/mpi_thread/mpi_init_thread.cpp
  cscs-checks/prgenv/src/openacc/vecAdd_openacc_mpi.f90
  cscs-checks/prgenv/src/openacc/vecAdd_openacc_nompi.f90
  cscs-checks/prgenv/src/opencl/Makefile
  cscs-checks/prgenv/src/opencl/vecAdd.c
  cscs-checks/prgenv/src/opencl/vecAddKernel.cl
  cscs-checks/prgenv/src/openmp/hello_world_openmp.c
  cscs-checks/prgenv/src/openmp/hello_world_openmp.cpp
  cscs-checks/prgenv/src/openmp/hello_world_openmp.f90
  cscs-checks/prgenv/src/serial/hello_world_serial.c
  cscs-checks/prgenv/src/serial/hello_world_serial.cpp
  cscs-checks/prgenv/src/serial/hello_world_serial.f90
  cscs-checks/prgenv/src/ulimit/ulimit.c
  cscs-checks/prgenv/ulimit_check.py
Labels: prio: normal, regression test

#1480 [feat] Change default JSON report file pattern
  docs/config_reference.rst
  reframe/schemas/config.json
Labels: enhancement, prio: normal

#1488 [bugfix] Fix module import for files under `site-packages`
  reframe/utility/__init__.py
Labels: bugfix, prio: normal

#1489 [bugfix] Fix JSON report generation for deferred expressions
  reframe/core/deferrable.py
  reframe/frontend/cli.py
  reframe/utility/json.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#1491 [bugfix] Remove unnecessary error message from failure report
  reframe/frontend/statistics.py
Labels: bugfix, prio: normal

#1493 [bugfix] Fix bootstrap script for Ubuntu/Debian installation
  bootstrap.sh
  docs/started.rst
Labels: bugfix, prio: normal

#1483 [feat] Drop support of scheduler-specific command-line options
  docs/manpage.rst
  reframe/core/launchers/mpi.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  unittests/test_launchers.py
  unittests/test_schedulers.py
Labels: code quality, prio: normal

#1417 [feat] Add utility function to look for available environment modules
  config/cscs-ci.py
  reframe/core/modules.py
  reframe/utility/__init__.py
  unittests/test_modules.py
  unittests/test_utility.py
Labels: enhancement, prio: normal

#1501 [bugfix] Restore environment correctly in case of module load failures
  reframe/core/runtime.py
  unittests/test_environments.py
Labels: bugfix, prio: normal

#1499 [bugfix] Load configuration even if the username cannot be retrieved
  reframe/core/config.py
  unittests/test_config.py
Labels: bugfix, prio: normal
