Repository reframe-hpc/reframe, pull requests merged in 2020-12, with the labels that each got.

#1628 [ci] Use github/super-linter for unused import checks
  .github/linters/.flake8
  .github/workflows/main.yml
  README.md
  setup.py
Labels: ci, prio: normal

#1635 [doc] Remove superlinter badge from README
  README.md
  setup.py
Labels: documentation, prio: normal

#1630 [feat] Drop support for old configuration syntax
  docs/migration_2_to_3.rst
  reframe/core/config.py
  unittests/test_config.py
Labels: enhancement, prio: normal

#1633 [test] Update configuration and tests for the new batch policies
  config/cscs.py
  cscs-checks/system/slurm/slurm.py
Labels: prio: important, regression test

#1637 [bugfix] Fix detailed listing message for node allocation scheme
  reframe/frontend/cli.py
Labels: bugfix, prio: normal

#1547 [test] Update GridTools tests
  cscs-checks/libraries/gridtools/gridtools_tests.py
Labels: prio: normal, regression test

#1620 [ci] Add configuration entries for Eiger
  config/cscs.py
Labels: ci, prio: normal

#1644 [bugfix] Send test attributes correctly with the Graylog handler
  docs/config_reference.rst
  reframe/core/buildsystems.py
  reframe/core/deferrable.py
  reframe/core/logging.py
  reframe/core/pipeline.py
  reframe/utility/jsonext.py
  unittests/test_logging.py
Labels: bugfix, prio: important

#1636 [feat] Drop support of pipeline stage method override
  docs/migration_2_to_3.rst
  reframe/core/meta.py
  reframe/core/pipeline.py
  unittests/test_loader.py
Labels: enhancement, prio: normal

#1613 [test] Add MPI version of the eat memory check
  cscs-checks/system/slurm/slurm.py
  cscs-checks/system/slurm/src/eatmemory_mpi.c
Labels: prio: normal, regression test

#1538 [feat] Add ability to restore a test session and rerun selected tests
  docs/manpage.rst
  reframe/core/config.py
  reframe/core/environments.py
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/core/systems.py
  reframe/frontend/cli.py
  reframe/frontend/dependencies.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  reframe/frontend/runreport.py
  reframe/frontend/statistics.py
  reframe/schemas/runreport.json
  reframe/utility/jsonext.py
  reframe/utility/versioning.py
  unittests/resources/settings.py
  unittests/test_cli.py
  unittests/test_config.py
  unittests/test_pipeline.py
  unittests/test_policies.py
  unittests/test_schedulers.py
  unittests/test_utility.py
  unittests/test_versioning.py
Labels: enhancement, prio: normal

#1621 [test] Add HIP support for GPU microbenchmarks
  cscs-checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py
  cscs-checks/microbenchmarks/gpu/gpu_burn/src/Xdevice
  cscs-checks/microbenchmarks/gpu/gpu_burn/src/gpu_burn.cu
  cscs-checks/microbenchmarks/gpu/gpu_burn/src/makefile.cuda
  cscs-checks/microbenchmarks/gpu/gpu_burn/src/makefile.hip
  cscs-checks/microbenchmarks/gpu/kernel_latency/kernel_latency.py
  cscs-checks/microbenchmarks/gpu/kernel_latency/src/Xdevice
  cscs-checks/microbenchmarks/gpu/kernel_latency/src/kernel_latency.cu
  cscs-checks/microbenchmarks/gpu/kernel_latency/src/makefile.cuda
  cscs-checks/microbenchmarks/gpu/kernel_latency/src/makefile.hip
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/memory_bandwidth.py
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/p2p_bandwidth.py
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/blas.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/common/smi.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/cuda/blas.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/cuda/include.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/cuda/smi.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/cuda/tools.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/cuda/utils.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/defaults.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/hip/blas.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/hip/include.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/hip/smi.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/hip/tools.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/hip/utils.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/runtime.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/smi.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/makefile_memoryBandwidth.cuda
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/makefile_memoryBandwidth.hip
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/makefile_p2pBandwidth.cuda
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/makefile_p2pBandwidth.hip
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/memory_bandwidth.cu
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/p2p_bandwidth.cu
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/testHeaders.hpp
  cscs-checks/microbenchmarks/gpu/shmem/shmem.py
  cscs-checks/microbenchmarks/gpu/shmem/src/Xdevice
  cscs-checks/microbenchmarks/gpu/shmem/src/makefile.cuda
  cscs-checks/microbenchmarks/gpu/shmem/src/makefile.hip
  cscs-checks/microbenchmarks/gpu/shmem/src/shmem.cu
Labels: prio: normal, regression test

#1649 [bugfix] Fix formatting of lists of non-string objects when logging
  reframe/core/logging.py
  unittests/test_logging.py
Labels: bugfix, prio: important

#1652 [feat] Remove the --use-feature=2020-resolver from bootstrap
  bootstrap.sh
Labels: packaging, prio: normal

#1651 [test] Fix GPU burn test output
  cscs-checks/microbenchmarks/gpu/gpu_burn/src/gpu_burn.cu
Labels: bugfix, regression test

#1654 [bugfix] Fix module backend implementation for Lmod versions < 8.2
  .github/workflows/main.yml
  ci-scripts/dockerfiles/Lmod77.dockerfile
  reframe/core/modules.py
Labels: bugfix, prio: important

#1658 [ci] Disable parallel unittests in CI for eiger
  ci-scripts/ci-runner.bash
Labels: ci, prio: important

#1657 [test] Adapt GROMACS test to Eiger
  cscs-checks/apps/gromacs/gromacs_check.py
Labels: prio: normal, regression test

#1659 [bugfix] Properly expand environment variables for the filelog log handler
  reframe/core/logging.py
  unittests/test_cli.py
Labels: bugfix, prio: normal

#1656 [bugfix] Restore module paths specified in command line when restoring module collections
  reframe/core/modules.py
  unittests/test_modules.py
Labels: bugfix, prio: normal

#1655 [ci] Ensure that module paths are restored correctly in unit tests
  requirements.txt
  unittests/test_cli.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#1653 [test] Extend GPU burn test to report GPU node with smallest flops
  cscs-checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py
Labels: prio: normal, regression test

#1662 [bugfix] Pass the job id when raising job-related errors
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
Labels: bugfix, prio: normal

#1624 [feat] Support `spack load` for loading software packages
  ci-scripts/configs/spack.py
  ci-scripts/dockerfiles/Spack.dockerfile
  docs/config_reference.rst
  reframe/core/modules.py
  reframe/schemas/config.json
  unittests/fixtures.py
  unittests/test_cli.py
  unittests/test_modules.py
Labels: feature request, prio: normal

#1665 [bugfix] Do not evaluate deferred expressions when dumping in JSON
  reframe/core/deferrable.py
  unittests/test_logging.py
  unittests/test_utility.py
Labels: bugfix, prio: important

#1666 [bugfix] Fix documentation of sanity functions accepting a filename
  reframe/utility/sanity.py
Labels: bugfix, documentation, prio: normal

#1668 [ci] Add eiger to the PR message for ReFrame deployment
  JenkinsfileDeploy
Labels: ci, prio: normal

#1660 [test] Adapt CP2K checks for Eiger
  cscs-checks/apps/cp2k/cp2k_check.py
Labels: prio: normal, regression test

#1664 [test] Update MpiCheck for Alps
  cscs-checks/prgenv/mpi.py
  cscs-checks/prgenv/src/mpi_thread/mpi_init_thread.cpp
Labels: prio: normal, regression test

#1663 [test] Update MpiTCheck for Alps
  cscs-checks/prgenv/mpi_t.py
  cscs-checks/prgenv/src/mpi_t/mpit_categories_32.ref
  cscs-checks/prgenv/src/mpi_t/mpit_categories_33.ref
  cscs-checks/prgenv/src/mpi_t/mpit_control_vars_32.ref
  cscs-checks/prgenv/src/mpi_t/mpit_control_vars_33.ref
  cscs-checks/prgenv/src/mpi_t/mpit_perf_vars.ref
Labels: prio: normal, regression test
