Repository reframe-hpc/reframe, pull requests merged in 2020-01, with the labels that each got.

#1110 [bugfix] Remove `type` key from the environment configuration
  config/cscs-ci.py
  config/cscs-pbs.py
  config/cscs.py
  docs/configure.rst
  reframe/core/config.py
  tutorial/config/settings.py
  unittests/resources/settings.py
  unittests/test_config.py
Labels: bugfix, prio: normal

#1112 [test] Add native Spark check
  cscs-checks/apps/spark/spark_check.py
Labels: prio: normal, regression test

#1109 [bugfix] Fix dependency bug in async policy
  reframe/frontend/executors/policies.py
  unittests/resources/checks_unlisted/deps_complex.py
  unittests/test_policies.py
Labels: bugfix, prio: normal

#1118 [ci] Add Python 3.8 testing in Travis CI
  .travis.yml
  setup.py
Labels: ci, prio: normal

#1122 [misc] Add more shields in README
  README.md
  setup.py
Labels: enhancement, prio: normal

#1117 [bugfix] Fix incomplete printout of the performance report in case of test failures
  reframe/frontend/statistics.py
Labels: bugfix, prio: normal

#1132 [misc] Bump major version
  reframe/__init__.py
Labels: enhancement, prio: normal

#1129 [feat] Evaluate `extra_resources` just before job submission
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1127 [feat] Make the asynchronous execution policy default
  docs/running.rst
  docs/tutorial.rst
  reframe/frontend/cli.py
Labels: enhancement, prio: normal

#1135 [test] Make SimpleMpiCheck with CUDA more robust
  cscs-checks/cuda/cuda_checks.py
Labels: enhancement, regression test

#1125 [feat] Do not allow chaining of the `-c` option; pass multiple paths as a colon separated list
  docs/running.rst
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: enhancement, prio: normal

#1141 [ci] Use colon separated path convenction in CI
  Jenkinsfile
  ci-scripts/ci-runner.bash
Labels: ci, prio: important

#1124 [bugfix] Fix infinite loop bug when cleanup phase fails
  reframe/frontend/executors/policies.py
  reframe/frontend/printer.py
  unittests/resources/checks/frontend_checks.py
  unittests/test_loader.py
  unittests/test_policies.py
Labels: bugfix, prio: important

#1145 [docs] Add slides from 5th EasyBuild User Meeting presentation
  docs/index.rst
Labels: documentation, enhancement, prio: normal
