Repository reframe-hpc/reframe, pull requests merged in 2020-04, with the labels that each got.

#1252 [test] Set `max_pending_time` for the Jupyter tests
  cscs-checks/tools/jupyter/jupyter_tests.py
Labels: prio: normal, regression test

#1255 [test] Modernize the default programming environment check
  cscs-checks/prgenv/environ_check.py
Labels: prio: normal, regression test

#1251 [test] Add MPI Tool Information Interfaces (MPI_T) check
  cscs-checks/prgenv/mpi_t.py
  cscs-checks/prgenv/src/mpit_categories.ref
  cscs-checks/prgenv/src/mpit_control_vars.ref
  cscs-checks/prgenv/src/mpit_perf_vars.ref
  cscs-checks/prgenv/src/mpit_vars.c
Labels: prio: normal, regression test

#1230 [test] Update GROMACS test
  cscs-checks/apps/gromacs/gromacs_check.py
Labels: prio: normal, regression test

#1210 [test] Add GREASY test
  config/cscs.py
  cscs-checks/apps/greasy/greasy_check.py
  cscs-checks/apps/greasy/src/tasks_mpi_openmp.c
Labels: prio: normal, regression test

#1257 [bugfix] Do not crash in case of broken pipe errors
  reframe/core/logging.py
Labels: bugfix, prio: normal

#1256 [doc] Update "Use Cases" page of the documentation
  docs/usecases.rst
Labels: documentation, prio: normal

#1253 [feat] Support `*:<partition name>` name pattern in the list of valid systems
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1259 [bugfix] Fix `AttributeError` in flexible node allocation from the Slurm backend
  reframe/core/schedulers/slurm.py
  unittests/test_schedulers.py
Labels: bugfix, prio: important

#1228 [feat] Deprecate test syntax that overrides `RegressionTest` methods
  docs/index.rst
  docs/migration_2_to_3.rst
  docs/tutorial.rst
  reframe/core/meta.py
  reframe/core/pipeline.py
  unittests/resources/checks/frontend_checks.py
  unittests/resources/checks_unlisted/kbd_interrupt.py
  unittests/test_loader.py
Labels: enhancement, prio: normal

#1266 [ci] Implement XALT workaround for unit tests on Dom
  ci-scripts/ci-runner.bash
Labels: ci, prio: important

#1268 [bugfix] Improve the message of the deprecation warning about pipeline methods overrides
  reframe/core/meta.py
Labels: bugfix, prio: normal

#1262 [test] Update OSU Allreduce check
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: prio: normal, regression test

#1264 [test] Implement Cray linker workaround for CLE7.0.UP01.PS09
  cscs-checks/compile/libsci_resolve.py
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/scalapack_compile_run.py
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/microbenchmarks/stream/stream.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/prgenv/mpi_t.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/tools/profiling_and_debugging/ipm_mpi_omp.py
  cscs-checks/tools/profiling_and_debugging/notool.py
Labels: prio: important, regression test

#1271 [test] Update GPU burn test
  cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
Labels: enhancement, regression test

#1272 [test] Update G2G latency check
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: prio: normal, regression test

#1276 [test] Update GREASY test
  cscs-checks/apps/greasy/greasy_check.py
Labels: prio: normal, regression test

#1278 [bugfix] Fix string alignment in failure statistics
  reframe/frontend/statistics.py
  unittests/test_cli.py
Labels: bugfix, prio: normal

#1281 [test] Update LAMMPS test
  cscs-checks/apps/lammps/lammps_check.py
Labels: prio: normal, regression test

#1277 [test] Enable units in StreamTest when running with an unknown programming environment
  cscs-checks/microbenchmarks/stream/stream.py
Labels: prio: normal, regression test

#1279 [bugfix] More robust completion check for the Torque scheduler
  reframe/core/schedulers/torque.py
Labels: bugfix, prio: normal

#1275 [bugfix] Fix logging crash when increasing verbosity level
  docs/running.rst
  reframe/core/logging.py
  unittests/test_cli.py
Labels: bugfix, prio: normal

#1270 [test] Update tests for QuantumESPRESSO 6.5
  cscs-checks/apps/espresso/espresso_check.py
  cscs-checks/apps/quantumespresso/quantumespresso_check.py
  cscs-checks/apps/quantumespresso/src/Au.pbe-nd-van.UPF
  cscs-checks/apps/quantumespresso/src/ausurf.in
Labels: prio: normal, regression test
