Repository reframe-hpc/reframe, pull requests merged in 2020-03, with the labels that each got.

#1193 [bugfix] Do not leave stale test jobs when ReFrame receives a TERM signal
  reframe/core/exceptions.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  unittests/test_policies.py
Labels: bugfix, prio: normal

#1205 [bugfix] Include commit hash in ReFrame version when running
  reframe/frontend/cli.py
Labels: bugfix, prio: normal

#1207 [test] Implement workaround for PETSc test when using PrgEnv-intel and static linking
  cscs-checks/libraries/petsc/petsc_helloworld.py
Labels: prio: normal, regression test

#1191 [test] Temporarily fix HPCG reference version
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
Labels: prio: normal, regression test

#1209 [bugfix] Fix long description in setup script
  setup.py
Labels: bugfix, prio: important

#1156 [test] Migrate tool checks to hpctools.git
  cscs-checks/tools/profiling_and_debugging/README.md
  cscs-checks/tools/profiling_and_debugging/berkeley-ert-nvprof.py
  cscs-checks/tools/profiling_and_debugging/berkeley-ert.py
  cscs-checks/tools/profiling_and_debugging/gpp_nvprof_roofline.py
  cscs-checks/tools/profiling_and_debugging/intel_advisor_roofline.py
  cscs-checks/tools/profiling_and_debugging/intel_sde_roofline.py
  cscs-checks/tools/profiling_and_debugging/intel_vtune_roofline.py
  cscs-checks/tools/profiling_and_debugging/scorep_mpi_omp.py
Labels: prio: normal, regression test

#1148 [test] Adapt PrgEnv-cray flags for Trilinos check
  cscs-checks/libraries/math/trilinos_compile_run.py
Labels: prio: normal, regression test

#1211 [test] Correct the test for number of nodes in DGEMM
  cscs-checks/microbenchmarks/dgemm/dgemm.py
Labels: bugfix, prio: normal, regression test

#1208 [test] More robust treatment of unknown references in GpuBandwidthCheck
  cscs-checks/cuda/multi_gpu.py
Labels: prio: normal, regression test

#1172 [feat] Add support for the Torque scheduler
  ci-scripts/ci-runner.bash
  config/cscs-torque.py
  docs/configure.rst
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/registry.py
  reframe/core/schedulers/torque.py
  unittests/test_schedulers.py
Labels: enhancement, prio: normal

#1206 [feat] Add command-line option to suppress deprecation warnings
  reframe/frontend/cli.py
  unittests/resources/checks_unlisted/deprecated_test.py
  unittests/test_cli.py
Labels: enhancement, prio: normal

#1215 [ci] Remove 'Public Test' stage from CSCS CI
  Jenkinsfile
Labels: ci, prio: normal

#1217 [bugfix] Fix random 'test_sigterm' unit test failure
  unittests/test_policies.py
Labels: bugfix, prio: urgent

#1199 [test] Fix deprecated `time_limit` syntax in checks
  cscs-checks/apps/cpmd/cpmd_check.py
  cscs-checks/apps/paraview/paraview_check.py
  cscs-checks/microbenchmarks/spec-accel/spec.py
  cscs-checks/prgenv/mpi.py
  cscs-checks/system/io/ior_check.py
  cscs-checks/system/openstack/s3_check.py
  cscs-checks/system/slurm/slurm.py
  cscs-checks/tools/jupyter/jupyter_tests.py
Labels: prio: normal, regression test

#1214 [bugfix] Fix crash when creating a regression test interactively
  reframe/core/pipeline.py
  reframe/utility/os_ext.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#1218 [test] Update NAMD test
  cscs-checks/apps/namd/namd_check.py
Labels: prio: normal, regression test

#1220 [bugfix] Improve unit tests for the handling of the TERM signal
  unittests/test_policies.py
Labels: bugfix, prio: important

#1163 [bugfix] Execute setup hooks for `CompileOnlyRegressionTest` and make the run hooks for the `RunOnlyRegressionTest` execute at the right place
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: bugfix, prio: normal

#1225 [feat] Drop support for Python 3.5
  .travis.yml
  docs/started.rst
  reframe/__init__.py
  requirements.txt
  setup.py
Labels: enhancement, prio: normal

#1227 [bugfix] Make unit test for TERM signal handling more robust
  unittests/resources/checks_unlisted/selfkill.py
  unittests/test_policies.py
Labels: bugfix, prio: normal

#1099 [feat] Allow tests to timeout if their associated job is pending for too long
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  reframe/core/schedulers/torque.py
  unittests/test_schedulers.py
Labels: enhancement, feature request, prio: normal

#1223 [feat] Impose units in performance reference tuple
  cscs-checks/compile/haswell_fma_check.py
  cscs-checks/libraries/hpx/hpx_hello_world.py
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/collectives_halo.py
  cscs-checks/mch/cuda_stress_test.py
  cscs-checks/mch/fieldextra_check.py
  cscs-checks/mch/g2g_meteoswiss_check.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/tools/profiling_and_debugging/gperftools_mpi_omp.py
  docs/running.rst
  docs/tutorial.rst
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1224 [test] Use builtin programming environment for tests loading EB modules
  config/cscs.py
  cscs-checks/apps/amber/amber_check.py
  cscs-checks/apps/cp2k/cp2k_check.py
  cscs-checks/apps/cpmd/cpmd_check.py
  cscs-checks/apps/espresso/espresso_check.py
  cscs-checks/apps/gromacs/gromacs_check.py
  cscs-checks/apps/lammps/lammps_check.py
  cscs-checks/apps/namd/namd_check.py
  cscs-checks/apps/openfoam/check_openfoam.py
  cscs-checks/apps/openfoam/check_openfoam_extend.py
  cscs-checks/apps/paraview/paraview_check.py
  cscs-checks/apps/python/numpy_check.py
  cscs-checks/apps/spark/spark_check.py
  cscs-checks/apps/tensorflow/tensorflow_check.py
  cscs-checks/apps/tensorflow/tf2_horovod_check.py
  cscs-checks/apps/tensorflow/tf_horovod_check.py
  cscs-checks/libraries/boost/boost_python_check.py
  cscs-checks/libraries/gridtools/gridtools_tests.py
  cscs-checks/libraries/hpx/hpx_hello_world.py
  cscs-checks/libraries/hpx/hpx_stencil.py
  cscs-checks/libraries/magma/magma_checks.py
  cscs-checks/microbenchmarks/simd/nsimd.py
  cscs-checks/microbenchmarks/simd/vc.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
Labels: enhancement, prio: normal, regression test

#1235 [test] Update Vc and nsimd tests to Cray PE/19.10
  cscs-checks/microbenchmarks/simd/nsimd.py
  cscs-checks/microbenchmarks/simd/vc.py
Labels: prio: normal, regression test

#1231 [bugfix] Fix Slurm backend deadlock when ReFrame runs through midnight
  reframe/core/schedulers/slurm.py
Labels: bugfix, prio: normal

#1233 [test] Move patrun checks to the 'eth-cscs/hpctools' repo
  cscs-checks/tools/profiling_and_debugging/README.md
  cscs-checks/tools/profiling_and_debugging/perftools.py
Labels: prio: normal, regression test

#1232 [test] Update P2P latency tests
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: prio: normal, regression test

#1229 [test] Move MpiP and VTune checks to the eth-cscs/hpctools repo
  cscs-checks/tools/profiling_and_debugging/README.md
  cscs-checks/tools/profiling_and_debugging/intel_vtune.py
  cscs-checks/tools/profiling_and_debugging/mpip_mpi_omp.py
Labels: prio: normal, regression test

#1176 [feat] Print failure statistics table as well as the run options for failures
  reframe/frontend/cli.py
  reframe/frontend/statistics.py
  unittests/test_cli.py
Labels: enhancement, prio: normal

#1186 [feat] Add a tool to convert from the old to the new configuration syntax
  ci-scripts/ci-runner.bash
  reframe/core/config.py
  reframe/utility/__init__.py
  schemas/config.json
  schemas/settings.py
  tools/convert_config.py
  unittests/resources/settings.py
  unittests/test_utility.py
Labels: feature request, prio: normal

#1241 [test] Remove kesch:pn from supported systems of FlexAlltoallTest
  cscs-checks/microbenchmarks/osu/osu_tests.py
Labels: prio: normal, regression test

#1237 [feat] Print test dependencies in output of `--list-detailed`
  reframe/frontend/cli.py
Labels: feature request, prio: normal

#1240 [feat] Include progress report in output
  docs/advanced.rst
  docs/running.rst
  docs/tutorial.rst
  reframe/frontend/executors/__init__.py
  reframe/frontend/printer.py
Labels: feature request, prio: normal

#1239 [test] Remove unnecessary tags in the HaloExchangeTest
  cscs-checks/mch/collectives_halo.py
Labels: prio: normal, regression test

#1243 [bugfix] Fix formatting of the error message when an OS command fails
  reframe/core/exceptions.py
  reframe/utility/os_ext.py
  unittests/test_exceptions.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#1244 [doc] Add ReFrame logo to the documentation
  docs/_static/img/reframe-logo-dark-bg.svg
  docs/conf.py
  reframe/core/pipeline.py
Labels: documentation, enhancement, prio: normal

#1247 [bugfix] Do not update progress count when a test fails with status ERROR
  reframe/frontend/printer.py
Labels: bugfix, prio: normal

#1246 [test] Update nvprof test and add maintenance tag
  cscs-checks/tools/profiling_and_debugging/nvprof.py
Labels: prio: normal, regression test

#1248 [test] Update CP2K GPU checks
  cscs-checks/apps/cp2k/cp2k_check.py
Labels: prio: normal, regression test

#1249 [test] Update CP2K CPU small check
  cscs-checks/apps/cp2k/cp2k_check.py
Labels: prio: normal, regression test

#1250 [test] Update QE CPU checks
  cscs-checks/apps/espresso/espresso_check.py
Labels: prio: normal, regression test
