Repository reframe-hpc/reframe, pull requests merged in 2020-02, with the labels that each got.

#1140 [test] Improvements and fixes for static linking tests
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/scalapack_compile_run.py
  cscs-checks/libraries/petsc/petsc_helloworld.py
  cscs-checks/prgenv/helloworld.py
Labels: prio: normal, regression test

#1138 [test] Remove stale FIXME and NOTE tags from tests
  cscs-checks/libraries/math/trilinos_compile_run.py
  cscs-checks/mch/g2g_meteoswiss_check.py
  cscs-checks/mch/gpu_direct_cuda.py
  cscs-checks/tools/profiling_and_debugging/perftools.py
Labels: enhancement, regression test

#1128 [feat] Introduce new configuration syntax and validation schema
  requirements.txt
  schemas/config.json
  schemas/settings.py
Labels: enhancement, prio: normal

#1150 [feat] Support RFC3339 compliant time zone formatting when logging time fields
  docs/running.rst
  reframe/core/logging.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/slurm.py
  unittests/test_logging.py
Labels: enhancement, prio: normal

#1151 [test] Introduce workaround for static linking tests on Dom
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/scalapack_compile_run.py
  cscs-checks/prgenv/helloworld.py
Labels: prio: normal, regression test

#1166 [ci] Fix CI for Tsa
  ci-scripts/ci-runner.bash
  config/cscs-ci.py
Labels: ci, enhancement, prio: important

#1164 [config] Replace ShifterNg by Sarus in CSCS configuration
  config/cscs.py
Labels: enhancement, prio: normal

#1154 [test] Port ReFrame checks on Arolla and Tsa with PE 19.04
  config/cscs-ci.py
  config/cscs.py
  cscs-checks/cuda/cuda_checks.py
  cscs-checks/cuda/multi_gpu.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/collectives_halo.py
  cscs-checks/mch/cuda_stress_test.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/mch/gpu_direct_cuda.py
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
  cscs-checks/microbenchmarks/dgemm/dgemm.py
  cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
  cscs-checks/microbenchmarks/kernel_latency/kernel_latency.py
  cscs-checks/microbenchmarks/mpi/halo_cell_exchange.py
  cscs-checks/microbenchmarks/osu/osu_tests.py
  cscs-checks/microbenchmarks/stream/stream.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/prgenv/mpi.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/system/slurm/slurm.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
  cscs-checks/tools/profiling_and_debugging/ddt.py
  cscs-checks/tools/profiling_and_debugging/nvprof.py
Labels: prio: important, regression test

#1173 [test] Fix cuda module for GpuBurn on Kesch
  cscs-checks/microbenchmarks/gpu_burn/gpu_burn_test.py
Labels: prio: normal, regression test

#1174 [test] Adjust num_cpus_per_task on Arolla and Tsa
  cscs-checks/microbenchmarks/dgemm/dgemm.py
Labels: prio: normal, regression test

#1178 [test] Move Intel Inspector test to the external eth-cscs/hpctools repo
  cscs-checks/tools/profiling_and_debugging/intel_inspector.py
Labels: prio: normal, regression test

#1180 [test] Adapt CudaStressTest to Dom
  cscs-checks/mch/cuda_stress_test.py
Labels: prio: normal, regression test

#1152 [bugfix] Fix failure when check search path contains duplicates
  reframe/frontend/cli.py
  reframe/utility/os_ext.py
  unittests/test_cli.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#1179 [test] Fix CDO checks
  cscs-checks/tools/io/cdo.py
Labels: prio: normal, regression test

#1184 [feat] Print the current working directory in "ReFrame paths" output section
  reframe/frontend/cli.py
Labels: enhancement, prio: normal

#1182 [test] Update GROMACS maintenance reference values
  cscs-checks/apps/gromacs/gromacs_check.py
Labels: prio: normal, regression test

#1181 [test] Fix GridTools test failures on Dom
  cscs-checks/libraries/gridtools/gridtools_tests.py
Labels: prio: normal, regression test

#1142 [feat] Change `time_limit` attribute to a string-based format
  docs/advanced.rst
  docs/tutorial.rst
  reframe/core/fields.py
  reframe/core/launchers/mpi.py
  reframe/core/pipeline.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  reframe/utility/__init__.py
  tutorial/advanced/advanced_example5.py
  unittests/test_fields.py
  unittests/test_launchers.py
  unittests/test_schedulers.py
Labels: enhancement, prio: normal

#1190 [doc] Adjust copyright dates in documentation
  LICENSE
  docs/conf.py
Labels: documentation, enhancement, prio: normal

#1188 [refactor] Convert unittests to pytest syntax
  unittests/test_argparser.py
  unittests/test_buildsystems.py
  unittests/test_check_filters.py
  unittests/test_cli.py
  unittests/test_color.py
  unittests/test_config.py
  unittests/test_containers.py
  unittests/test_deferrable.py
  unittests/test_environments.py
  unittests/test_exceptions.py
  unittests/test_fields.py
  unittests/test_launchers.py
  unittests/test_loader.py
  unittests/test_logging.py
  unittests/test_modules.py
  unittests/test_pipeline.py
  unittests/test_policies.py
  unittests/test_runtime.py
  unittests/test_sanity_functions.py
  unittests/test_schedulers.py
  unittests/test_shell.py
  unittests/test_typecheck.py
  unittests/test_utility.py
  unittests/test_versioning.py
Labels: code quality, prio: normal

#1160 [test] Update tests with the new syntax using decorators
  cscs-checks/analytics/spark/spark_check.py
  cscs-checks/apps/amber/amber_check.py
  cscs-checks/apps/cp2k/cp2k_check.py
  cscs-checks/apps/cpmd/cpmd_check.py
  cscs-checks/apps/espresso/espresso_check.py
  cscs-checks/apps/icon/rrtmgp_check.py
  cscs-checks/apps/lammps/lammps_check.py
  cscs-checks/apps/namd/namd_check.py
  cscs-checks/apps/paraview/paraview_check.py
  cscs-checks/compile/haswell_fma_check.py
  cscs-checks/compile/libsci_acc_symlink.py
  cscs-checks/compile/libsci_resolve.py
  cscs-checks/cuda/cuda_memtest_check.py
  cscs-checks/cuda/nvml_check.py
  cscs-checks/libraries/gridtools/gridtools_tests.py
  cscs-checks/libraries/hpx/hpx_hello_world.py
  cscs-checks/libraries/hpx/hpx_stencil.py
  cscs-checks/libraries/magma/magma_checks.py
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/check_ruby.py
  cscs-checks/mch/collectives_halo.py
  cscs-checks/mch/fieldextra_check.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/microbenchmarks/alloc_speed/alloc_speed.py
  cscs-checks/microbenchmarks/dgemm/dgemm.py
  cscs-checks/microbenchmarks/fft/fftw_benchmark.py
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
  cscs-checks/microbenchmarks/latency/latency.py
  cscs-checks/microbenchmarks/likwid/likwid.py
  cscs-checks/microbenchmarks/mpi/halo_cell_exchange.py
  cscs-checks/microbenchmarks/osu/osu_tests.py
  cscs-checks/microbenchmarks/shmem/shmem.py
  cscs-checks/microbenchmarks/spec-accel/spec.py
  cscs-checks/microbenchmarks/stream/stream.py
  cscs-checks/microbenchmarks/strided_bandwidth/strides.py
  cscs-checks/prgenv/affinity_check.py
  cscs-checks/prgenv/cpu_target_check.py
  cscs-checks/prgenv/environ_check.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/prgenv/opencl_check.py
  cscs-checks/prgenv/ssh_environ_check.py
  cscs-checks/prgenv/ulimit_check.py
  cscs-checks/system/io/ior_check.py
  cscs-checks/system/openstack/s3_check.py
  cscs-checks/system/slurm/cscs_usertools.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
Labels: enhancement, prio: normal, regression test

#1183 [bugfix] Fix TypeError crash in the performance checking phase when the extracted performance variable value is not a number
  reframe/core/pipeline.py
  reframe/utility/sanity.py
  unittests/test_pipeline.py
Labels: bugfix, prio: normal

#1185 [feat] Set default value of `sourcesdir` to `'src'` only if such a directory exists, otherwise set to `None`
  reframe/core/pipeline.py
  unittests/fixtures.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1192 [misc] Use `check_job_completion_time` with timezone info for performance logging in all settings files
  config/cscs-ci.py
  config/cscs-pbs.py
  config/cscs.py
  config/tiger.py
  reframe/settings.py
  schemas/settings.py
  tutorial/config/settings.py
  unittests/resources/settings.py
Labels: enhancement, prio: normal

#1195 [doc] Add ReFrame logo to README
  README.md
  docs/_static/img/reframe_logo-full.png
Labels: documentation, enhancement, prio: normal

#1200 [test] Fix misleading variant description in the affinity check
  cscs-checks/prgenv/affinity_check.py
Labels: enhancement, regression test
