Repository reframe-hpc/reframe, pull requests merged in 2020-11, with the labels that each got.

#1564 [bugfix] Fix statistics crash when reporting task dependency errors
  reframe/core/exceptions.py
Labels: bugfix, prio: important

#1539 [test] GPU bandwidth benchmarks
  cscs-checks/microbenchmarks/gpu/memory_bandwidth.py
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/memory_bandwidth.py
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/p2p_bandwidth.py
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/cuda/include.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/cuda/tools.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/cuda/types.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/cuda/utils.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/hip/include.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/hip/tools.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/hip/types.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/hip/utils.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/Xdevice/runtime.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/bandwidth.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/makefile_memoryBandwidth.cuda
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/makefile_memoryBandwidth.hip
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/makefile_p2pBandwidth.cuda
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/makefile_p2pBandwidth.hip
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/memory_bandwidth.cu
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/p2p_bandwidth.cu
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/testHeaders.hpp
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/src/types.hpp
Labels: prio: normal, regression test

#1562 [feat] Accept file glob patterns in `keep_files`
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1556 [bugfix] Fix spacing issues when defining options for execution modes
  reframe/frontend/cli.py
  unittests/resources/settings.py
Labels: bugfix, prio: normal

#1565 [test] Update IOR test to use dependencies
  cscs-checks/system/io/ior_check.py
Labels: prio: normal, regression test

#1481 [feat] Allow dependencies between partitions
  docs/_static/img/test-deps-by-case.svg
  docs/_static/img/test-deps-by-env.svg
  docs/_static/img/test-deps-by-part.svg
  docs/_static/img/test-deps-by-xcase.svg
  docs/_static/img/test-deps-by-xenv.svg
  docs/_static/img/test-deps-by-xpart.svg
  docs/_static/img/test-deps-custom.svg
  docs/_static/img/test-deps-cycle.svg
  docs/_static/img/test-deps-dangling.svg
  docs/_static/img/test-deps-exact.svg
  docs/_static/img/test-deps-fully.svg
  docs/dependencies.rst
  docs/tutorial_deps.rst
  docs/utility_functions_reference.rst
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  reframe/frontend/dependencies.py
  reframe/frontend/executors/__init__.py
  reframe/utility/udeps.py
  tutorials/deps/osu_benchmarks.py
  unittests/resources/checks_unlisted/deps_simple.py
  unittests/test_dependencies.py
  unittests/test_pipeline.py
  unittests/test_policies.py
Labels: feature request, prio: normal

#1574 [ci] Restrict max flex alloc nodes for tutorial checks
  ci-scripts/ci-runner.bash
Labels: bugfix, ci, prio: normal

#1578 [ci] Disable parallel unit testing on tsa
  ci-scripts/ci-runner.bash
Labels: ci, prio: important

#1575 [bugfix] Fix handling of symbolic links in `osext.copytree()` when destination exists
  reframe/utility/osext.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#1571 [feat] Better logging of framework activities, especially test loading
  config/cscs-ci.py
  config/cscs.py
  docs/config_reference.rst
  reframe/core/config.py
  reframe/core/exceptions.py
  reframe/core/logging.py
  reframe/core/modules.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  reframe/core/schedulers/torque.py
  reframe/core/settings.py
  reframe/core/systems.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  reframe/frontend/loader.py
  reframe/schemas/config.json
  reframe/utility/osext.py
  unittests/test_exceptions.py
Labels: enhancement, prio: normal

#1583 [bugfix] Fix unit test error due the PID 1 problem when running inside a Docker container
  unittests/test_schedulers.py
Labels: bugfix, ci, prio: normal

#1580 [feat] Preserve symbolic links in sources directory
  reframe/core/pipeline.py
  unittests/resources/checks/src/hello.sh.link
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1576 [feat] Print more information about dependencies in detailed test listing
  reframe/frontend/cli.py
Labels: enhancement, prio: normal

#1587 [ci] Change base eb recipe for deployment to 3.3-dev0
  JenkinsfileDeploy
Labels: ci, prio: important

#1586 [feat] Add support for module collections
  ci-scripts/configs/lmod.py
  ci-scripts/configs/tmod32.py
  ci-scripts/configs/tmod4.py
  ci-scripts/dockerfiles/Lmod.dockerfile
  ci-scripts/dockerfiles/Tmod32.dockerfile
  ci-scripts/dockerfiles/Tmod4.dockerfile
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/config.py
  reframe/core/environments.py
  reframe/core/modules.py
  reframe/core/runtime.py
  reframe/frontend/cli.py
  reframe/frontend/executors/policies.py
  reframe/schemas/config.json
  reframe/utility/osext.py
  unittests/resources/settings.py
  unittests/test_cli.py
  unittests/test_config.py
  unittests/test_environments.py
  unittests/test_modules.py
  unittests/test_schedulers.py
  unittests/test_utility.py
Labels: feature request, prio: important

#1593 [bugfix] Remove duplicate entries in test listing
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: bugfix, prio: important

#1589 [ci] Skip unit tests requiring git if git is not available
  .dockerignore
  ci-scripts/dockerfiles/Lmod.dockerfile
  ci-scripts/dockerfiles/Tmod32.dockerfile
  ci-scripts/dockerfiles/Tmod4.dockerfile
  unittests/test_utility.py
Labels: bugfix, ci, prio: normal

#1590 [test] Update memory bandwidth checks references
  config/cscs.py
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/memory_bandwidth.py
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/p2p_bandwidth.py
Labels: prio: normal, regression test

#1487 [test] Add test for CUDA Fortran
  cscs-checks/prgenv/cuda-fortran/cuda_fortran_check.py
  cscs-checks/prgenv/cuda-fortran/src/vecAdd_cuda.f90
Labels: prio: normal, regression test

#1594 [feat] Make test filtering aware of test dependencies and simply skip the tests in case of unresolved dependencies
  docs/tutorial_deps.rst
  reframe/frontend/check_filters.py
  reframe/frontend/cli.py
  reframe/frontend/dependencies.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/filters.py
  unittests/test_check_filters.py
  unittests/test_dependencies.py
  unittests/test_filters.py
  unittests/test_pipeline.py
  unittests/test_policies.py
Labels: enhancement, prio: normal

#1602 [ci] Migrate unit tests and coverage to Github Actions
  .github/workflows/main.yml
  .travis.yml
  README.md
  setup.py
Labels: ci, prio: normal

#1603 [bugfix] Fix regression when filtering with multiple criteria
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: bugfix, prio: important

#1604 [doc] Fix CI badge URL in README
  README.md
Labels: documentation, prio: important

#1599 [feat] Validate tests after loading them
  reframe/core/pipeline.py
  reframe/frontend/loader.py
  reframe/utility/__init__.py
  unittests/resources/checks/bad/invalid_check.py
  unittests/resources/checks/bad/noentry.py
  unittests/resources/checks/emptycheck.py
  unittests/resources/checks/frontend_checks.py
  unittests/resources/checks_unlisted/good.py
  unittests/test_utility.py
Labels: enhancement, prio: normal

#1598 [test] Add test for Cray module prefix environment variables
  cscs-checks/prgenv/environ_check.py
Labels: prio: normal, regression test

#1570 [feat] Add possibility to inherit the prefix from the parent class
  reframe/core/pipeline.py
  unittests/resources/checks/pinnedcheck.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1605 [doc] Update ReFrame's requirements in the documentation
  docs/started.rst
Labels: documentation, prio: normal

#1601 [feat] Print test dependencies in failure report
  reframe/frontend/cli.py
  reframe/frontend/statistics.py
  reframe/schemas/runreport.json
Labels: enhancement, prio: normal

#1609 [ci] Install and update ca-certificates for ubuntu-based images
  ci-scripts/dockerfiles/Lmod.dockerfile
  ci-scripts/dockerfiles/Tmod4.dockerfile
Labels: ci, prio: important

#1610 [ci] Use 'catchError' Jenkins pipeline step
  Jenkinsfile
Labels: ci, prio: normal

#1608 [bugfix] Properly define default values for the 'modules' and 'variables' configuration parameters of the 'container_platforms'
  reframe/schemas/config.json
Labels: bugfix, prio: important

#1591 [feat] Add support for building tests remotely
  reframe/core/pipeline.py
  reframe/core/schedulers/slurm.py
  unittests/test_pipeline.py
  unittests/test_schedulers.py
Labels: enhancement, prio: normal

#1588 [test] Remove retired systems Kesch and Tiger
  config/cscs-ci.py
  config/cscs.py
  cscs-checks/apps/gromacs/gromacs_check.py
  cscs-checks/compile/haswell_fma_check.py
  cscs-checks/compile/libsci_acc_symlink.py
  cscs-checks/compile/libsci_resolve.py
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/scalapack_compile_run.py
  cscs-checks/libraries/math/trilinos_compile_run.py
  cscs-checks/libraries/petsc/petsc_helloworld.py
  cscs-checks/mch/automatic_arrays_acc.py
  cscs-checks/mch/check_ruby.py
  cscs-checks/mch/collectives_halo.py
  cscs-checks/mch/cuda_stress_test.py
  cscs-checks/mch/fieldextra_check.py
  cscs-checks/mch/g2g_meteoswiss_check.py
  cscs-checks/mch/gpu_direct_acc.py
  cscs-checks/mch/gpu_direct_cuda.py
  cscs-checks/mch/multi_device_openacc.py
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
  cscs-checks/microbenchmarks/cpu/alloc_speed/alloc_speed.py
  cscs-checks/microbenchmarks/cpu/dgemm/dgemm.py
  cscs-checks/microbenchmarks/cpu/fft/fftw_benchmark.py
  cscs-checks/microbenchmarks/cpu/stream/stream.py
  cscs-checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py
  cscs-checks/microbenchmarks/gpu/kernel_latency/kernel_latency.py
  cscs-checks/microbenchmarks/gpu/shmem/shmem.py
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
  cscs-checks/microbenchmarks/mpi/halo_exchange/halo_cell_exchange.py
  cscs-checks/microbenchmarks/mpi/osu/osu_tests.py
  cscs-checks/prgenv/cuda-fortran/cuda_fortran_check.py
  cscs-checks/prgenv/cuda/cuda_aware_mpi.py
  cscs-checks/prgenv/cuda/cuda_memtest_check.py
  cscs-checks/prgenv/cuda/cuda_samples.py
  cscs-checks/prgenv/cuda/nvml_check.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/prgenv/mpi.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/prgenv/opencl_check.py
  cscs-checks/prgenv/ssh_environ_check.py
  cscs-checks/prgenv/ulimit_check.py
  cscs-checks/system/slurm/slurm.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
  cscs-checks/tools/profiling_and_debugging/nvprof.py
Labels: prio: normal, regression test

#1597 [bugfix] List inherited pipeline hooks with the `-L` option
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  unittests/test_pipeline.py
Labels: bugfix, prio: normal

#1612 [refactor] Align implementations of the PBS and the Torque scheduler regarding the use of `qstat`
  reframe/core/backends.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/torque.py
  unittests/test_schedulers.py
Labels: code quality, prio: normal

#1600 [feat] Allow any test attribute to be logged
  docs/config_reference.rst
  reframe/core/logging.py
  unittests/test_logging.py
Labels: feature request, prio: normal

#1606 [feat] Add command-line option to manipulate the module path before executing any tests
  docs/manpage.rst
  reframe/core/modules.py
  reframe/frontend/cli.py
  unittests/test_cli.py
  unittests/test_environments.py
  unittests/test_modules.py
Labels: enhancement, prio: normal

#1619 [bugfix] Fail properly when the source code language cannot be guessed
  reframe/core/buildsystems.py
  unittests/test_buildsystems.py
  unittests/test_pipeline.py
Labels: bugfix, prio: normal

#1622 [ci] Add Github action to check for unused imports
  .github/workflows/main.yml
  reframe/frontend/cli.py
  reframe/frontend/loader.py
Labels: ci, prio: normal

#1625 [feat] Remove deprecated `pre_run`, `post_run`, `prebuild_cmd` and `postbuild_cmd` attributes
  docs/migration_2_to_3.rst
  reframe/core/pipeline.py
Labels: enhancement, prio: normal

#1623 [feat] Allow using colon separated paths with the `--module-path` option
  docs/manpage.rst
  reframe/frontend/cli.py
  unittests/test_buildsystems.py
  unittests/test_cli.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal
