Repository reframe-hpc/reframe, pull requests merged in 2021-06, with the labels that each got.

#1995 [ci] Add required access config for Pilatus
  config/cscs.py
Labels: ci, prio: normal

#1999 [doc] Fix code listings in configuration docs
  docs/configure.rst
Labels: bugfix, documentation, prio: normal

#2003 [ci] Add the codecov upload token to the github action
  .github/workflows/main.yml
Labels: ci, prio: important

#2004 [ci] Use version 1.0.5 of the codecov github action
  .github/workflows/main.yml
Labels: ci, prio: important

#2006 [ci] Revert the change to codecov version
  .github/workflows/main.yml
Labels: ci, prio: important

#2002 [doc] Update figure and text about test execution
  docs/_static/img/reframe-test-cases.svg
  docs/pipeline.rst
Labels: documentation, enhancement, prio: normal

#1993 [test] Update MpiT Check
  cscs-checks/prgenv/mpi_t.py
  cscs-checks/prgenv/src/mpi_t/mpit_categories_7.7.ref
  cscs-checks/prgenv/src/mpi_t/mpit_categories_8.0.ref
  cscs-checks/prgenv/src/mpi_t/mpit_categories_8.1.4.ref
  cscs-checks/prgenv/src/mpi_t/mpit_categories_8.1.5.ref
  cscs-checks/prgenv/src/mpi_t/mpit_control_vars_7.7.ref
  cscs-checks/prgenv/src/mpi_t/mpit_control_vars_8.0.ref
  cscs-checks/prgenv/src/mpi_t/mpit_control_vars_8.1.4.ref
  cscs-checks/prgenv/src/mpi_t/mpit_control_vars_8.1.5.ref
Labels: prio: normal, regression test

#2005 [test] Update cudatoolkit version in GridTools check
  cscs-checks/libraries/gridtools/gridtools_tests.py
Labels: prio: normal, regression test

#2013 [bugfix] Respect default values for module objects in the configuration
  reframe/core/runtime.py
Labels: bugfix, prio: normal

#2015 [test] Fix QE check on Eiger and Pilatus
  cscs-checks/apps/quantumespresso/quantumespresso_check.py
Labels: prio: normal, regression test

#2021 [bugfix] Fix unittests for module collections
  unittests/test_modules.py
Labels: bugfix, ci, prio: important

#2020 [test] Update `cuda-samples` check
  config/cscs.py
  cscs-checks/microbenchmarks/gpu/hooks.py
  cscs-checks/prgenv/cuda/cuda_aware_mpi.py
  cscs-checks/prgenv/cuda/cuda_samples.py
Labels: prio: normal, regression test

#2025 Update config/cscs.py for PrgEnv-nvidia
  config/cscs.py
Labels: prio: important, regression test

#2027 [bugfix] Fix deep-copy of `_Undefined` constant
  reframe/core/buildsystems.py
Labels: bugfix, prio: normal

#2035 [test] Update affinity and stream checks
  cscs-checks/microbenchmarks/cpu/stream/stream.py
  cscs-checks/prgenv/affinity_check.py
Labels: prio: normal, regression test

#2026 [test] Update checkout version of the `cuda-samples` repo
  cscs-checks/microbenchmarks/gpu/hooks.py
  cscs-checks/prgenv/cuda/cuda_samples.py
Labels: bugfix, regression test

#2012 [bugfix] Restrict use of `required` keyword
  reframe/core/meta.py
  reframe/core/variables.py
  unittests/test_meta.py
  unittests/test_variables.py
Labels: bugfix, prio: normal

#2037 [test] Bugfix `cuda_aware_mpi_check`
  cscs-checks/prgenv/cuda/cuda_aware_mpi.py
Labels: prio: normal, regression test

#2041 [config] Remove PrgEnv-nvidia from eiger config
  config/cscs.py
Labels: ci, prio: important

#2042 [test] Add `PrgEnv-nvidia` support to `cuda_stress_test`
  cscs-checks/mch/cuda_stress_test.py
Labels: prio: normal, regression test

#2034 [test] Update automatic_arrays_acc
  cscs-checks/mch/automatic_arrays_acc.py
Labels: prio: normal, regression test

#2040 [test] Update OSU benchmark to include prgenv nvidia
  cscs-checks/microbenchmarks/mpi/osu/osu_tests.py
Labels: regression test

#2023 [test] Add PrgEnv-nvidia to the mpi, tools and ulimit tests
  cscs-checks/prgenv/mpi.py
  cscs-checks/prgenv/mpi_t.py
  cscs-checks/prgenv/src/mpi_t/ref/mpit_categories_7.7.ref
  cscs-checks/prgenv/src/mpi_t/ref/mpit_categories_8.0.ref
  cscs-checks/prgenv/src/mpi_t/ref/mpit_categories_8.1.4.ref
  cscs-checks/prgenv/src/mpi_t/ref/mpit_categories_8.1.5.ref
  cscs-checks/prgenv/src/mpi_t/ref/mpit_control_vars_7.7.ref
  cscs-checks/prgenv/src/mpi_t/ref/mpit_control_vars_8.0.ref
  cscs-checks/prgenv/src/mpi_t/ref/mpit_control_vars_8.1.4.ref
  cscs-checks/prgenv/src/mpi_t/ref/mpit_control_vars_8.1.5.ref
  cscs-checks/prgenv/ulimit_check.py
  cscs-checks/tools/profiling_and_debugging/notool.py
Labels: prio: normal, regression test
