Repository reframe-hpc/reframe, pull requests merged in 2021-01, with the labels that each got.

#1670 [bugfix] Revert feature to preserve symbolic links in sources directory since it can lead to dangling links in the stage directory; users should use `readonly_files` instead
  cscs-checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py
  cscs-checks/microbenchmarks/gpu/kernel_latency/kernel_latency.py
  cscs-checks/microbenchmarks/gpu/shmem/shmem.py
  reframe/core/pipeline.py
  unittests/resources/checks/src/hello.sh.link
  unittests/test_pipeline.py
Labels: bugfix, prio: normal

#1669 [doc] Add DOI for the latest released version to the README
  README.md
  setup.py
Labels: documentation, prio: normal

#1674 [test] Cleanup cray_cdt_version in TensorFlow test
  cscs-checks/apps/tensorflow/tf2_horovod_check.py
Labels: prio: normal, regression test

#1673 [bugfix] Fix numbering of failed tasks when reframe execution is aborted
  reframe/frontend/executors/policies.py
Labels: bugfix, prio: normal

#1677 [feat] Support CUDA Fortran file extensions in SingleSource
  cscs-checks/prgenv/cuda-fortran/cuda_fortran_check.py
  cscs-checks/prgenv/cuda-fortran/src/vecAdd_cuda.cuf
  reframe/core/buildsystems.py
Labels: enhancement, prio: normal, regression test

#1681 [config] Fix names of jupyter reservations in configuration
  config/cscs.py
Labels: bugfix, prio: normal

#1678 [test] Add basic hostname check for the `xfer` partition
  config/cscs.py
  cscs-checks/system/slurm/slurm.py
Labels: prio: normal, regression test

#1675 [test] Add PyTorch Horovod test
  cscs-checks/apps/pytorch/pytorch_horovod_check.py
Labels: prio: normal, regression test

#1683 [test] Fix tests on dom requiring cdt-cuda
  cscs-checks/mch/collectives_halo.py
  cscs-checks/mch/cuda_stress_test.py
  cscs-checks/mch/gpu_direct_cuda.py
  cscs-checks/prgenv/cuda/cuda_aware_mpi.py
  cscs-checks/prgenv/cuda/cuda_samples.py
  cscs-checks/tools/profiling_and_debugging/cuda_gdb.py
  cscs-checks/tools/profiling_and_debugging/notool.py
  cscs-checks/tools/profiling_and_debugging/nvprof.py
Labels: prio: normal, regression test

#1688 [ci] Use Github Action for uploading ReFrame releases on PyPI
  .github/workflows/publish.yml
  ci-scripts/deploy.sh
Labels: ci, prio: normal

#1686 [test] Fix energy reference value and difference of QE small
  cscs-checks/apps/quantumespresso/quantumespresso_check.py
Labels: prio: normal, regression test

#1689 [test] Update version of the Horovod module
  cscs-checks/apps/jupyter/check_ipcmagic.py
  cscs-checks/apps/tensorflow/tf2_horovod_check.py
Labels: prio: normal, regression test

#1680 [refactor] Remove fieldname argument from the field validators
  reframe/core/buildsystems.py
  reframe/core/containers.py
  reframe/core/environments.py
  reframe/core/fields.py
  reframe/core/launchers/__init__.py
  reframe/core/modules.py
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  unittests/test_fields.py
Labels: code quality, enhancement, prio: normal

#1696 [test] Remove HPCG test workaround for unsupported OpenMP pragma
  cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
Labels: prio: normal, regression test

#1694 [test] Load cdt-cuda in dom for GPU checks
  cscs-checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py
  cscs-checks/microbenchmarks/gpu/kernel_latency/kernel_latency.py
  cscs-checks/microbenchmarks/gpu/memory_bandwidth/memory_bandwidth.py
  cscs-checks/microbenchmarks/gpu/shmem/shmem.py
Labels: prio: normal, regression test

#1614 [feat] Introduce new syntax for allowing the creation of extensible parametrised tests
  .gitignore
  docs/regression_test_api.rst
  reframe/core/decorators.py
  reframe/core/meta.py
  reframe/core/parameters.py
  reframe/core/pipeline.py
  unittests/test_parameters.py
Labels: enhancement, prio: normal

#1695 [feat] Add sanity function equivalents of some of `os.path` functions
  reframe/utility/sanity.py
  unittests/test_sanity_functions.py
Labels: enhancement, prio: normal

#1697 [test] Put back import that registers magic command
  cscs-checks/apps/jupyter/src/tf-hvd-sgd-ipc-tf2.py
Labels: prio: normal, regression test

#1698 [bugfix] Fix sanity function `print` to accept a single object only
  reframe/utility/sanity.py
  unittests/test_sanity_functions.py
Labels: bugfix, prio: normal

#1701 [bugfix] Ensure that job options passed from the command-line are always the last in the generated job script
  reframe/core/launchers/mpi.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  unittests/test_launchers.py
Labels: bugfix, prio: important

#1707 [test] Remove the 'analytics' regression tests
  cscs-checks/analytics/spark/spark_check.py
  cscs-checks/analytics/spark/src/spark_pi.py
Labels: code quality, prio: normal

#1706 [bugfix] Correct the advisory rerun message on test failures
  reframe/frontend/statistics.py
Labels: bugfix, prio: normal

#1702 [test] Simply set job options in tests; do not append if not needed
  cscs-checks/system/slurm/slurm.py
Labels: enhancement, regression test

#1710 [doc] Enhance documentation about performance log directories
  docs/configure.rst
Labels: documentation, enhancement, prio: normal

#1712 [test] Update Cray variable test for cdt/20.11
  cscs-checks/prgenv/environ_check.py
Labels: prio: normal, regression test

#1714 [bugfix] Skip test cases recursively in case of dangling dependencies
  reframe/frontend/dependencies.py
Labels: bugfix, prio: important

#1715 [bugfix] Fix cdt version condition
  cscs-checks/prgenv/environ_check.py
Labels: bugfix, prio: normal

#1713 [test] Port JacobiNoToolHybrid check to Alps
  cscs-checks/tools/profiling_and_debugging/notool.py
  cscs-checks/tools/profiling_and_debugging/src/F90/Makefile
Labels: prio: normal, regression test

#1682 [test] Add Eiger system to NAMD check
  cscs-checks/apps/namd/namd_check.py
Labels: prio: normal, regression test

#1711 [test] Add Empirical Roofline Toolkit (gpu) check
  cscs-checks/microbenchmarks/gpu/roofline/berkeley-ert-gpu.py
Labels: prio: normal, regression test

#1716 [feat] Set executable bit in generated job script files
  reframe/core/schedulers/local.py
  reframe/core/shell.py
  unittests/test_shell.py
Labels: enhancement, prio: normal

#1676 [feat] Add `--maxfail` option to stop execution after a certain number of failures
  config/cscs-ci.py
  docs/manpage.rst
  reframe/core/exceptions.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  reframe/frontend/runreport.py
  reframe/frontend/statistics.py
  reframe/schemas/runreport.json
  unittests/test_cli.py
  unittests/test_policies.py
  unittests/test_utility.py
Labels: enhancement, prio: normal

#1718 [bugfix] Fix handling of single character scheduler backend options passed through `-J`
  docs/manpage.rst
  reframe/frontend/cli.py
Labels: bugfix, prio: normal

#1722 [bugfix] Fix parameter value specification in the `parameter()` directive
  docs/regression_test_api.rst
  reframe/core/parameters.py
  unittests/test_parameters.py
Labels: bugfix, prio: important
