Repository reframe-hpc/reframe, pull requests merged in 2021-05, with the labels that each got.

#1925 [feat] Add command-line option to generate a JUnit XML report
  docs/config_reference.rst
  docs/manpage.rst
  reframe/frontend/cli.py
  reframe/frontend/runreport.py
  reframe/frontend/statistics.py
  reframe/schemas/config.json
  reframe/schemas/junit.xsd
  requirements.txt
  setup.py
  unittests/test_policies.py
Labels: enhancement, prio: normal

#1961 [bugfix] Fixes `find_modules()` behaviour with flat module scheme when an environment is a substring of another one
  reframe/utility/__init__.py
Labels: bugfix, prio: normal

#1958 [test] Modernize Scalapack test
  cscs-checks/libraries/math/scalapack_compile_run.py
Labels: prio: normal, regression test

#1965 [feat] Support test retries in the JUnit report
  docs/manpage.rst
  reframe/frontend/runreport.py
Labels: enhancement, prio: normal

#1964 [feat] Add new logging handler for sending test data in JSON to an HTTP server
  config/cscs.py
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/logging.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
Labels: enhancement, prio: normal

#1968 [config] Remove Graylog handler from CSCS config
  config/cscs.py
Labels: ci, prio: normal

#1971 [bugfix] Fix error checking of module commands in the class Tmod backends
  reframe/core/modules.py
  unittests/modules/testmod_bar
Labels: bugfix, prio: normal

#1966 [test] Remove VC test
  cscs-checks/microbenchmarks/cpu/simd/vc.py
Labels: prio: normal

#1944 [bugfix] Mark jobs properly as completed in PBS scheduler
  reframe/core/schedulers/pbs.py
Labels: bugfix, prio: normal

#1972 [bugfix] Generate run reports per test with `--ci-generate`
  docs/manpage.rst
  reframe/frontend/ci.py
  reframe/frontend/cli.py
  reframe/frontend/runreport.py
  unittests/test_policies.py
Labels: bugfix, prio: important

#1976 [doc] Use PNG logo for compatibility with all browsers
  docs/_static/img/reframe-logo-dark-bg.png
  docs/_static/img/reframe-logo-dark-bg.svg
  docs/conf.py
  docs/config_reference.rst
Labels: bugfix, documentation, prio: normal

#1950 [test] Update checks for Eiger with PE 21.04
  config/cscs.py
  cscs-checks/apps/cp2k/cp2k_check.py
  cscs-checks/apps/gromacs/gromacs_check.py
  cscs-checks/apps/lammps/lammps_check.py
  cscs-checks/apps/namd/namd_check.py
  cscs-checks/apps/paraview/paraview_check.py
  cscs-checks/apps/quantumespresso/quantumespresso_check.py
  cscs-checks/apps/vasp/vasp_check.py
  cscs-checks/libraries/boost/boost_python_check.py
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/libraries/math/scalapack_compile_run.py
  cscs-checks/microbenchmarks/cpu/alloc_speed/alloc_speed.py
  cscs-checks/microbenchmarks/cpu/dgemm/dgemm.py
  cscs-checks/microbenchmarks/cpu/strided_bandwidth/strides.py
  cscs-checks/microbenchmarks/mpi/halo_exchange/halo_cell_exchange.py
  cscs-checks/microbenchmarks/mpi/osu/osu_tests.py
  cscs-checks/prgenv/environ_check.py
  cscs-checks/prgenv/helloworld.py
  cscs-checks/prgenv/mpi.py
  cscs-checks/prgenv/mpi_t.py
  cscs-checks/prgenv/src/mpi_t/mpit_categories_34a2.ref
  cscs-checks/prgenv/src/mpi_t/mpit_control_vars_34a2.ref
  cscs-checks/prgenv/ulimit_check.py
  cscs-checks/system/io/ior_check.py
  cscs-checks/system/slurm/slurm.py
  cscs-checks/tools/io/cdo.py
  cscs-checks/tools/io/nco.py
  cscs-checks/tools/profiling_and_debugging/notool.py
Labels: prio: normal, regression test

#1978 [test] Correct the cudatoolkit version loaded for CUDA Fortran
  cscs-checks/prgenv/cuda-fortran/cuda_fortran_check.py
Labels: prio: important, regression test

#1871 [feat] Add a new build system backend for building test code with Spack
  reframe/core/buildsystems.py
  reframe/core/pipeline.py
  unittests/test_buildsystems.py
Labels: enhancement, prio: normal

#1984 [code quality] Test that stagedir is mounted inside container
  unittests/test_pipeline.py
Labels: code quality, prio: normal

#1986 [feat] Remove deprecated features from 4.x
  reframe/core/containers.py
  reframe/core/pipeline.py
  reframe/core/systems.py
  unittests/test_containers.py
Labels: 4.x, enhancement, prio: normal

#1979 [test] Optimize affinity check
  cscs-checks/prgenv/affinity_check.py
Labels: prio: normal, regression test

#1988 [bugfix] Fix variable and parameter access as class attributes
  reframe/core/meta.py
  reframe/core/variables.py
  unittests/test_parameters.py
  unittests/test_variables.py
Labels: bugfix, prio: normal

#1992 [packaging] Add docutils 0.16 for sphinx-rtd-theme compatibility
  docs/requirements.txt
Labels: bugfix, packaging

#1975 [test] Add test for JobReport
  cscs-checks/system/jobreport/gpu_report.py
Labels: prio: normal, regression test

#1994 [packaging] Disable the pip user installation scheme in bootstrap
  bootstrap.sh
Labels: bugfix, packaging, prio: normal
