Repository reframe-hpc/reframe, pull requests merged in 2021-04, with the labels that each got.

#1905 [packaging] Bump versions of requirements
  docs/requirements.txt
  requirements.txt
Labels: packaging, prio: normal

#1904 [bugfix] Fix rescheduling condition for asynchronous execution policy
  reframe/frontend/executors/policies.py
Labels: bugfix, prio: normal

#1902 [test] Fix cudatoolkit version for Cuda-Fortran check on dom
  cscs-checks/prgenv/cuda-fortran/cuda_fortran_check.py
Labels: prio: normal, regression test

#1907 [bugfix] Fix squeue backend scheduler crash
  reframe/core/schedulers/slurm.py
Labels: bugfix, prio: important

#1895 [doc] Add tutorial about reusable tests
  docs/tutorial_advanced.rst
  tutorials/advanced/library/lib/__init__.py
  tutorials/advanced/library/lib/src/get_os_release.sh
  tutorials/advanced/library/usr/container_test.py
Labels: documentation, prio: normal

#1891 [bugfix] Fix missing path to build stdout when collecting EasyBuild installed modules
  reframe/core/buildsystems.py
  reframe/core/pipeline.py
Labels: bugfix, prio: normal

#1910 [bugfix] Fix crash when `sourcesdir` is set to `None` in class body
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: bugfix, prio: normal

#1888 [feat] Improve error message when parameters are undefined
  reframe/core/decorators.py
  reframe/core/meta.py
  unittests/test_parameters.py
Labels: code quality, prio: normal

#1870 [doc] Add `-pthread` to the multithreaded tutorial test
  docs/tutorial_basics.rst
  tutorials/basics/hellomp/hellomp1.py
  tutorials/basics/hellomp/hellomp2.py
  tutorials/basics/hellomp/hellomp3.py
Labels: documentation, prio: normal

#1865 [feat] Re-implement pipeline hook mechanism and add a post-init hook
  docs/regression_test_api.rst
  reframe/core/decorators.py
  reframe/core/hooks.py
  reframe/core/meta.py
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  reframe/utility/__init__.py
  unittests/test_ci.py
  unittests/test_cli.py
  unittests/test_dependencies.py
  unittests/test_logging.py
  unittests/test_pipeline.py
  unittests/test_policies.py
  unittests/test_schedulers.py
  unittests/test_utility.py
Labels: code quality, enhancement, prio: normal

#1922 [doc] Add URL to Twitter badge
  README.md
Labels: documentation, prio: normal

#1926 [bugfix] Fix crash when `OSError` occurs during dumping of test cases
  reframe/frontend/executors/__init__.py
Labels: bugfix, prio: normal

#1924 [doc] Change favicon to the ReFrame logo
  docs/_static/img/favicon.png
Labels: documentation, prio: normal

#1923 [refactor] Consolidate unit test fixtures and other refactoring of unit tests
  test_reframe.py
  unittests/conftest.py
  unittests/resources/checks/bad/notacheck.py
  unittests/resources/checks/bad/relative_imports.py
  unittests/resources/checks/frontend_checks.py
  unittests/test_argparser.py
  unittests/test_buildsystems.py
  unittests/test_cli.py
  unittests/test_config.py
  unittests/test_dependencies.py
  unittests/test_environments.py
  unittests/test_fields.py
  unittests/test_loader.py
  unittests/test_logging.py
  unittests/test_modules.py
  unittests/test_pipeline.py
  unittests/test_policies.py
  unittests/test_sanity_functions.py
  unittests/test_schedulers.py
  unittests/test_utility.py
  unittests/test_variables.py
  unittests/test_warnings.py
  unittests/utility.py
Labels: code quality, enhancement, prio: normal

#1795 [test] Add Slurm response sanity tests
  cscs-checks/system/slurm/slurm.py
Labels: prio: normal, regression test

#1909 [ci] Pull base images for CI instead of building them from scratch
  ci-scripts/dockerfiles/Lmod-base.dockerfile
  ci-scripts/dockerfiles/Lmod.dockerfile
  ci-scripts/dockerfiles/Lmod77-base.dockerfile
  ci-scripts/dockerfiles/Lmod77.dockerfile
  ci-scripts/dockerfiles/Tmod32-base.dockerfile
  ci-scripts/dockerfiles/Tmod32.dockerfile
  ci-scripts/dockerfiles/Tmod4-base.dockerfile
  ci-scripts/dockerfiles/Tmod4.dockerfile
Labels: ci, prio: normal

#1932 [doc] Make basic configuration example more intuitive w.r.t. to modules systems
  docs/configure.rst
  docs/tutorial_advanced.rst
  docs/tutorial_basics.rst
  tutorials/config/settings.py
Labels: documentation, enhancement

#1840 [test] Sanity jupyter tests
  cscs-checks/tools/jupyter/jupyter_tests.py
Labels: prio: normal, regression test

#1912 [feat] Abbreviate node lists in `FAILURE INFO` reports
  reframe/frontend/statistics.py
  reframe/utility/__init__.py
  unittests/test_utility.py
Labels: enhancement, prio: normal

#1933 [feat] Issue a warning if a module operation is attempted on the `nomod` modules system
  reframe/core/logging.py
  reframe/core/modules.py
  unittests/test_logging.py
Labels: enhancement, prio: normal

#1934 [feat] Deprecate the use of the `@parameterized_test` decorator
  reframe/core/decorators.py
  reframe/frontend/loader.py
  reframe/utility/__init__.py
  unittests/resources/checks_unlisted/deps_simple.py
  unittests/resources/checks_unlisted/good.py
  unittests/test_dependencies.py
  unittests/test_loader.py
  unittests/test_parameters.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#1931 [test] Add workaround for PGI on Tsa
  cscs-checks/mch/gpu_direct_cuda.py
  cscs-checks/system/openstack/src/s3_download_large_object.py
  cscs-checks/system/openstack/src/tools.py
Labels: prio: normal, regression test

#1920 [test] Add Likwid test to the health suite
  cscs-checks/microbenchmarks/cpu/likwid/likwid.py
Labels: prio: normal, regression test

#1939 [ci] Remove module collections from Alps config
  config/cscs.py
Labels: ci, prio: normal

#1941 [feat] Add a configuration option to disable automatic module conflict resolution
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/runtime.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
  unittests/test_environments.py
Labels: enhancement, prio: normal

#1945 [feat] Add a `--list-tags` command-line action to list all the available test tags
  docs/manpage.rst
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: enhancement, prio: normal

#1880 [test] Add PrgEnv checks for HIP
  cscs-checks/prgenv/hip/build_hip.py
Labels: prio: normal, regression test

#1940 [doc] Update documentation of built-ins and update tutorial examples removing the use of `__init__`
  docs/dependencies.rst
  docs/regression_test_api.rst
  docs/tutorial_advanced.rst
  docs/tutorial_basics.rst
  docs/tutorial_deps.rst
  docs/tutorial_tips_tricks.rst
  reframe/utility/__init__.py
  tutorials/advanced/affinity/affinity.py
  tutorials/advanced/containers/container_test.py
  tutorials/advanced/flexnodes/flextest.py
  tutorials/advanced/jobopts/eatmemory.py
  tutorials/advanced/makefiles/maketest.py
  tutorials/advanced/makefiles/maketest_mixin.py
  tutorials/advanced/multilaunch/multilaunch.py
  tutorials/advanced/parameterized/stream.py
  tutorials/advanced/random/prepostrun.py
  tutorials/advanced/random/randint.py
  tutorials/advanced/runonly/echorand.py
  tutorials/basics/hello/hello1.py
  tutorials/basics/hello/hello2.py
  tutorials/basics/hellomp/hellomp1.py
  tutorials/basics/hellomp/hellomp2.py
  tutorials/basics/hellomp/hellomp3.py
  tutorials/basics/stream/stream1.py
  tutorials/basics/stream/stream2.py
  tutorials/basics/stream/stream3.py
  tutorials/deps/osu_benchmarks.py
Labels: documentation, enhancement, prio: normal

#1951 [feat] Drop the `@parameterized_test` decorator
  reframe/core/decorators.py
  unittests/test_parameters.py
Labels: 4.x, enhancement, prio: normal

#1953 [bugfix] Properly check exit status of `ensurepip` in `bootstrap.sh`
  bootstrap.sh
Labels: bugfix, packaging, prio: normal

#1949 [bugfix] Warn when a check search path does not exist
  reframe/frontend/loader.py
Labels: bugfix, prio: normal

#1956 [bugfix] Fix regression in setting the graylog server address
  reframe/frontend/cli.py
Labels: bugfix, prio: important

#1946 [packaging] Bump versions of dependencies
  docs/requirements.txt
  requirements.txt
Labels: packaging, prio: normal

#1957 [test] Specify the ipcmagic version currently working with jupyterlab
  cscs-checks/apps/jupyter/check_ipcmagic.py
Labels: prio: normal, regression test
