Repository reframe-hpc/reframe, pull requests merged in 2021-07, with the labels that each got.

#2007 [feat] Add `sanity_function` and `deferrable` builtins
  cscs-checks/system/jobreport/gpu_report.py
  docs/deferrable_functions_reference.rst
  docs/deferrables.rst
  docs/programming_apis.rst
  docs/regression_test_api.rst
  docs/sanity_functions_reference.rst
  docs/tutorial_basics.rst
  docs/tutorial_tips_tricks.rst
  hpctestlib/microbenchmarks/gpu/dgemm/__init__.py
  hpctestlib/microbenchmarks/gpu/gpu_burn/__init__.py
  hpctestlib/microbenchmarks/gpu/kernel_latency/__init__.py
  hpctestlib/microbenchmarks/gpu/memory_bandwidth/__init__.py
  hpctestlib/microbenchmarks/gpu/pointer_chase/__init__.py
  hpctestlib/microbenchmarks/gpu/shmem/__init__.py
  reframe/core/meta.py
  reframe/core/pipeline.py
  reframe/utility/sanity.py
  unittests/test_meta.py
  unittests/test_pipeline.py
Labels: enhancement, prio: normal

#2032 [test] Update `openacc_cuda_mpi_cppstd` check
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
Labels: prio: normal, regression test

#2047 [bugfix] Hide data-descriptors from `variable` attributes
  reframe/core/meta.py
  reframe/core/variables.py
  unittests/test_meta.py
  unittests/test_variables.py
Labels: bugfix, prio: normal

#2024 [test] Add support to PrgEnv-nvidia in various tests
  cscs-checks/compile/libsci_resolve.py
  cscs-checks/libraries/io/hdf5_compile_run.py
  cscs-checks/libraries/io/netcdf_compile_run.py
  cscs-checks/microbenchmarks/gpu/kernel_latency/kernel_latency.py
  cscs-checks/prgenv/cpu_target_check.py
  cscs-checks/prgenv/cuda-fortran/cuda_fortran_check.py
  cscs-checks/prgenv/environ_check.py
  cscs-checks/prgenv/openacc_checks.py
  cscs-checks/prgenv/opencl_check.py
Labels: prio: normal, regression test

#2039 [test] Update `haswell_fma_check`
  cscs-checks/compile/haswell_fma_check.py
Labels: prio: normal, regression test

#2049 [test] Update `gpu_direct_acc`
  cscs-checks/mch/gpu_direct_acc.py
Labels: prio: normal, regression test

#2050 [test] Update `openacc_cuda_mpi_cppstd`
  cscs-checks/mch/openacc_cuda_mpi_cppstd.py
Labels: prio: normal, regression test

#2052 [bugfix] Increase timeout for `test_git_repo_exists` unittest
  unittests/test_utility.py
Labels: bugfix, prio: normal

#2053 [config] Add container platforms to eiger/pilatus config
  config/cscs.py
Labels: prio: normal

#2054 [test] Update nvidia gpu direct acc
  cscs-checks/mch/gpu_direct_acc.py
Labels: prio: normal, regression test

#2051 [packaging] Add `--no-deps` option to ignore dependency conflicts when bootstrapping
  bootstrap.sh
Labels: enhancement, packaging, prio: normal

#2029 [test] Add PrgEnv-nvidia to halo_cell_exchange check
  cscs-checks/microbenchmarks/mpi/halo_exchange/halo_cell_exchange.py
Labels: prio: normal, regression test

#2018 [test] Update Amber test to new syntax and add support for Eiger and Pilatus
  cscs-checks/apps/amber/amber_check.py
Labels: prio: normal, regression test

#2056 [test] Remove `spec-accel` check
  cscs-checks/microbenchmarks/gpu/spec-accel/spec.py
  cscs-checks/microbenchmarks/gpu/spec-accel/src/cscs-cray
  cscs-checks/microbenchmarks/gpu/spec-accel/src/cscs-gnu
  cscs-checks/microbenchmarks/gpu/spec-accel/src/cscs-pgi
Labels: prio: normal, regression test

#2048 [bugfix] Fix pipeline hook override
  docs/regression_test_api.rst
  reframe/core/hooks.py
  reframe/core/meta.py
  unittests/test_meta.py
Labels: bugfix, prio: normal

#2060 [bugfix] Remove `PrgEnv-nvidia` from Pilatus environs
  config/cscs.py
Labels: bugfix

#2063 [bugfix] Add account and constraint to Eiger configuration
  config/cscs.py
Labels: prio: important

#1991 [feat] Auto-detect cpu topology
  docs/config_reference.rst
  docs/configure.rst
  docs/manpage.rst
  docs/requirements.txt
  reframe/core/config.py
  reframe/core/systems.py
  reframe/frontend/autodetect.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
  reframe/utility/cpuinfo.py
  reframe/utility/osext.py
  requirements.txt
  setup.py
  unittests/test_autodetect.py
  unittests/test_cli.py
Labels: enhancement, prio: normal

#2058 [feat] Expose `@final` decorator in the class body
  reframe/core/meta.py
  reframe/core/pipeline.py
  unittests/test_loader.py
  unittests/test_meta.py
Labels: code quality, prio: normal

#2059 [bugfix] Fix `TypeError` in logger when using tuples as dict keys
  reframe/utility/jsonext.py
  unittests/test_utility.py
Labels: bugfix, prio: normal

#2068 [ci] Serialize unit tests everywhere
  ci-scripts/ci-runner.bash
Labels: ci, enhancement, prio: normal

#2046 [feat] Make the `@required_version` decorator a class definition parameter
  reframe/core/decorators.py
  reframe/core/pipeline.py
  unittests/test_loader.py
Labels: enhancement, prio: normal

#1989 [doc] Add tutorial to showcase the use of build automation tools through ReFrame
  ci-scripts/ci-runner.bash
  docs/tutorial_build_automation.rst
  docs/tutorials.rst
  reframe/core/buildsystems.py
  reframe/frontend/cli.py
  tutorials/build_systems/easybuild/eb_test.py
  tutorials/build_systems/spack/spack_test.py
  tutorials/build_systems/spack/src/myenv/spack.yaml
Labels: documentation, enhancement, prio: normal

#2016 [feat] Print the run report location at the end of a session
  reframe/frontend/cli.py
Labels: enhancement, prio: normal

#2071 [ci] Remove `sn.sanity_function` references from unit tests
  unittests/resources/checks_unlisted/deps_complex.py
  unittests/test_deferrable.py
  unittests/test_logging.py
  unittests/test_pipeline.py
  unittests/test_sanity_functions.py
Labels: ci, prio: normal

#2073 [ci] Don't fail the CI if a cleanup stage fails
  Jenkinsfile
Labels: ci, prio: normal

#2074 [bugfix] Always use `$HOME` for storing processor auto-detection results
  reframe/frontend/autodetect.py
  unittests/test_autodetect.py
  unittests/test_cli.py
Labels: bugfix, prio: important

#2079 [doc] Fix documentation about processor auto-detection
  docs/configure.rst
Labels: documentation, prio: normal

#2080 [ci] Fix sanity function deprecation unit test
  unittests/test_deferrable.py
Labels: prio: important, prio: normal

#2086 [bugfix] Fix the way a custom Python binary is passed to the bootstrap script
  bootstrap.sh
Labels: bugfix, prio: important

#2076 [test] Modernise IOR checks
  cscs-checks/system/io/ior_check.py
Labels: prio: normal, regression test

#2090 [packaging] Build ReFrame using `pyproject.toml` and `setup.cfg`
  .github/workflows/main.yml
  .github/workflows/publish.yml
  pyproject.toml
  setup.cfg
  setup.py
Labels: packaging, prio: normal

#2092 [bugfix] Remove redundant whitespace in local launcher's command
  reframe/core/pipeline.py
Labels: bugfix, prio: normal

#2081 [bugfix] Fix hook override with multiple inheritance
  reframe/core/hooks.py
  reframe/core/meta.py
  reframe/core/pipeline.py
  unittests/test_meta.py
  unittests/test_pipeline.py
Labels: bugfix, code quality, prio: normal

#2091 [bugfix] Remove unnecessary file locks
  reframe/frontend/autodetect.py
  reframe/utility/osext.py
Labels: bugfix, prio: normal

#2089 [test] Add Jupyter tests for Eiger
  config/cscs.py
  cscs-checks/tools/jupyter/jupyter_tests.py
Labels: regression test

#1959 [feat] Add SGE scheduler backend
  docs/config_reference.rst
  reframe/core/backends.py
  reframe/core/schedulers/registry.py
  reframe/core/schedulers/sge.py
  reframe/schemas/config.json
  unittests/test_schedulers.py
Labels: enhancement, prio: normal

#2096 [feat] Remove deprecated features for 4.x
  docs/deferrable_functions_reference.rst
  docs/regression_test_api.rst
  reframe/core/decorators.py
  reframe/core/launchers/__init__.py
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/utility/__init__.py
  reframe/utility/sanity.py
  reframe/utility/versioning.py
  unittests/resources/checks_unlisted/no_required_version.py
  unittests/test_deferrable.py
  unittests/test_dependencies.py
  unittests/test_loader.py
  unittests/test_versioning.py
Labels: 4.x, enhancement, prio: normal

#2101 [test] Test `HIP` build on the `main` branch
  cscs-checks/prgenv/hip/build_hip.py
Labels: prio: normal, regression test

#2094 [bugfix] Do not emit `module unuse <path>` after loading modules with Lmod from a specific path
  reframe/core/modules.py
  unittests/test_modules.py
Labels: bugfix, prio: normal

#2098 [bugfix] Handle `None` in `Decimal` conversion of junit report
  reframe/frontend/runreport.py
  unittests/test_policies.py
Labels: bugfix, prio: normal

#2087 [feat] Improve handling of user programming errors
  docs/config_reference.rst
  docs/manpage.rst
  docs/tutorial_tips_tricks.rst
  reframe/core/decorators.py
  reframe/core/exceptions.py
  reframe/core/meta.py
  reframe/core/namespaces.py
  reframe/core/parameters.py
  reframe/core/variables.py
  reframe/core/warnings.py
  reframe/frontend/cli.py
  reframe/frontend/loader.py
  unittests/resources/checks/bad/abstract_check.py
  unittests/test_cli.py
  unittests/test_loader.py
  unittests/test_parameters.py
  unittests/test_pipeline.py
  unittests/test_policies.py
  unittests/test_variables.py
Labels: enhancement, prio: normal
