Repository reframe-hpc/reframe, pull requests merged in 2022-03, with the labels that each got.

#2450 [config] Use new naming scheme in CSCS config
  config/cscs-ci.py
  config/cscs.py
Labels: prio: normal, enhancement

#2457 [ci] Update checkout and setup-python versions for GH actions
  .github/workflows/main.yml
  .github/workflows/publish.yml
Labels: prio: normal, ci-integration

#2456 [test] Fix reference assignment in LAMMPS checks
  cscs-checks/apps/lammps/lammps_check.py
Labels: prio: important, regression test

#2455 [test] Update `AllocSpeedTest` performance reference on Dom and Piz Daint
  cscs-checks/microbenchmarks/cpu/alloc_speed/alloc_speed.py
Labels: prio: normal, regression test

#2462 [testlib] Make `bench_name` loggable in Gromacs library test
  hpctestlib/sciapps/gromacs/benchmarks.py
Labels: prio: normal, test library

#2463 [feat] Extend the public API of `Job`
  reframe/core/launchers/mpi.py
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/lsf.py
  reframe/core/schedulers/slurm.py
  unittests/test_launchers.py
  unittests/test_schedulers.py
Labels: prio: normal, code quality, documentation, enhancement

#2454 [test] Update VASP checks and reference values
  cscs-checks/apps/vasp/vasp_check.py
Labels: prio: normal, regression test

#2468 [test] Update reference values for large NAMD test on cpu
  cscs-checks/apps/namd/namd_check.py
Labels: prio: normal, regression test

#2469 [test] Update CPMD check
  cscs-checks/apps/cpmd/cpmd_check.py
Labels: prio: normal, regression test

#2472 [feat] Add display name to the failure statistics
  reframe/frontend/statistics.py
Labels: prio: normal, enhancement

#2471 [bugfix] Make rerun prompt consistent with the new naming scheme
  reframe/frontend/statistics.py
Labels: prio: normal, bugfix

#2470 [refactor] Move builtins in a separate module file and improve `make_test()`
  docs/regression_test_api.rst
  reframe/core/builtins.py
  reframe/core/deferrable.py
  reframe/core/fixtures.py
  reframe/core/hooks.py
  reframe/core/meta.py
  reframe/core/parameters.py
  reframe/core/variables.py
  unittests/test_pipeline.py
Labels: prio: normal, code quality, documentation, enhancement, test syntax

#2475 [test] Temporary fix for CPMD
  cscs-checks/apps/cpmd/cpmd_check.py
Labels: prio: normal, regression test

#2474 [refactor] Refactor fixture instantiation
  reframe/core/decorators.py
  reframe/frontend/loader.py
Labels: prio: normal, code quality

#2476 [bugfix] Fix regression with tests that treat stdin as a tty
  reframe/utility/osext.py
Labels: prio: important, bugfix

#2482 [bugfix] Treat empty source code context when reporting errors
  reframe/core/exceptions.py
Labels: prio: normal, bugfix

#2345 [testlib] Time the warmup phase and print minimum required duration in the GPU burn test
  hpctestlib/microbenchmarks/gpu/gpu_burn/src/gpu_burn.cu
Labels: enhancement, test library

#2484 [feat] Support early access to fixtures
  reframe/core/fixtures.py
  reframe/core/meta.py
  reframe/core/pipeline.py
  unittests/test_fixtures.py
Labels: prio: normal, enhancement
