Repository reframe-hpc/reframe, pull requests merged in 2022-08, with the labels that each got.

#2562 [feat] Introduce ReFrame 4.0
  docs/deferrable_functions_reference.rst
  docs/regression_test_api.rst
  reframe/__init__.py
  reframe/core/containers.py
  reframe/core/decorators.py
  reframe/core/launchers/__init__.py
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/core/systems.py
  reframe/utility/__init__.py
  reframe/utility/sanity.py
  reframe/utility/versioning.py
  unittests/resources/checks_unlisted/no_required_version.py
  unittests/test_containers.py
  unittests/test_deferrable.py
  unittests/test_dependencies.py
  unittests/test_loader.py
  unittests/test_parameters.py
  unittests/test_pipeline.py
  unittests/test_versioning.py
Labels: enhancement, 4.x

#2573 [refactor] Small style enhancement
  reframe/core/fixtures.py
Labels: prio: normal, code quality

#2574 [feat] Drop the old test naming scheme
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/decorators.py
  reframe/core/fixtures.py
  reframe/core/logging.py
  reframe/core/meta.py
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  reframe/frontend/filters.py
  reframe/frontend/loader.py
  reframe/frontend/statistics.py
  reframe/schemas/config.json
  unittests/resources/settings.py
  unittests/test_cli.py
  unittests/test_dependencies.py
  unittests/test_filters.py
  unittests/test_parameters.py
  unittests/test_pipeline.py
Labels: prio: normal, code quality, enhancement, 4.x

#2575 [feat] Add command line option to set the execution order of independent tests
  docs/manpage.rst
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: prio: normal, enhancement, 4.x, cli

#2579 [packaging] Bump version of `requests` in `requirements.txt`
  requirements.txt
Labels: prio: normal, packaging

#2578 [feat] Associate a unique hash with each test
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/logging.py
  reframe/core/meta.py
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/filters.py
  unittests/test_dependencies.py
  unittests/test_filters.py
  unittests/test_fixtures.py
  unittests/test_logging.py
Labels: prio: normal, 4.x, runtime, cli

#2581 [bugfix] Fix singularity cli option to change to the mounted stage directory with the Singularity container platform
  reframe/core/containers.py
  unittests/test_containers.py
Labels: prio: normal, bugfix
