Repository reframe-hpc/reframe, pull requests merged in 2022-12, with the labels that each got.

#2703 [ci] Add support for Python 3.11 and update CI workflow for Python 3.6
  .github/workflows/main.yml
  setup.cfg
Labels: prio: important, automation, 4.x

#2691 [feat] Print better error message when pygelf cannot be imported
  reframe/core/logging.py
Labels: prio: normal, enhancement, logging

#2689 [bugfix] Fix nodelist compaction for single digitless nodes
  reframe/utility/__init__.py
  unittests/test_utility.py
Labels: prio: normal, bugfix

#2692 [bugfix] Do not require `handlers$` in the logging config
  reframe/core/config.py
  reframe/schemas/config.json
  unittests/test_config.py
Labels: prio: normal, bugfix, configuration

#2633 [feat] Improve performance logging
  docs/config_reference.rst
  docs/configure.rst
  docs/listings/perflogs.txt
  docs/tutorial_basics.rst
  reframe/core/logging.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/core/settings.py
  reframe/frontend/executors/__init__.py
  reframe/schemas/config.json
  unittests/conftest.py
  unittests/test_logging.py
  unittests/test_pipeline.py
  unittests/test_policies.py
Labels: prio: normal, enhancement, logging

#2707 [feat] Update `temp_environment` to use `env_vars` as an argument
  reframe/core/runtime.py
  reframe/core/schedulers/slurm.py
  reframe/frontend/autodetect.py
  unittests/test_argparser.py
Labels: prio: normal, enhancement, 4.x

#2706 [feat] Remove deprecated `--ignore-check-conflicts` CLI option and the associated configuration option
  reframe/core/hooks.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
Labels: prio: normal, 4.x

#2694 [feat] Remove the `schedulers` section from the configuration
  docs/config_reference.rst
  docs/configure.rst
  docs/pipeline.rst
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/flux.py
  reframe/core/schedulers/lsf.py
  reframe/core/schedulers/oar.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/sge.py
  reframe/core/schedulers/slurm.py
  reframe/core/systems.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
  unittests/test_schedulers.py
Labels: prio: normal, enhancement, 4.x, configuration

#2705 [bugfix] Properly set display name of tests with join fixtures
  reframe/core/meta.py
  reframe/core/pipeline.py
  unittests/test_fixtures.py
Labels: prio: normal, bugfix

#2708 [doc] Update link in codecov badge
  README.md
Labels: prio: normal, documentation, enhancement

#2695 [feat] Control verbosity level of the immediate performance info
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/logging.py
  reframe/frontend/argparse.py
  reframe/frontend/cli.py
  reframe/frontend/executors/policies.py
  reframe/schemas/config.json
  reframe/utility/typecheck.py
Labels: prio: normal, enhancement, runtime

#2702 [bugfix] Restrict reference tuples acceptable types
  reframe/core/pipeline.py
  reframe/utility/typecheck.py
  unittests/test_pipeline.py
  unittests/test_typecheck.py
Labels: prio: normal, bugfix

#2710 [feat] Remove the `--force-local` option
  docs/manpage.rst
  docs/pipeline.rst
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  unittests/resources/config/settings.py
  unittests/test_cli.py
  unittests/test_policies.py
Labels: prio: normal, enhancement, 4.x

#2712 [ci] Use an Ubuntu 20.04 image for Python 3.6 tests
  .github/workflows/main.yml
Labels: prio: normal, automation

#2711 [feat] Remove the `--strict` option
  docs/manpage.rst
  docs/tutorial_tips_tricks.rst
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  unittests/test_policies.py
Labels: prio: normal, enhancement, 4.x

#2714 [bugfix] Fix hash clashes for parameterised tests
  reframe/core/pipeline.py
  unittests/test_filters.py
  unittests/test_pipeline.py
Labels: prio: important, bugfix

#2713 [doc] Document the rest of `Job`'s properties
  docs/regression_test_api.rst
  reframe/core/schedulers/__init__.py
Labels: prio: normal, documentation

#2716 [bugfix] Fix cleanup crash for non-performance tests when the `perflog_compat` option is on
  reframe/frontend/executors/__init__.py
  unittests/test_policies.py
Labels: prio: important, bugfix

#2709 [doc] Add a "What's New" page for ReFrame 4.0
  docs/config_reference.rst
  docs/configure.rst
  docs/index.rst
  docs/manpage.rst
  docs/migration_2_to_3.rst
  docs/pipeline.rst
  docs/regression_test_api.rst
  docs/started.rst
  docs/tutorial_advanced.rst
  docs/tutorial_basics.rst
  docs/whats_new_40.rst
Labels: prio: normal, documentation, 4.x

#2718 [bugfix] Fix `perflog_compat` crash when performance test fails in sanity
  reframe/core/logging.py
  reframe/frontend/executors/__init__.py
  unittests/test_policies.py
Labels: prio: important, bugfix
