Repository reframe-hpc/reframe, pull requests merged in 2022-10, with the labels that each got.

#2611 [bugfix] Submit jobs using the correct module path when testing scheduler backends
  unittests/test_schedulers.py
Labels: prio: normal, bugfix

#2613 [feat] Add support for the Apptainer container platform
  docs/config_reference.rst
  reframe/core/containers.py
  unittests/test_containers.py
Labels: prio: normal, enhancement

#2605 [feat] Allow user defined launchers in the configuration
  docs/config_reference.rst
  docs/tutorial_advanced.rst
  reframe/core/launchers/__init__.py
  reframe/schemas/config.json
Labels: prio: normal, enhancement

#2620 [feat] Add `perflog_ignore` attribute in httpjson handler
  docs/config_reference.rst
  reframe/core/logging.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
Labels: prio: important, enhancement, bugfix, 4.x

#2619 [doc] Make it clear that logical CPUs refer to hardware threads
  docs/config_reference.rst
Labels: prio: normal, documentation, enhancement

#2618 [feat] Improve framework messages and the performance report
  docs/conf.py
  docs/listings/alltests_daint.txt
  docs/listings/deps_complex_run.txt
  docs/listings/deps_rerun_t6.txt
  docs/listings/deps_run_t6.txt
  docs/listings/hello1.txt
  docs/listings/hello2.txt
  docs/listings/hello2_catalina.txt
  docs/listings/hello2_list_verbose.txt
  docs/listings/hello2_print_stdout.txt
  docs/listings/hello2_typo.txt
  docs/listings/hello2_typo_stacktrace.txt
  docs/listings/hellomp1.txt
  docs/listings/hellomp2.txt
  docs/listings/maketest_mixin.txt
  docs/listings/osu_bandwidth_concretized_daint.txt
  docs/listings/osu_bench_deps.txt
  docs/listings/osu_bench_fixtures_list.txt
  docs/listings/osu_bench_fixtures_run.txt
  docs/listings/osu_bench_list_concretized.txt
  docs/listings/osu_bench_list_concretized_gnu.txt
  docs/listings/osu_latency_list.txt
  docs/listings/osu_latency_unresolved_deps.txt
  docs/listings/param_deps_list.txt
  docs/listings/stream1.txt
  docs/listings/stream3_failure_only.txt
  docs/listings/stream4_daint.txt
  docs/listings/stream_params.txt
  docs/tutorial_basics.rst
  docs/tutorial_tips_tricks.rst
  reframe/core/config.py
  reframe/core/logging.py
  reframe/frontend/cli.py
  reframe/frontend/executors/policies.py
  reframe/frontend/statistics.py
  tools/gendoclistings.py
  tutorials/config/settings.py
  tutorials/cscs-webinar-2022/config/mysettings.py
  unittests/test_logging.py
Labels: prio: normal, enhancement

#2624 [feat] Remove the deprecated `RFM_GRAYLOG_SERVER` environment variable
  docs/manpage.rst
  reframe/frontend/cli.py
Labels: prio: normal, enhancement

#2627 [feat] Allow tests to require references
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: prio: normal, enhancement, test syntax

#2631 [test] Fix sanity pattern in GpuShmem test
  hpctestlib/microbenchmarks/gpu/shmem/__init__.py
Labels: prio: normal, bugfix, test library

#2637 [packaging] Update `setup.cfg` to match the authors in the copyright
  setup.cfg
Labels: prio: normal, packaging

#2641 [bugfix] Filter out unnecessary fixtures when listing or running tests
  reframe/frontend/cli.py
Labels: prio: normal, bugfix

#2644 [feat] Extend `cray_cdt_version()` utility function to recognise CPE versions too
  reframe/utility/osext.py
Labels: prio: normal

#2638 [feat] Change default value of `num_gpus_per_node` to `None`
  reframe/core/pipeline.py
Labels: prio: normal, enhancement, 4.x

#2643 [doc] Remove mailing list from README
  README.md
  README_minimal.md
Labels: prio: normal, documentation
