Repository reframe-hpc/reframe, pull requests merged in 2022-11, with the labels that each got.

#2647 [feat] Introduce variable aliases
  docs/conf.py
  reframe/core/meta.py
  reframe/core/variables.py
  unittests/test_logging.py
  unittests/test_variables.py
Labels: prio: normal, enhancement, test syntax

#2634 [bugfix] Keep updating the node list during the job
  reframe/core/schedulers/slurm.py
  reframe/utility/__init__.py
  unittests/test_utility.py
Labels: prio: normal, bugfix

#2649 [feat] Relax the value syntax of `env_vars`
  reframe/core/environments.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  tutorials/advanced/parameterized/stream.py
  tutorials/basics/stream/stream4.py
  tutorials/cscs-webinar-2022/tests/stream4.py
  tutorials/cscs-webinar-2022/tests/stream5.py
  tutorials/cscs-webinar-2022/tests/stream6.py
  tutorials/cscs-webinar-2022/tests/stream7.py
  tutorials/cscs-webinar-2022/tests/stream8.py
  tutorials/cscs-webinar-2022/tests/stream9.py
  unittests/test_environments.py
  unittests/test_pipeline.py
Labels: prio: normal, enhancement, test syntax

#2656 [bugfix] Pass explicitly the `--cpus-per-task` option to `srun` for Slurm >= 22.05
  reframe/core/launchers/mpi.py
  unittests/test_launchers.py
Labels: prio: normal, bugfix

#2682 [bugfix] Fix injection of env variables for non default craype
  reframe/core/pipeline.py
Labels: prio: normal, bugfix

#2679 [testlib] Use the builtin validation option of OSU benchmarks to validate the results
  hpctestlib/microbenchmarks/mpi/osu.py
Labels: prio: normal, enhancement, test library

#2680 [ci] Revert workaround in script for generating release notes
  ci-scripts/genrelnotes.py
Labels: prio: normal, automation

#2683 [bugfix] Fix variable assignment when aliases are set in subclasses
  reframe/core/variables.py
  unittests/test_pipeline.py
Labels: prio: important, bugfix, test syntax

#2684 [doc] Update copyright notice in docs
  docs/conf.py
Labels: prio: normal, documentation

#2685 [doc] Fix example in `sn.print()` docs
  reframe/utility/sanity.py
Labels: prio: normal, documentation, bugfix

#2688 [bugfix] Fix filtering of tests with hashcode
  reframe/frontend/filters.py
  unittests/test_cli.py
Labels: prio: normal, bugfix, cli
