Repository reframe-hpc/reframe, pull requests merged in 2022-06, with the labels that each got.

#2524 [testlib] Fix broken symlinks to the Xdevice header library
  hpctestlib/microbenchmarks/gpu/dgemm/src/Xdevice
  hpctestlib/microbenchmarks/gpu/kernel_latency/src/Xdevice
  hpctestlib/microbenchmarks/gpu/memory_bandwidth/src/Xdevice
  hpctestlib/microbenchmarks/gpu/pointer_chase/src/Xdevice
  hpctestlib/microbenchmarks/gpu/shmem/src/Xdevice
Labels: prio: important, bugfix, test library

#2535 [bugfix] Skip test file when an import error is encountered
  reframe/core/exceptions.py
Labels: prio: normal, bugfix

#2534 [bugfix] Reset poll rate every time a test finishes the compilation or run phase
  reframe/frontend/executors/policies.py
Labels: prio: normal, bugfix, executors

#2533 [bugfix] Improve test selection by their variant id
  reframe/frontend/filters.py
  reframe/frontend/runreport.py
  reframe/frontend/statistics.py
  reframe/schemas/runreport.json
  unittests/test_filters.py
Labels: prio: normal, bugfix

#2538 [bugfix] Snooze between polls in serial policy
  reframe/frontend/executors/policies.py
Labels: prio: important, bugfix, runtime

#2537 [feat] Do not require to set `container_platform` for running containerised tests
  docs/config_reference.rst
  docs/tutorial_advanced.rst
  reframe/core/containers.py
  reframe/core/pipeline.py
  reframe/core/systems.py
  reframe/schemas/config.json
  reframe/utility/__init__.py
  tutorials/advanced/containers/gromacs_test.py
  unittests/resources/settings.py
  unittests/test_config.py
  unittests/test_containers.py
  unittests/test_pipeline.py
Labels: prio: normal, enhancement, test syntax

#2541 [doc] Fix documentation of execution modes' `target_systems`
  docs/config_reference.rst
Labels: prio: normal, documentation, bugfix

#2543 [feat] Include the loggable variables and parameters in the run report
  docs/config_reference.rst
  docs/manpage.rst
  reframe/frontend/cli.py
  reframe/frontend/runreport.py
  reframe/frontend/statistics.py
  reframe/schemas/config.json
  reframe/schemas/runreport.json
Labels: prio: normal, enhancement

#2546 [bugfix] Treat undefined variables correctly in run report
  reframe/frontend/statistics.py
  unittests/resources/checks/frontend_checks.py
  unittests/test_schedulers.py
Labels: prio: normal, bugfix

#2544 [feat] Optimise the test case generation
  reframe/frontend/executors/__init__.py
  reframe/schemas/config.json
  unittests/test_dependencies.py
  unittests/test_pipeline.py
Labels: prio: normal, enhancement, runtime

#2545 [feat] Add a lightweight time profiler in the framework
  reframe/core/decorators.py
  reframe/core/logging.py
  reframe/frontend/cli.py
  reframe/frontend/dependencies.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/loader.py
  reframe/frontend/testgenerators.py
  reframe/utility/profile.py
  unittests/test_profiler.py
Labels: prio: normal, enhancement
