Repository reframe-hpc/reframe, pull requests merged in 2022-05, with the labels that each got.

#2503 [testlib] Make GPU burn test a library test
  config/cscs.py
  cscs-checks/microbenchmarks/gpu/gpu_burn/gpu_burn_test.py
  docs/hpctestlib.rst
  hpctestlib/microbenchmarks/gpu/gpu_burn.py
  hpctestlib/microbenchmarks/gpu/gpu_burn/__init__.py
  hpctestlib/microbenchmarks/gpu/gpu_burn/src/Xdevice
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/blas.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/common/smi.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/cuda/blas.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/cuda/include.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/cuda/smi.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/cuda/types.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/cuda/utils.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/defaults.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/hip/blas.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/hip/include.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/hip/smi.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/hip/types.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/hip/utils.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/runtime.hpp
  hpctestlib/microbenchmarks/gpu/src/common/Xdevice/smi.hpp
  hpctestlib/microbenchmarks/gpu/src/gpu_burn/Xdevice
  hpctestlib/microbenchmarks/gpu/src/gpu_burn/gpu_burn.cu
  hpctestlib/microbenchmarks/gpu/src/gpu_burn/makefile.cuda
  hpctestlib/microbenchmarks/gpu/src/gpu_burn/makefile.hip
  reframe/core/systems.py
Labels: prio: important, regression test, test library

#2516 [test] Align the job report test to the new `gpu_burn_check` library test
  cscs-checks/system/jobreport/gpu_report.py
Labels: prio: important, regression test

#2515 [bugfix] Allow setting fixture variables from the command line
  docs/manpage.rst
  reframe/core/meta.py
  reframe/core/variables.py
  unittests/resources/checks_unlisted/externalvars.py
  unittests/test_cli.py
Labels: prio: normal, bugfix

#2519 [bugfix] Check that PBS output is written back to working directory before setting the job as completed
  reframe/core/schedulers/pbs.py
Labels: prio: normal, bugfix, schedulers

#2514 [feat] Add `--mode` option to GitLab CI pipeline command
  docs/tutorial_tips_tricks.rst
  reframe/frontend/ci.py
  reframe/frontend/cli.py
Labels: feature request, prio: normal
