Repository reframe-hpc/reframe, pull requests merged in 2022-04, with the labels that each got.

#2444 [feat] Introduce environment variables for controlling system auto-detection
  docs/configure.rst
  docs/manpage.rst
  reframe/core/config.py
  reframe/frontend/argparse.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
  unittests/test_argparser.py
  unittests/test_config.py
Labels: feature request, prio: normal

#2421 [testlib] Add OSU benchmarks in the test library and adapt CSCS checks accordingly
  cscs-checks/microbenchmarks/mpi/osu/osu_tests.py
  cscs-checks/microbenchmarks/mpi/osu/src/Makefile_allreduce
  cscs-checks/microbenchmarks/mpi/osu/src/Makefile_alltoall
  cscs-checks/microbenchmarks/mpi/osu/src/Makefile_p2p
  cscs-checks/microbenchmarks/mpi/osu/src/osu_allreduce.c
  cscs-checks/microbenchmarks/mpi/osu/src/osu_alltoall.c
  cscs-checks/microbenchmarks/mpi/osu/src/osu_bw.c
  cscs-checks/microbenchmarks/mpi/osu/src/osu_latency.c
  cscs-checks/microbenchmarks/mpi/osu/src/osu_util.c
  cscs-checks/microbenchmarks/mpi/osu/src/osu_util.h
  docs/hpctestlib.rst
  hpctestlib/microbenchmarks/mpi/osu.py
Labels: prio: normal, regression test, test library

#2491 [test] Use a Jupyter notebook as IPCMagic script for better readability
  hpctestlib/interactive/jupyter/ipcmagic/__init__.py
  hpctestlib/interactive/jupyter/ipcmagic/src/tf-hvd-sgd-ipc-tf2.ipynb
  hpctestlib/interactive/jupyter/ipcmagic/src/tf-hvd-sgd-ipc-tf2.py
Labels: prio: normal, regression test

#2485 [bugfix] Fix test filtering by name when multiple exact matches are requested
  reframe/frontend/cli.py
  reframe/frontend/filters.py
  unittests/test_filters.py
Labels: prio: normal, bugfix

#2492 [doc] Improve documentation about setting performance references in tests
  reframe/core/pipeline.py
Labels: prio: normal, documentation

#2493 [ci] Use `pytest-rerunfailures` to and mark flaky unit tests
  requirements.txt
  unittests/test_schedulers.py
Labels: prio: normal, ci-integration

#2479 [feat] Extend the syntax of `valid_systems` and `valid_prog_environs`
  docs/config_reference.rst
  reframe/core/decorators.py
  reframe/core/environments.py
  reframe/core/fixtures.py
  reframe/core/meta.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/core/systems.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/loader.py
  reframe/schemas/config.json
  unittests/resources/settings.py
  unittests/test_config.py
  unittests/test_fixtures.py
  unittests/test_pipeline.py
  unittests/test_policies.py
Labels: prio: normal, enhancement, test syntax

#2494 [feat] Add new build system backend for custom builds
  reframe/core/buildsystems.py
  unittests/test_buildsystems.py
Labels: prio: normal, enhancement, buildsystems

#2458 [feat] Add new command line option to distribute single node jobs on multiple cluster nodes
  docs/manpage.rst
  reframe/core/meta.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/slurm.py
  reframe/frontend/cli.py
  reframe/frontend/distribute.py
  reframe/frontend/statistics.py
  unittests/resources/checks_unlisted/distribute.py
  unittests/test_cli.py
  unittests/test_distribute_tests.py
Labels: feature request, prio: normal

#2496 [test] Fix metric name in references for CPMD and VASP checks
  cscs-checks/apps/cpmd/cpmd_check.py
  cscs-checks/apps/vasp/vasp_check.py
Labels: prio: important, regression test
