Repository reframe-hpc/reframe, pull requests merged in 2023-06, with the labels that each got.

#2887 [feat] Support `prepare_cmds` at the environment level
  docs/config_reference.rst
  reframe/core/environments.py
  reframe/core/runtime.py
  reframe/core/systems.py
  reframe/schemas/config.json
  unittests/resources/config/settings.py
  unittests/test_environments.py
Labels: new feature, prio: normal

#2921 [doc] Fix broken formatting in `extractall_s()` docs
  reframe/utility/sanity.py
Labels: prio: normal, documentation, bugfix

#2922 [doc] Fixed a typo in documentation - `JobLaucher` to `JobLauncher`
  docs/tutorial_advanced.rst
Labels: prio: normal, documentation, bugfix

#2920 [doc] Fix broken docs links in `valid_systems` and `valid_prog_environs` sections
  reframe/core/pipeline.py
Labels: prio: normal, documentation, bugfix

#2894 [feat] Support for `pdsh` and `clush` parallel launchers
  docs/config_reference.rst
  docs/configure.rst
  reframe/core/backends.py
  reframe/core/launchers/rsh.py
  unittests/test_launchers.py
Labels: new feature, prio: normal, schedulers

#2882 [feat] Combine perflogs for parameterised tests
  docs/config_reference.rst
  reframe/core/logging.py
  reframe/core/settings.py
  reframe/schemas/config.json
  unittests/test_policies.py
Labels: new feature, prio: normal

#2925 [packaging] Fail on errors in `bootstrap.sh` and add a new `--ignore-errors` option
  bootstrap.sh
Labels: prio: normal, enhancement, packaging

#2927 [bugfix] Properly cleanup resources of dependencies when their dependents are filtered
  reframe/frontend/dependencies.py
  unittests/test_dependencies.py
Labels: prio: normal, bugfix

#2928 [bugfix] Use tests's short name as the name of the job
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
Labels: prio: normal, bugfix

#2919 [feat] Additional Spack build system options
  reframe/core/buildsystems.py
  unittests/test_buildsystems.py
Labels: new feature, prio: normal

#2929 [doc] Add note about test generation options and `--ci-generate`
  docs/manpage.rst
Labels: prio: normal, documentation, enhancement

#2913 [feat] Parameterise test from command line
  docs/manpage.rst
  reframe/core/meta.py
  reframe/frontend/cli.py
  reframe/frontend/testgenerators.py
  unittests/test_cli.py
  unittests/test_testgenerators.py
Labels: new feature, prio: normal, cli

#2931 [feat] Update default `--timestamp` format
  reframe/core/runtime.py
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: prio: normal, enhancement, runtime
