Repository reframe-hpc/reframe, pull requests merged in 2023-12, with the labels that each got.

#3058 [bugfix] Do not pass the stdout/stderr options to `srun` when using the `srunalloc` launcher
  reframe/core/launchers/mpi.py
  unittests/test_launchers.py
Labels: prio: normal, bugfix, schedulers

#3068 [doc] Remove outdated text in configuration docs
  docs/configure.rst
Labels: prio: normal, documentation, bugfix

#3070 [feat] Issue an error when invoking an invalid mode
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: prio: normal, enhancement, configuration, cli

#3054 [enhancement] Skip modules system sanity checking when module conflict resolution is off
  docs/config_reference.rst
  reframe/core/modules.py
  reframe/core/systems.py
Labels: prio: normal, enhancement

#3081 [bugfix] Fix crash when `--distribute` option is applied to a run-only test
  reframe/frontend/testgenerators.py
  unittests/resources/checks_unlisted/distribute.py
  unittests/test_cli.py
Labels: prio: normal, bugfix

#3080 [doc] Document the limitations of the test generation options
  docs/manpage.rst
  reframe/frontend/cli.py
Labels: prio: normal, documentation, enhancement

#3082 [enhancement] Make variables and parameters loggable by default
  reframe/core/parameters.py
  reframe/core/pipeline.py
  reframe/core/variables.py
  unittests/resources/checks/frontend_checks.py
  unittests/test_logging.py
  unittests/test_meta.py
Labels: prio: normal, enhancement

#3083 [enhancement] Allow `always_last` to be defined in multiple hooks and add a note about users' workaround code for enforcing hook execution order
  docs/regression_test_api.rst
  reframe/core/builtins.py
  reframe/core/pipeline.py
  unittests/test_pipeline.py
Labels: prio: normal, enhancement, test syntax

#3084 [feat] Expose job submit time as a loggable property
  docs/config_reference.rst
  reframe/core/pipeline.py
Labels: prio: normal, enhancement, logging
