Repository reframe-hpc/reframe, pull requests merged in 2023-09, with the labels that each got.

#2978 [bugfix] Fix remote topology detection for pip installations
  reframe/frontend/autodetect.py
Labels: prio: normal, bugfix, autodetection

#2994 [ci] Pin version of flux scheduler in CI
  .github/workflows/test-flux.yaml
Labels: prio: important, automation

#2992 [feat] Allow pinning a hook as the last of its stage
  docs/regression_test_api.rst
  reframe/core/builtins.py
  reframe/core/hooks.py
  reframe/core/pipeline.py
  unittests/test_meta.py
  unittests/test_pipeline.py
Labels: prio: normal, enhancement, test syntax

#2996 [testlib] Fix the `ssh_host_keys` library test
  hpctestlib/system/ssh/host_keys.py
Labels: prio: normal, bugfix, test library

#2998 [doc] Update `filelog` log handler docs
  docs/config_reference.rst
Labels: prio: normal, documentation, bugfix

#3000 [bugfix] Always remove temporary directory when remote auto-detection fails
  reframe/frontend/autodetect.py
Labels: prio: normal, bugfix, autodetection

#2999 [bugfix] Show test references with `--describe` option
  reframe/utility/__init__.py
  unittests/test_utility.py
Labels: prio: normal, bugfix, cli

#2997 [bugfix] Respect execution order of overriden hooks
  reframe/core/hooks.py
  reframe/core/meta.py
  unittests/test_pipeline.py
Labels: prio: normal, bugfix, test syntax

#3003 [packaging] Add hpctestlib to the PyPI package
  setup.cfg
Labels: prio: normal, bugfix, packaging

#2993 [bugfix] Properly retrieve exit status for PBS Pro jobs
  reframe/core/schedulers/pbs.py
Labels: prio: normal, bugfix, schedulers

#2975 [feat] Add an SSH-based scheduler backend
  docs/config_reference.rst
  reframe/core/backends.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/ssh.py
  reframe/schemas/config.json
  reframe/utility/osext.py
  unittests/test_schedulers.py
  unittests/test_utility.py
Labels: prio: normal, enhancement, schedulers
