Repository reframe-hpc/reframe, pull requests merged in 2023-07, with the labels that each got.

#2876 [feat] Allow setting nested mapping types using the `-S` option
  docs/manpage.rst
  reframe/utility/typecheck.py
  unittests/test_typecheck.py
Labels: prio: normal, enhancement

#2946 [bugfix] Update OAR scheduler backend to accept the `Job_Id:` syntax
  reframe/core/schedulers/oar.py
Labels: prio: normal, schedulers, autodetection

#2947 [bugfix] Properly apply logging configuration to all systems listed in `target_systems`
  reframe/core/config.py
Labels: prio: normal, bugfix, configuration

#2948 [enhancement] Warn on unset variables in fixtures when using the `-S` option
  reframe/core/decorators.py
  reframe/frontend/cli.py
  reframe/frontend/loader.py
  tutorials/cscs-webinar-2022/config/mysettings.py
Labels: prio: normal, enhancement, cli

#2953 [enhancement] Run `./bootstrap.sh` in a virtual environment
  .github/workflows/test-flux.yaml
  bootstrap.sh
  ci-scripts/dockerfiles/Lmod-base.dockerfile
  ci-scripts/dockerfiles/Lmod77-base.dockerfile
  ci-scripts/dockerfiles/Spack.dockerfile
  ci-scripts/dockerfiles/Tmod4-base.dockerfile
Labels: prio: normal, bugfix, packaging

#2955 [feat] Support for custom schedulers
  reframe/schemas/config.json
Labels: new feature, prio: normal, schedulers
