Repository reframe-hpc/reframe, pull requests merged in 2023-01, with the labels that each got.

#2731 [bugfix] Add MANIFEST.in to include the README_minimal.md
  MANIFEST.in
Labels: prio: normal, documentation, bugfix, packaging

#2736 [feat] Relax the regex matching for test names and tags
  docs/manpage.rst
  reframe/frontend/filters.py
  unittests/test_cli.py
  unittests/test_testgenerators.py
Labels: prio: normal, enhancement

#2743 [doc] Improve documentation for the `RFM_CONFIG_PATH`
  docs/manpage.rst
Labels: prio: normal, documentation, enhancement

#2750 [ci] Use `master` branch for deployment
  ci-scripts/deploy.sh
Labels: prio: normal, automation, bugfix

#2751 [bugfix] Fix performance logging when `perf_variables` are set in a performance stage hook
  reframe/core/logging.py
  reframe/frontend/executors/__init__.py
  unittests/test_policies.py
Labels: prio: normal, bugfix, logging

#2765 [bugfix] Fix broken `--cpu-only` and `--gpu-only` options
  reframe/frontend/filters.py
  unittests/test_filters.py
Labels: prio: normal, bugfix, cli

#2767 [testlib] Change execution stage in OSU test library
  hpctestlib/microbenchmarks/mpi/osu.py
Labels: prio: normal, bugfix, test library

#2766 [bugfix] Pass long job options with `=`
  reframe/frontend/cli.py
Labels: prio: normal, bugfix, schedulers

#2762 [feat] Print the first lines of stderr and stdout in case of sanity failures
  reframe/frontend/statistics.py
Labels: new feature, prio: normal

#2769 [bugfix] Fix confusing stack trace dump when a logging error occurs
  reframe/frontend/executors/policies.py
Labels: prio: normal, bugfix, runtime, logging
