Repository reframe-hpc/reframe, pull requests merged in 2023-05, with the labels that each got.

#2866 [doc] New tutorial example on how to use `make_test()`
  docs/tutorial_make_test.rst
  docs/tutorials.rst
  tutorials/advanced/make_test/src/stream.c
  tutorials/advanced/make_test/stream.py
  tutorials/advanced/make_test/stream_config.yaml
  tutorials/advanced/make_test/stream_workflows.py
Labels: prio: normal, documentation

#2832 [feat] Support custom system auto-detection methods
  docs/config_reference.rst
  docs/configure.rst
  docs/manpage.rst
  reframe/core/config.py
  reframe/frontend/cli.py
  reframe/frontend/loader.py
  reframe/schemas/config.json
  reframe/utility/__init__.py
  unittests/resources/config/settings.py
  unittests/test_config.py
Labels: new feature, prio: normal, configuration, autodetection

#2881 [doc] Add EUM'23 slides
  docs/index.rst
Labels: prio: normal, documentation

#2883 [dependencies] Update requests version and add a Python 3.6 disclaimer
  docs/started.rst
  requirements.txt
Labels: prio: normal, documentation, dependencies

#2878 [doc] List the `httpjson` and `filelog` handlers as perflog handlers only
  docs/config_reference.rst
  docs/manpage.rst
  reframe/schemas/config.json
Labels: prio: normal, documentation, enhancement

#2885 [bugfix] Fix definition of default values for `sched_options` parameters
  reframe/schemas/config.json
  unittests/test_config.py
Labels: prio: normal, bugfix

#2888 [doc] Add part 2 of the EUM'23 talk + link to video
  docs/index.rst
Labels: prio: normal, documentation

#2892 [doc] Fixed a typo in documentation - `JobLaucher` to `JobLauncher`
  docs/tutorial_advanced.rst
Labels: prio: normal, documentation, bugfix

#2891 [doc] Update Slack link in `README_minimal.md`
  README_minimal.md
Labels: prio: normal, bugfix, packaging
