Repository reframe-hpc/reframe, pull requests merged in 2023-10, with the labels that each got.

#3010 [feat] Filter tests using arbitrary expressions
  docs/manpage.rst
  reframe/frontend/cli.py
  reframe/frontend/filters.py
  unittests/test_cli.py
  unittests/test_filters.py
Labels: new feature, prio: normal, cli

#3020 [ci] Validate docs everywhere
  .github/workflows/main.yml
Labels: prio: normal, automation, documentation

#3026 [doc] Update doc dependencies
  docs/requirements.txt
Labels: prio: normal, documentation, dependencies

#3025 [bugfix] Upgrade pip before pip-installing reframe for CPU autodetection
  reframe/frontend/autodetect.py
Labels: prio: normal, bugfix, autodetection

#3027 [bugfix] Treat node name suffixes properly in abbreviated node lists
  reframe/utility/__init__.py
  unittests/test_utility.py
Labels: prio: normal, bugfix

#2958 [testlib] Add fs mount options check to hpctstlib
  docs/hpctestlib.rst
  hpctestlib/system/fs/mnt_opts.py
Labels: prio: low, test library
