Repository reframe-hpc/reframe, pull requests merged in 2023-02, with the labels that each got.

#2752 [feat] Allow custom JSON formatting for log records in the `httpjson` handler
  docs/config_reference.rst
  reframe/core/logging.py
  reframe/schemas/config.json
  unittests/test_logging.py
Labels: new feature, prio: normal, logging

#2774 [bugfix] Warn for unset variables only for the tests that are selected
  reframe/frontend/cli.py
  reframe/frontend/loader.py
Labels: prio: normal, bugfix

#2775 [ci] Update GitHub Actions to use setup-python@v4
  .github/workflows/main.yml
  .github/workflows/publish.yml
Labels: prio: normal, ci-integration

#2777 [test] Update the syntax of the ipcmagic hpclib test to match ipcmagic-1.1.0
  hpctestlib/interactive/jupyter/ipcmagic/src/tf-hvd-sgd-ipc-tf2.ipynb
Labels: prio: normal, test library

#2782 [ci] Improve the release notes generation
  ci-scripts/genrelnotes.py
Labels: prio: normal, automation

#2778 [feat] Allow `num_tasks` to be `None`
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/lsf.py
  reframe/core/schedulers/oar.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  unittests/test_schedulers.py
Labels: prio: normal, enhancement, test syntax

#2783 [enhancement] Print the fixture variable names in test listings
  docs/manpage.rst
  reframe/frontend/cli.py
Labels: prio: normal, documentation, enhancement, cli

#2786 [bugfix] Correctly silence the `stream` handlers only when the `-q` option is passed
  reframe/core/logging.py
Labels: prio: normal, bugfix, logging

#2788 [enhancement] Properly combine `append`-type command-line options defined in execution modes
  docs/config_reference.rst
  docs/manpage.rst
  reframe/frontend/argparse.py
  unittests/test_argparser.py
Labels: prio: normal, enhancement, cli

#2770 [bugfix] Register performance functions even if `perf_variables` are defined in the class body and improve the performance function docs
  docs/deferrable_functions_reference.rst
  docs/tutorial_basics.rst
  reframe/core/pipeline.py
Labels: prio: normal, documentation, enhancement, bugfix, test syntax

#2780 [bugfix] Do not issue a name conflict error for the same fixture imported from different test files
  reframe/frontend/loader.py
  unittests/resources/checks_unlisted/testlib_inheritance_bar.py
  unittests/resources/checks_unlisted/testlib_inheritance_foo.py
  unittests/resources/testlib/simple.py
  unittests/test_cli.py
Labels: prio: normal, bugfix

#2790 [enhancement] Raise warning for invalid mode cli option
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: prio: normal, enhancement

#2791 [ci] Use release/v1 version for the publish gh action
  .github/workflows/publish.yml
Labels: prio: normal, ci-integration

#2793 [bugfix] Properly define `sched_options` in the configuration schema
  reframe/schemas/config.json
  unittests/resources/config/settings.py
  unittests/test_config.py
Labels: prio: important, bugfix, configuration

#2796 [bugfix] Fix use of `sched_options` by the backend schedulers
  docs/config_reference.rst
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/slurm.py
  reframe/schemas/config.json
  unittests/resources/config/settings.py
  unittests/test_config.py
  unittests/test_schedulers.py
Labels: prio: normal, bugfix, schedulers, configuration

#2746 [feat] Introduce a `--dry-run` option
  docs/manpage.rst
  reframe/core/decorators.py
  reframe/core/fixtures.py
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  reframe/frontend/loader.py
  reframe/frontend/printer.py
  unittests/test_cli.py
Labels: new feature, prio: normal

#2798 [bugfix] Fix listing of non-fixture-based dependencies
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: prio: normal, bugfix
