Repository reframe-hpc/reframe, pull requests merged in 2024-08, with the labels that each got.

#3239 [bugfix] Fix typo in the `--distribute` docs
  docs/manpage.rst
Labels: prio: normal, documentation, bugfix

#3227 [feat] Introduce permanent result storage and support performance results comparisons between runs
  docs/config_reference.rst
  docs/manpage.rst
  docs/tutorial.rst
  examples/tutorial/dockerfiles/singlenode.Dockerfile
  reframe/core/exceptions.py
  reframe/core/logging.py
  reframe/core/pipeline.py
  reframe/core/runtime.py
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/pbs.py
  reframe/frontend/argparse.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/printer.py
  reframe/frontend/reporting/__init__.py
  reframe/frontend/reporting/storage.py
  reframe/frontend/reporting/utility.py
  reframe/frontend/runreport.py
  reframe/frontend/statistics.py
  reframe/schemas/config.json
  reframe/schemas/runreport.json
  requirements.txt
  setup.cfg
  unittests/conftest.py
  unittests/test_argparser.py
  unittests/test_cli.py
  unittests/test_perflogging.py
  unittests/test_policies.py
  unittests/test_reporting.py
  unittests/test_schedulers.py
Labels: new feature, prio: normal

#3246 [feat] Introduce new option `--table-hide-columns` for hiding columns in tabular data output
  docs/manpage.rst
  reframe/frontend/cli.py
  reframe/frontend/printer.py
  unittests/test_cli.py
Labels: prio: normal, reporting
