Repository reframe-hpc/reframe, pull requests merged in 2024-12, with the labels that each got.

#3337 [bugfix] Fix relative imports in deeply nested tests
  reframe/frontend/loader.py
  unittests/resources/checks_unlisted/testlib/nested/__init__.py
  unittests/resources/checks_unlisted/testlib/nested/dummy.py
  unittests/resources/checks_unlisted/testlib/simple.py
  unittests/test_cli.py
  unittests/test_loader.py
Labels: prio: normal, bugfix

#3326 [bugfix] Fix error in fixture resolution when multiple fixtures of the same class are instantiated with different variables
  reframe/core/pipeline.py
  unittests/resources/checks_unlisted/fixtures_complex.py
Labels: prio: normal, bugfix

#3329 [bugfix] Do not ignore `--filter-expr` when using `--describe-stored-testcases`
  reframe/frontend/cli.py
Labels: prio: normal, bugfix, reporting

#3330 [enhancement] Prefix special (generated) parameters with `.` instead of `$`
  docs/manpage.rst
  reframe/frontend/testgenerators.py
  unittests/test_testgenerators.py
Labels: prio: normal, enhancement

#3339 [bugfix] Fix nodelist abbreviation when last node number is a multiple of 10
  reframe/utility/__init__.py
  unittests/test_utility.py
Labels: prio: normal, bugfix

#3327 [bugfix] Treat correctly Slurm constrains with hyphens when filtering nodes
  reframe/core/schedulers/slurm.py
Labels: prio: normal, bugfix, schedulers

#3328 [bugfix] Exit successfully if `--duration` limit is reached
  reframe/frontend/cli.py
  unittests/test_cli.py
Labels: prio: normal, bugfix, cli

#3346 [feat] Introduce `%(hostname)s` log format placeholder
  docs/config_reference.rst
  reframe/core/logging.py
Labels: prio: normal, enhancement, logging

#3350 [ci] Update GH actions for Python 3.7 after the move of runners to Ubuntu 24.04
  .github/workflows/main.yml
Labels: prio: important, automation
