Repository reframe-hpc/reframe, pull requests merged in 2024-05, with the labels that each got.

#3185 [feat] Update `archspec` and topology file call for CPU model name
  docs/requirements.txt
  reframe/utility/cpuinfo.py
  requirements.txt
  setup.cfg
Labels: prio: normal, autodetection

#3188 [ci] Do not upload to Codecov through a GH action
  .github/workflows/main.yml
Labels: prio: important, automation

#3173 [feat] Skip by default flexible tests when not enough nodes found
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/pipeline.py
  reframe/core/schedulers/__init__.py
  reframe/frontend/cli.py
  unittests/test_schedulers.py
Labels: prio: normal, enhancement, cli

#3184 [bugfix] Retrieve the test job's nodelist when using the `squeue` backend
  examples/tutorial/dockerfiles/slurm-cluster/reframe/Dockerfile
  reframe/core/schedulers/slurm.py
Labels: prio: normal, bugfix, schedulers

#3191 [doc] Add EUM24 slides
  docs/index.rst
Labels: prio: normal, documentation

#3189 [feat] Add a perflog entry also when sanity fails
  docs/config_reference.rst
  reframe/core/logging.py
  reframe/core/pipeline.py
  reframe/frontend/cli.py
  reframe/frontend/executors/__init__.py
  reframe/frontend/executors/policies.py
  unittests/test_cli.py
  unittests/test_policies.py
Labels: prio: normal, enhancement, logging

#3193 [bugfix] Constraint the lxml version on aarch64
  requirements.txt
  setup.cfg
Labels: prio: normal, bugfix, dependencies

#3199 [bugfix] Handle `None` cpu model name returned from `archspec`
  reframe/utility/cpuinfo.py
Labels: prio: normal, bugfix, autodetection

#3197 [doc] Use long options in places
  docs/tutorial.rst
Labels: prio: normal, documentation, enhancement

#3195 [doc] Display Python imports in the first tutorial example
  docs/tutorial.rst
Labels: prio: normal, documentation, enhancement

#3196 [doc] Fix broken cross links in the documentation
  docs/config_reference.rst
  docs/deferrables.rst
  docs/dependencies.rst
  docs/howto.rst
  docs/manpage.rst
  docs/pipeline.rst
  docs/regression_test_api.rst
  docs/tutorial.rst
Labels: prio: normal, documentation, bugfix

#3201 [bugfix] Fix perflog header formatting when `perflog_compat` is used
  reframe/core/logging.py
  unittests/test_policies.py
Labels: bug, prio: normal, logging

#3204 [bugfix] Make version hash suffix calculation more robust
  reframe/utility/osext.py
Labels: prio: normal, bugfix

#3206 [bugfix] Do not use CLI defaults for options that are backed by a configuration option
  reframe/frontend/cli.py
Labels: prio: normal, bugfix

#3205 [dependencies] Bump version of `requests` package
  requirements.txt
Labels: prio: normal, enhancement, dependencies
