Repository reframe-hpc/reframe, pull requests merged in 2024-03, with the labels that each got.

#3133 [doc] Fix spelling mistake in the documentation
  docs/tutorial_deps.rst
Labels: prio: normal, documentation, bugfix

#3135 [packaging] Stricter install requirements in `setup.cfg`
  setup.cfg
Labels: prio: important, packaging

#3138 [feat] Add a `model` property to the devices configuration
  reframe/core/systems.py
  reframe/schemas/config.json
  unittests/resources/config/settings.py
  unittests/test_autodetect.py
  unittests/test_config.py
Labels: prio: normal, configuration

#3134 [testlib] Added QuantumESPRESSO scalability test for `pw.x`
  docs/hpctestlib.rst
  hpctestlib/sciapps/qespresso/benchmarks.py
Labels: prio: low, enhancement, test library

#3140 [feat] Improve state selection criteria in the `--distribute` and the `--flex-alloc-nodes` option
  docs/manpage.rst
  reframe/core/schedulers/__init__.py
  reframe/core/schedulers/local.py
  reframe/core/schedulers/slurm.py
  reframe/frontend/cli.py
  reframe/frontend/testgenerators.py
Labels: prio: normal, enhancement

#3142 [bugfix] Fix logging crash when the `check_#ALL` placeholder is used
  reframe/core/logging.py
  unittests/test_policies.py
Labels: prio: normal, bugfix, logging
