Repository reframe-hpc/reframe, pull requests merged in 2024-06, with the labels that each got.

#3208 [doc] Improve description of `valid_systems` and `valid_prog_environs` in the tutorial and other minor tutorial fixes
  docs/regression_test_api.rst
  docs/tutorial.rst
Labels: prio: normal, documentation

#3213 [doc] Update description of the configuration in the manpage
  docs/manpage.rst
Labels: prio: normal, documentation, bugfix

#3156 [feat] Allow ReFrame to pass the access options in command line instead of the script for Slurm
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/schedulers/lsf.py
  reframe/core/schedulers/oar.py
  reframe/core/schedulers/pbs.py
  reframe/core/schedulers/slurm.py
  reframe/frontend/cli.py
  reframe/schemas/config.json
  unittests/test_schedulers.py
Labels: new feature, prio: normal

#3215 [bugfix] Fix logging crash when `timestamp=True` for the `file` log handler
  reframe/core/logging.py
Labels: prio: normal, bugfix

#3223 [bugfix] Fix report schema to properly accept all test results
  reframe/schemas/runreport.json
Labels: prio: normal, bugfix
