Repository reframe-hpc/reframe, pull requests merged in 2024-11, with the labels that each got.

#3296 [enhancement] Use builtin `json` package for decoding testcase data
  reframe/frontend/reporting/storage.py
Labels: prio: normal, enhancement, reporting

#3309 [ci] Enable Python 3.13 in CI + expand Github test workflows
  .github/workflows/main.yml
  setup.cfg
Labels: prio: normal, installation

#3314 [enhancement] Issue a more compact message when JSON schema validation fails
  reframe/core/config.py
  reframe/core/exceptions.py
  reframe/frontend/autodetect.py
  reframe/frontend/reporting/__init__.py
  unittests/resources/config/settings.py
Labels: prio: normal, enhancement, configuration

#3310 [enhancement] Warn instead of failing when a filter expression is invalid for test
  reframe/frontend/executors/__init__.py
  reframe/frontend/filters.py
  unittests/test_filters.py
Labels: prio: normal, enhancement, cli

#3307 [enhancement] Update `--table-format` arguments
  docs/manpage.rst
  docs/tutorial.rst
  reframe/frontend/cli.py
  reframe/frontend/printer.py
  reframe/frontend/reporting/__init__.py
  reframe/schemas/config.json
  unittests/test_cli.py
Labels: prio: normal, enhancement, reporting

#3293 [enhancement] Report the undefined parameters if an instantiation of an abstract test or fixture is attempted
  reframe/core/decorators.py
  reframe/core/fixtures.py
  reframe/core/parameters.py
  unittests/test_parameters.py
Labels: prio: normal, test syntax

#3316 [feat] Allow partition/environment extras to be used also as feature constraints in `valid_systems` and `valid_prog_environs`
  docs/config_reference.rst
  reframe/core/pipeline.py
  reframe/core/runtime.py
  unittests/test_pipeline.py
Labels: prio: normal, enhancement, test syntax

#3317 [feat] Make directory prefix for topology files configurable
  docs/config_reference.rst
  reframe/frontend/autodetect.py
  reframe/schemas/config.json
Labels: prio: normal, enhancement

#3313 [enhancement] Disable results storage by default
  examples/tutorial/scripts/runall.sh
  reframe/frontend/cli.py
  reframe/frontend/reporting/__init__.py
  reframe/schemas/config.json
  unittests/test_cli.py
Labels: prio: normal, enhancement, reporting

#3318 [bugfix] Add job options from the command-line to processor auto-detection remote job
  reframe/frontend/autodetect.py
  reframe/frontend/cli.py
  unittests/test_parameters.py
Labels: prio: normal, bugfix, autodetection

#3319 [doc] Remove tip for disabling storage results from documentation
  docs/tutorial.rst
Labels: prio: normal, documentation, enhancement, reporting

#3321 [doc] Update formatting of list of talks in the documentation
  docs/index.rst
Labels: prio: normal, documentation, enhancement
