Repository reframe-hpc/reframe, pull requests merged in 2025-02, with the labels that each got.

#3379 [bugfix] Make `getsid()` call persistent in `_ProcFuture.start()`
  reframe/utility/osext.py
Labels: prio: normal, bugfix

#3381 [bugfix] Fix `ESRCH` error due to race condition when spawning fast futures
  reframe/utility/osext.py
Labels: prio: important, bugfix

#3377 [bugfix] Fix assignment of default configuration parameters across systems
  reframe/core/config.py
  unittests/resources/config/settings.py
  unittests/test_config.py
Labels: prio: normal, bugfix

#3384 [doc] Update copyright year in docs
  docs/conf.py
Labels: prio: normal, documentation

#3370 [feat] Enable YAML configuration files
  docs/config_reference.rst
  docs/manpage.rst
  docs/requirements.txt
  docs/tutorial.rst
  examples/tutorial/config/baseline.yaml
  reframe/core/config.py
  reframe/utility/typecheck.py
  requirements.txt
  setup.cfg
  unittests/resources/config/bindings.yaml
  unittests/resources/config/settings.py
  unittests/resources/config/settings.yaml
  unittests/test_config.py
Labels: prio: normal, enhancement

#3383 [ci] Update Slurm cluster images to `ubuntu:22.04`
  .github/pseudo-cluster/docker-compose.yml
  .github/pseudo-cluster/reframe/Dockerfile
  .github/pseudo-cluster/reframe/docker-entrypoint.sh
  examples/tutorial/dockerfiles/slurm-cluster/docker-compose.yml
  examples/tutorial/dockerfiles/slurm-cluster/master/Dockerfile
  examples/tutorial/dockerfiles/slurm-cluster/master/docker-entrypoint.sh
  examples/tutorial/dockerfiles/slurm-cluster/master/slurm.conf
  examples/tutorial/dockerfiles/slurm-cluster/munge/Dockerfile
  examples/tutorial/dockerfiles/slurm-cluster/munge/entrypoint.sh
  examples/tutorial/dockerfiles/slurm-cluster/node/Dockerfile
  examples/tutorial/dockerfiles/slurm-cluster/node/cgroup.conf
  examples/tutorial/dockerfiles/slurm-cluster/node/docker-entrypoint.sh
  examples/tutorial/dockerfiles/slurm-cluster/node/slurm.conf
  examples/tutorial/dockerfiles/slurm-cluster/reframe/Dockerfile
  examples/tutorial/dockerfiles/slurm-cluster/reframe/cgroup.conf
  examples/tutorial/dockerfiles/slurm-cluster/reframe/docker-entrypoint.sh
  examples/tutorial/dockerfiles/slurm-cluster/reframe/slurm.conf
Labels: prio: normal, automation

#3388 [bugfix] Include test info when skipping tests
  reframe/frontend/executors/policies.py
Labels: prio: normal, bugfix

#3387 [ci] Remove stale Dockerfiles
  ci-scripts/dockerfiles/Lmod.dockerfile
  ci-scripts/dockerfiles/Lmod77.dockerfile
  ci-scripts/dockerfiles/Spack.dockerfile
  ci-scripts/dockerfiles/Tmod32.dockerfile
  ci-scripts/dockerfiles/Tmod4.dockerfile
Labels: prio: normal, automation

#3389 [doc] Fix tutorial on `--performance-report` default behaviour
  docs/tutorial.rst
Labels: prio: normal, documentation

#3390 [bugfix] Properly expand environment variables in execution modes
  reframe/frontend/cli.py
  unittests/resources/config/settings.py
  unittests/test_cli.py
  unittests/test_config.py
Labels: prio: normal, bugfix, cli

#3393 [bugfix] Do not copy or `git clone` `sourcesdir` if `--dont-restage` is passed
  docs/manpage.rst
  reframe/core/pipeline.py
  unittests/test_cli.py
Labels: prio: normal, bugfix

#3396 [ci] Replace symlinks with file copies in Docker compose config for Github workflows
  .github/pseudo-cluster/reframe/cgroup.conf
  .github/pseudo-cluster/reframe/slurm.conf
Labels: prio: important, automation

#3400 [bugfix] Fix bug in update of pipeline progress statistics
  reframe/frontend/executors/policies.py
Labels: prio: normal, bugfix, runtime

#3401 [ci] Fix wheel file pattern in the wheel validation Github action
  .github/workflows/main.yml
Labels: prio: important, automation, bugfix

#3395 [feat] Add support for configure directory in CMake builds
  reframe/core/buildsystems.py
Labels: prio: normal, enhancement, buildsystems

#3398 [bugfix] Mark the stagedir after the copy or clone of resources
  ci-scripts/dockerfiles/reframe-lmod77.dockerfile
  reframe/core/pipeline.py
  unittests/test_pipeline.py
  unittests/test_utility.py
Labels: prio: important, bugfix

#3405 [ci] Update YAML unit test config
  unittests/resources/config/settings.yaml
Labels: prio: important, automation

#3406 [ci] Use Python 3.13 to publish to PyPi
  .github/workflows/publish.yml
Labels: prio: normal, packaging
