Repository reframe-hpc/reframe, pull requests merged in 2025-01, with the labels that each got.

#3358 [enhancement] Report all failed performance variables in `FAILURE INFO`
  reframe/core/pipeline.py
  reframe/frontend/printer.py
Labels: prio: normal, enhancement

#3361 [bugfix] Treat a node in `PLANNED` Slurm state as available
  reframe/core/schedulers/slurm.py
Labels: prio: normal, bugfix, schedulers

#3356 [bugfix] Check response status in the `httpjson` log handler and retry in case of `TOO_MANY_REQUESTS`
  docs/config_reference.rst
  reframe/core/logging.py
  reframe/frontend/executors/__init__.py
  reframe/schemas/config.json
Labels: prio: normal, bugfix, logging

#3364 [bugfix] Add missing `topology_prefix` option in the configuration schema
  reframe/schemas/config.json
Labels: prio: normal, bugfix

#3365 [bugfix] Fix use of `dump_pipeline_progress` and `RFM_DUMP_PIPELINE_PROGRESS` options
  reframe/frontend/executors/policies.py
Labels: prio: normal, bugfix, configuration

#3368 [doc] Fix default value for results storage in documentation
  docs/config_reference.rst
Labels: prio: normal, documentation, bugfix
