Repository reframe-hpc/reframe, pull requests merged in 2025-04, with the labels that each got.

#3432 [bugfix] Disallow command options from execution modes
  docs/config_reference.rst
  docs/manpage.rst
  reframe/frontend/argparse.py
  reframe/frontend/cli.py
  unittests/test_argparser.py
Labels: prio: normal, bugfix

#3442 [feat] Allow changing the default mount location of stagedir inside containers
  reframe/core/containers.py
  reframe/core/pipeline.py
  unittests/test_containers.py
  unittests/test_pipeline.py
Labels: prio: normal, enhancement

#3441 [bugfix] Update special parameter character in test name
  reframe/core/pipeline.py
Labels: prio: normal, bugfix

#3452 [feat] Do not emit the `-lselect` option if `num_tasks=None`
  reframe/core/pipeline.py
  reframe/core/schedulers/pbs.py
  unittests/test_schedulers.py
Labels: prio: normal, enhancement, schedulers

#3450 [bugfix] Fix lock order when storing reports to the database
  reframe/frontend/reporting/storage.py
Labels: bugfix, reporting

#3449 [feat] Support list assignment from JSON using the `-S` option
  docs/manpage.rst
  reframe/utility/typecheck.py
  unittests/test_typecheck.py
Labels: prio: normal, enhancement

#3453 [doc] Add a note about results storage and analytics in README
  README.md
  README_minimal.md
  docs/index.rst
Labels: prio: normal, documentation, enhancement

#3448 [bugfix] Fix constraint evaluation for Slurm features starting with numbers
  reframe/core/schedulers/slurm.py
Labels: prio: normal, bugfix, schedulers

#3454 [bugfix] Treat correctly `failed_stage=None` in failure stats report
  reframe/frontend/printer.py
Labels: prio: normal, bugfix

#3456 [bugfix] Handle explicit scheduler options passed in the CLI in the remote auto-detection script
  reframe/frontend/autodetect.py
Labels: prio: normal, bugfix, autodetection

#3457 [doc] Document the requirement of file lock support for enabling results storage
  docs/manpage.rst
Labels: prio: normal, documentation, reporting

#3473 [doc] Fix typo in `versionadded` annotation
  reframe/core/launchers/__init__.py
Labels: prio: normal, documentation
