Repository reframe-hpc/reframe, pull requests merged in 2025-05, with the labels that each got.

#3474 [bugfix] Unset all `SBATCH_*` environment variables before submitting a job
  docs/config_reference.rst
  reframe/core/schedulers/slurm.py
  unittests/test_environments.py
Labels: prio: normal, bugfix, schedulers

#3472 [enhancement] Show up front if result storage is enabled
  reframe/frontend/cli.py
Labels: prio: normal, enhancement

#3470 [enhancement] Use `ClusterShell` to manipulate node lists instead of our own code
  docs/requirements.txt
  reframe/utility/__init__.py
  requirements.txt
  setup.cfg
  unittests/test_utility.py
Labels: prio: normal, code quality, enhancement

#3471 [bugfix] Use always `|` to join unique values in column aggregations except for `--table-format=pretty`
  reframe/frontend/reporting/__init__.py
Labels: prio: normal, bugfix, reporting

#3478 [enhancement] Use the `--use-pep517` option in `bootstrap.sh`
  bootstrap.sh
Labels: prio: normal, enhancement, packaging

#3464 [feat] Enable launchers to forward environment variables
  docs/config_reference.rst
  reframe/core/launchers/__init__.py
  reframe/core/launchers/mpi.py
  unittests/test_launchers.py
Labels: prio: normal, enhancement
