Repository reframe-hpc/reframe, pull requests merged in 2025-03, with the labels that each got.

#3391 [ci] Enabled slurmdbd in Docker compose setup
  .github/pseudo-cluster/docker-compose.yml
  .github/pseudo-cluster/reframe/Dockerfile
  .github/pseudo-cluster/reframe/docker-entrypoint.sh
  .github/workflows/test-schedulers.yaml
  ci-scripts/configs/ci-cluster.py
  docs/tutorial.rst
  examples/tutorial/dockerfiles/slurm-cluster/dbd/Dockerfile
  examples/tutorial/dockerfiles/slurm-cluster/dbd/cgroup.conf
  examples/tutorial/dockerfiles/slurm-cluster/dbd/docker-entrypoint.sh
  examples/tutorial/dockerfiles/slurm-cluster/dbd/slurm.conf
  examples/tutorial/dockerfiles/slurm-cluster/dbd/slurmdbd.conf
  examples/tutorial/dockerfiles/slurm-cluster/docker-compose.yml
  examples/tutorial/dockerfiles/slurm-cluster/master/Dockerfile
  examples/tutorial/dockerfiles/slurm-cluster/master/cgroup.conf
  examples/tutorial/dockerfiles/slurm-cluster/master/docker-entrypoint.sh
  examples/tutorial/dockerfiles/slurm-cluster/master/slurm.conf
  examples/tutorial/dockerfiles/slurm-cluster/munge/Dockerfile
  examples/tutorial/dockerfiles/slurm-cluster/munge/entrypoint.sh
  examples/tutorial/dockerfiles/slurm-cluster/node/Dockerfile
  examples/tutorial/dockerfiles/slurm-cluster/node/cgroup.conf
  examples/tutorial/dockerfiles/slurm-cluster/node/docker-entrypoint.sh
  examples/tutorial/dockerfiles/slurm-cluster/node/slurm.conf
  examples/tutorial/dockerfiles/slurm-cluster/reframe/Dockerfile
  examples/tutorial/dockerfiles/slurm-cluster/reframe/cgroup.conf
  examples/tutorial/dockerfiles/slurm-cluster/reframe/docker-entrypoint.sh
  examples/tutorial/dockerfiles/slurm-cluster/reframe/slurm.conf
Labels: prio: normal, automation

#3417 [ci] Add GH action to test older python versions
  .github/workflows/main.yml
  ci-scripts/dockerfiles/reframe-python.dockerfile
Labels: prio: normal

#3418 Make ReFrame more resilient to `sacct` temporary errors
  docs/config_reference.rst
  reframe/core/schedulers/slurm.py
  reframe/schemas/config.json
  unittests/test_config.py
Labels: prio: normal, enhancement, schedulers

#3414 [feat] Store test sub-result per performance variable
  docs/config_reference.rst
  docs/manpage.rst
  reframe/core/logging.py
  reframe/core/pipeline.py
  reframe/frontend/reporting/__init__.py
  unittests/test_perflogging.py
Labels: prio: normal, enhancement, logging

#3426 [doc] Add warning about combining `build_locally=0` and scheduler backends that cannot reliably retrieve the job's exit code
  reframe/core/pipeline.py
Labels: prio: normal, documentation, enhancement

#3425 [bugfix] Disable number parsing when in `--list-stored-sessions`
  reframe/frontend/cli.py
Labels: prio: normal, bugfix, reporting

#3429 [bugfix] Insert new line between stdout/stderr listings in failures
  reframe/frontend/printer.py
Labels: prio: normal, bugfix

#3433 [bugfix] Fix calculation of lower/upper reference bounds when their absolute value reaches zero
  reframe/utility/sanity.py
  unittests/test_sanity_functions.py
Labels: prio: normal, bugfix

#3434 [feat] Support reference values of zero
  reframe/core/pipeline.py
  reframe/utility/sanity.py
  unittests/test_sanity_functions.py
Labels: prio: normal, enhancement

#3440 [enhancement] List parameterized tests in their instantiation order
  reframe/core/decorators.py
  unittests/test_testgenerators.py
Labels: prio: normal, enhancement

#3431 [feat] Support selecting A/B column variants in performance comparisons
  docs/manpage.rst
  reframe/frontend/reporting/__init__.py
  unittests/test_cli.py
Labels: prio: normal, enhancement
